import type { SourceRecord } from "./types";

const HEADER = "<!-- Generated by npm run license:notices. Do not edit manually. -->\n# Third-party notices\n\n";

function markdownLink(label: string, url: string | undefined): string {
  return url?.startsWith("https://") ? `[${label}](${url})` : label;
}

function requiresNotice(record: SourceRecord): boolean {
  return record.decision === "SAFE_WITH_ATTRIBUTION" && record.attributionPlacement !== "NONE" && record.affectedPaths.length > 0;
}

export function noticeRecords(records: readonly SourceRecord[]): readonly SourceRecord[] {
  return records.filter(requiresNotice).slice().sort((left, right) => left.id.localeCompare(right.id));
}

export function renderThirdPartyNotices(records: readonly SourceRecord[]): string {
  const required = noticeRecords(records);
  if (required.length === 0) {
    return `${HEADER}No third-party source code, document assets, media, or datasets are redistributed by the current public application.\n\nResearch-only sources are recorded separately in \`docs/legal/source-registry.json\` and are not reproduced here.\n`;
  }
  const sections = required.map((record) => {
    const lines = [
      `## ${record.title}`,
      "",
      `- Owner: ${record.authorOrOwner}`,
      `- License: ${markdownLink(record.licenseId, record.evidence)}`,
      `- Source: ${markdownLink(record.publicSourceUrl ?? "Recorded source", record.publicSourceUrl)}`,
      `- Affected files: ${record.affectedPaths.map((value) => `\`${value}\``).join(", ")}`,
    ];
    if (record.copyrightNotice) lines.push(`- Copyright: ${record.copyrightNotice}`);
    if (record.notes) lines.push(`- Handling: ${record.notes}`);
    return lines.join("\n");
  });
  return `${HEADER}${sections.join("\n\n")}\n`;
}
