import type { InstrumentId, MarketAssetClass, MarketInstrument, ProviderId, VendorSymbolMapping } from "./domain";

const fx = (slug: string, symbol: string, name: string, baseCurrency: string, quoteCurrency: string): MarketInstrument => ({ id: `fx-${slug}`, slug, symbol, name, assetClass: "FX", instrumentType: "FX_SPOT", currency: quoteCurrency, exchange: null, timezone: "UTC", session: "24H", baseCurrency, quoteCurrency, pipSize: quoteCurrency === "JPY" ? .01 : .0001, displayPrecision: quoteCurrency === "JPY" ? 3 : 5, pricerMode: "fx", learnSlug: "/learn/fx/fx-spot" });
const equity = (symbol: string, name: string): MarketInstrument => ({ id: `eq-${symbol.toLowerCase()}`, slug: symbol.toLowerCase(), symbol, name, assetClass: "EQUITY", instrumentType: "EQUITY_SPOT", currency: "USD", exchange: "NASDAQ/NYSE", timezone: "America/New_York", session: "EXCHANGE", displayPrecision: 2, pricerMode: "equity", learnSlug: "/learn/equity/equity-forward" });
const index = (slug: string, symbol: string, name: string, currency: string, timezone: string): MarketInstrument => ({ id: `index-${slug}`, slug, symbol, name, assetClass: "INDEX", instrumentType: "INDEX_SPOT", currency, exchange: "INDEX", timezone, session: "EXCHANGE", displayPrecision: 2 });
const rate = (slug: string, symbol: string, name: string, type: "REFERENCE_RATE" | "POLICY_RATE" | "GOVERNMENT_YIELD"): MarketInstrument => ({ id: `rates-${slug}`, slug, symbol, name, assetClass: "RATES", instrumentType: type, currency: "EUR", exchange: "ECB", timezone: "Europe/Frankfurt", session: "REFERENCE", displayPrecision: 3, unit: "%", learnSlug: "/learn/rates/yield-curves" });
const commodity = (slug: string, symbol: string, name: string, unit: string): MarketInstrument => ({ id: `comm-${slug}`, slug, symbol, name, assetClass: "COMMODITY", instrumentType: "COMMODITY_REFERENCE", currency: "USD", exchange: null, timezone: "UTC", session: "EXCHANGE", displayPrecision: 2, unit, pricerMode: "forward", learnSlug: "/learn/commodities/spot-vs-futures" });
const crypto = (slug: string, symbol: string, name: string): MarketInstrument => ({ id: `crypto-${slug}`, slug, symbol, name, assetClass: "CRYPTO", instrumentType: "CRYPTO_SPOT", currency: "USD", exchange: "Coinbase Advanced", timezone: "UTC", session: "24H", baseCurrency: symbol.split("/")[0], quoteCurrency: "USD", displayPrecision: 2 });

export const instrumentMaster: MarketInstrument[] = [
  fx("eurusd", "EUR/USD", "Euro / US Dollar", "EUR", "USD"), fx("gbpusd", "GBP/USD", "Sterling / US Dollar", "GBP", "USD"), fx("usdjpy", "USD/JPY", "US Dollar / Japanese Yen", "USD", "JPY"), fx("usdchf", "USD/CHF", "US Dollar / Swiss Franc", "USD", "CHF"), fx("audusd", "AUD/USD", "Australian Dollar / US Dollar", "AUD", "USD"), fx("nzdusd", "NZD/USD", "New Zealand Dollar / US Dollar", "NZD", "USD"), fx("usdcad", "USD/CAD", "US Dollar / Canadian Dollar", "USD", "CAD"), fx("eurgbp", "EUR/GBP", "Euro / Sterling", "EUR", "GBP"), fx("eurjpy", "EUR/JPY", "Euro / Japanese Yen", "EUR", "JPY"), fx("eurchf", "EUR/CHF", "Euro / Swiss Franc", "EUR", "CHF"), fx("gbpjpy", "GBP/JPY", "Sterling / Japanese Yen", "GBP", "JPY"),
  ...[["AAPL","Apple"],["MSFT","Microsoft"],["NVDA","NVIDIA"],["AMZN","Amazon"],["META","Meta Platforms"],["GOOGL","Alphabet"],["TSLA","Tesla"],["JPM","JPMorgan Chase"],["GS","Goldman Sachs"],["BAC","Bank of America"],["XOM","Exxon Mobil"],["CVX","Chevron"]].map(([symbol,name]) => equity(symbol, name)),
  index("spx", "S&P 500", "S&P 500 Index", "USD", "America/New_York"), index("ndx", "NASDAQ 100", "Nasdaq 100 Index", "USD", "America/New_York"), index("dji", "DOW", "Dow Jones Industrial Average", "USD", "America/New_York"), index("stoxx50", "EURO STOXX 50", "Euro Stoxx 50 Index", "EUR", "Europe/Frankfurt"), index("dax", "DAX", "DAX Index", "EUR", "Europe/Berlin"), index("ftse", "FTSE 100", "FTSE 100 Index", "GBP", "Europe/London"), index("ibex", "IBEX 35", "IBEX 35 Index", "EUR", "Europe/Madrid"), index("nikkei", "NIKKEI 225", "Nikkei 225 Index", "JPY", "Asia/Tokyo"),
  rate("estr", "€STR", "Euro short-term rate", "REFERENCE_RATE"), rate("ecb-dfr", "ECB DFR", "ECB deposit facility", "POLICY_RATE"), rate("ecb-mro", "ECB MRO", "ECB main refinancing operations", "POLICY_RATE"), rate("eur2y", "EUR 2Y", "Euro-area 2Y benchmark yield", "GOVERNMENT_YIELD"), rate("eur10y", "EUR 10Y", "Euro-area 10Y benchmark yield", "GOVERNMENT_YIELD"),
  commodity("brent", "BRENT", "Brent reference proxy", "USD/barrel"), commodity("wti", "WTI", "WTI reference proxy", "USD/barrel"), commodity("gold", "GOLD", "Gold spot/reference proxy", "USD/oz"), commodity("silver", "SILVER", "Silver spot/reference proxy", "USD/oz"), commodity("natgas", "NAT GAS", "Natural gas reference proxy", "USD/MMBtu"), commodity("copper", "COPPER", "Copper reference proxy", "USD/lb"),
  crypto("btcusd", "BTC/USD", "Bitcoin / US Dollar"), crypto("ethusd", "ETH/USD", "Ether / US Dollar"),
];

const twelve = (instrument: MarketInstrument): VendorSymbolMapping => ({ instrumentId: instrument.id, provider: "TWELVE_DATA", vendorSymbol: instrument.symbol.includes("/") ? instrument.symbol : instrument.symbol.split(" ")[0] });
const finnhub = (instrument: MarketInstrument): VendorSymbolMapping => ({ instrumentId: instrument.id, provider: "FINNHUB", vendorSymbol: instrument.assetClass === "FX" ? `OANDA:${instrument.baseCurrency}_${instrument.quoteCurrency}` : instrument.symbol });
export const vendorSymbolMappings: VendorSymbolMapping[] = [
  ...instrumentMaster.filter((item) => ["FX","EQUITY","INDEX","COMMODITY","CRYPTO"].includes(item.assetClass)).flatMap((item) => [twelve(item), finnhub(item)]),
  ...instrumentMaster.filter((item) => item.assetClass === "FX").map((item) => ({ instrumentId: item.id, provider: "ECB" as const, vendorSymbol: `${item.baseCurrency}/${item.quoteCurrency}`, transform: item.baseCurrency === "EUR" ? "DIRECT" as const : "ECB_CROSS" as const, sourceUrl: `https://data.ecb.europa.eu/data/datasets/EXR/EXR.D.${item.quoteCurrency}.EUR.SP00.A` })),
  { instrumentId: "rates-estr", provider: "ECB", vendorSymbol: "EST.B.EU000A2X2A25.WT", sourceUrl: "https://data.ecb.europa.eu/data/datasets/EST/EST.B.EU000A2X2A25.WT" },
  { instrumentId: "rates-ecb-dfr", provider: "ECB", vendorSymbol: "FM.B.U2.EUR.4F.KR.DFR.LEV", sourceUrl: "https://data.ecb.europa.eu/data/datasets/FM/FM.B.U2.EUR.4F.KR.DFR.LEV" },
  { instrumentId: "crypto-btcusd", provider: "COINBASE", vendorSymbol: "BTC-USD", sourceUrl: "https://www.coinbase.com/advanced-trade/spot/BTC-USD" },
  { instrumentId: "crypto-ethusd", provider: "COINBASE", vendorSymbol: "ETH-USD", sourceUrl: "https://www.coinbase.com/advanced-trade/spot/ETH-USD" },
];

export const defaultWatchlistIds: InstrumentId[] = ["fx-eurusd", "fx-usdjpy", "eq-aapl", "eq-nvda", "rates-estr", "rates-ecb-dfr", "comm-brent", "comm-gold", "crypto-btcusd", "crypto-ethusd"];
export const homeTickerIds: InstrumentId[] = ["fx-eurusd", "fx-usdjpy", "rates-estr", "eq-aapl", "comm-brent", "crypto-btcusd"];

export function findInstrument(idOrSlugOrSymbol: string): MarketInstrument | undefined { const key = idOrSlugOrSymbol.toLowerCase().replaceAll("/", ""); return instrumentMaster.find((item) => item.id.toLowerCase() === key || item.slug === key || item.symbol.toLowerCase().replaceAll("/", "") === key); }
export function mappingsFor(instrumentId: InstrumentId, provider?: ProviderId): VendorSymbolMapping[] { return vendorSymbolMappings.filter((mapping) => mapping.instrumentId === instrumentId && (!provider || provider === "AUTO" || mapping.provider === provider)); }
export function instrumentCounts(): Record<MarketAssetClass, number> { return instrumentMaster.reduce((counts, item) => ({ ...counts, [item.assetClass]: counts[item.assetClass] + 1 }), { FX: 0, EQUITY: 0, INDEX: 0, RATES: 0, COMMODITY: 0, CRYPTO: 0 }); }
