"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useEffect, useMemo, useState } from "react";
import { defaultWatchlistIds, instrumentMaster } from "@/src/market-data/instrumentMaster";
import type { InstrumentId, MarketAssetClass, MarketDataMode, MarketInstrument, ProviderId } from "@/src/market-data/domain";
import { formatMarketPrice, formatSessionMove, formatTickMove } from "@/src/market-data/normalization";
import { useMarketQuote, useMarketSnapshot, useProviderHealth } from "@/src/market-data/client/hooks";
import { pick, useI18n } from "@/src/i18n";

const modeOptions: { value: MarketDataMode; label: string }[] = [{ value: "LIVE_STREAM", label: "LIVE" }, { value: "LIVE_SNAPSHOT", label: "SNAPSHOT" }, { value: "END_OF_DAY", label: "CLOSE" }, { value: "HISTORICAL", label: "HISTORICAL" }];
const assetOptions: (MarketAssetClass | "ALL")[] = ["ALL", "FX", "EQUITY", "INDEX", "RATES", "COMMODITY", "CRYPTO"];

export function MarketPulse() { return <MarketBoard />; }

function MarketBoard() {
  const { locale } = useI18n(); const [mode, setMode] = useState<MarketDataMode>("LIVE_STREAM"); const [provider, setProvider] = useState<ProviderId>("AUTO"); const [asset, setAsset] = useState<MarketAssetClass | "ALL">("ALL"); const [query, setQuery] = useState(""); const [sort, setSort] = useState<"watchlist" | "symbol" | "asset">("watchlist"); const [showUniverse, setShowUniverse] = useState(false); const [asOf, setAsOf] = useState(new Date().toISOString().slice(0, 10)); const [watchlist, setWatchlist] = useState<InstrumentId[]>(defaultWatchlistIds);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("tqb-market-watchlist") ?? "null"); if (Array.isArray(saved) && saved.every((id) => typeof id === "string")) window.setTimeout(() => setWatchlist(saved), 0); } catch { /* malformed device-local preference is ignored */ } }, []);
  const base = useMemo(() => showUniverse ? instrumentMaster : instrumentMaster.filter((instrument) => watchlist.includes(instrument.id)), [showUniverse, watchlist]);
  const instruments = useMemo(() => base.filter((instrument) => (asset === "ALL" || instrument.assetClass === asset) && `${instrument.symbol} ${instrument.name}`.toLowerCase().includes(query.toLowerCase())).sort((left, right) => sort === "asset" ? `${left.assetClass}${left.symbol}`.localeCompare(`${right.assetClass}${right.symbol}`) : sort === "symbol" ? left.symbol.localeCompare(right.symbol) : watchlist.indexOf(left.id) - watchlist.indexOf(right.id)), [asset, base, query, sort, watchlist]);
  const requestedIds = useMemo(() => instruments.map((instrument) => instrument.id), [instruments]); const market = useMarketSnapshot(requestedIds, mode, provider, mode === "HISTORICAL" ? asOf : undefined); const health = useProviderHealth();
  const toggleWatchlist = (id: InstrumentId) => setWatchlist((current) => { const next = current.includes(id) ? current.filter((item) => item !== id) : [...current, id]; localStorage.setItem("tqb-market-watchlist", JSON.stringify(next)); return next; });
  return <div className="markets-workstation">
    <header className="page-hero section-shell markets-hero"><div><span className="eyebrow">MARKET DATA WORKSTATION · NORMALIZED</span><h1>{pick(locale, { en: <>MARKET<br /><em>STATE.</em></>, es: <>ESTADO DE<br /><em>MERCADO.</em></> })}</h1><p>{pick(locale, { en: "Live where legally available, reference where authoritative, demo only where explicit. Every value exposes its source and as-of semantics.", es: "En vivo donde es legal, referencia donde es oficial y demo solo de forma explícita. Cada valor muestra fuente y fecha." })}</p></div><div className="market-connection"><span className={`connection-dot connection-${health.state.toLowerCase()}`} /><div><strong>{mode.replaceAll("_", " ")}</strong><small>{mode === "LIVE_STREAM" ? `COINBASE · ${health.state}` : "STATIC · NO TICK ANIMATION"}</small></div></div></header>
    <section className="market-controls section-shell" aria-label="Market data controls"><div className="market-mode"><span>MARKET STATE</span>{modeOptions.map((option) => <button key={option.value} className={mode === option.value ? "active" : ""} onClick={() => setMode(option.value)}>{option.label}{option.value === "LIVE_STREAM" && <i />}</button>)}</div><label><span>DATA SOURCE</span><select value={provider} onChange={(event) => setProvider(event.target.value as ProviderId)}><option value="AUTO">AUTO</option><option value="ECB">ECB</option><option value="DEMO">DEMO</option></select></label>{mode === "HISTORICAL" && <label><span>AS OF · UTC</span><input type="date" value={asOf} onChange={(event) => setAsOf(event.target.value)} max={new Date().toISOString().slice(0, 10)} /></label>}<div className="market-asof"><span>AS OF</span><strong>{market.snapshot?.asOf ? new Date(market.snapshot.asOf).toLocaleString(locale, { dateStyle: "medium", timeStyle: "short", timeZone: "UTC" }) : "LOADING"} UTC</strong></div></section>
    <section className="market-browser section-shell"><header className="market-browser-tools"><label><span>SEARCH UNIVERSE</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="EUR/USD, AAPL, €STR…" /></label><div className="asset-filter">{assetOptions.map((item) => <button className={asset === item ? "active" : ""} onClick={() => setAsset(item)} key={item}>{item}</button>)}</div><label><span>SORT</span><select value={sort} onChange={(event) => setSort(event.target.value as typeof sort)}><option value="watchlist">WATCHLIST</option><option value="symbol">SYMBOL</option><option value="asset">ASSET CLASS</option></select></label><button className="universe-toggle" onClick={() => setShowUniverse((value) => !value)}>{showUniverse ? "SHOW WATCHLIST" : `BROWSE UNIVERSE · ${instrumentMaster.length}`}</button></header>
      <div className="market-table" role="table" aria-label="Normalized market quotes"><div className="market-table-head" role="row"><span>WATCH</span><span>INSTRUMENT</span><span>LAST</span><span>TICK</span><span>SESSION / 24H</span><span>BID / ASK</span><span>SPARK</span><span>STATE · SOURCE</span></div>{instruments.map((instrument) => <MarketRow key={instrument.id} instrument={instrument} watched={watchlist.includes(instrument.id)} mode={mode} onToggle={() => toggleWatchlist(instrument.id)} />)}{!instruments.length && <div className="market-empty">No instruments match this view.</div>}</div>
      {market.error && <div className="market-error"><b>PROVIDER ERROR</b><span>{market.error}</span></div>}{market.loading && <div className="market-loading">NORMALIZING MARKET STATE…</div>}
    </section>
    <section className="market-source-guide section-shell"><div><span className="eyebrow">SOURCE TRANSPARENCY</span><h2>Inspect the input, not only the output.</h2><p>Each populated row links to the authoritative provider or exact instrument page. ECB values are daily references; Coinbase values are a private-beta public WebSocket demonstration; unsupported assets remain explicitly unavailable or demo.</p></div><a className="source-button" href="https://data.ecb.europa.eu/" target="_blank" rel="noreferrer">OPEN ECB DATA ↗</a><a className="source-button" href="https://docs.cdp.coinbase.com/coinbase-app/advanced-trade-apis/websocket/websocket-overview" target="_blank" rel="noreferrer">STREAM DOCUMENTATION ↗</a></section>
    <section className="market-branch section-shell"><div><span className="eyebrow">PUBLIC EVENT MARKETS</span><h2>{pick(locale, { en: "Macro probabilities, read only.", es: "Probabilidades macro, solo lectura." })}</h2><p>{pick(locale, { en: "Observed Polymarket prices now include direct source verification links.", es: "Los precios observados de Polymarket incluyen enlaces directos para verificar la fuente." })}</p></div><a className="button button-primary" href="/markets/predictions">{pick(locale, { en: "OPEN PREDICTIONS", es: "ABRIR PREDICCIONES" })} →</a></section>
  </div>;
}

function MarketRow({ instrument, watched, mode, onToggle }: { instrument: MarketInstrument; watched: boolean; mode: MarketDataMode; onToggle: () => void }) {
  const quote = useMarketQuote(instrument.id); const [flash, setFlash] = useState(""); const price = quote?.price;
  useEffect(() => { if (!quote || mode !== "LIVE_STREAM" || quote.tickDirection === "UNCHANGED") return; const start = window.setTimeout(() => setFlash(quote.tickDirection === "UP" ? "tick-up" : "tick-down"), 0); const finish = window.setTimeout(() => setFlash(""), 420); return () => { window.clearTimeout(start); window.clearTimeout(finish); }; }, [price, mode, quote]);
  const values = quote?.history.slice(-16) ?? []; const minimum = Math.min(...values); const maximum = Math.max(...values); const status = quote?.status ?? "OFFLINE"; const source = quote?.source ?? "Waiting";
  return <div className={`market-data-row ${flash}`} role="row"><button className={watched ? "watch active" : "watch"} onClick={onToggle} aria-label={`${watched ? "Remove" : "Add"} ${instrument.symbol} ${watched ? "from" : "to"} watchlist`}>{watched ? "◆" : "◇"}</button><a className="instrument-cell" href={`/markets/${instrument.slug}`}><strong>{instrument.symbol}</strong><small>{instrument.name}</small><em>{instrument.assetClass} · {instrument.instrumentType.replaceAll("_", " ")}</em></a><b className="last-cell">{quote ? formatMarketPrice(quote, instrument) : "—"}<i>{quote?.tickDirection === "UP" ? "↑" : quote?.tickDirection === "DOWN" ? "↓" : "·"}</i></b><span className={quote?.tickDirection === "DOWN" ? "negative" : quote?.tickDirection === "UP" ? "positive" : ""}>{quote ? formatTickMove(quote, instrument) : "—"}</span><span className={(quote?.sessionChange ?? 0) < 0 ? "negative" : (quote?.sessionChange ?? 0) > 0 ? "positive" : ""}>{quote ? formatSessionMove(quote, instrument) : "—"}<small>{quote?.sessionLabel ?? instrument.session}</small></span><span className="bid-ask">{quote?.bid !== null && quote?.bid !== undefined && quote?.ask !== null && quote?.ask !== undefined ? `${quote.bid.toFixed(instrument.displayPrecision)} / ${quote.ask.toFixed(instrument.displayPrecision)}` : "LAST ONLY"}<small>{quote?.spreadInPips !== null && quote?.spreadInPips !== undefined ? `${quote.spreadInPips.toFixed(1)}p spread` : "spread unavailable"}</small></span><span className="market-spark" aria-label="Recent observations">{values.map((value, index) => <i key={`${index}-${value}`} style={{ height: `${maximum === minimum ? 45 : 20 + (value - minimum) / (maximum - minimum) * 70}%` }} />)}</span><span className="market-lineage"><b className={`data-status status-${status.toLowerCase()}`}>{status}</b><small>{quote?.freshness ?? "OFFLINE"} · {source}</small>{quote?.sourceUrl ? <a href={quote.sourceUrl} target={quote.sourceUrl.startsWith("http") ? "_blank" : undefined} rel="noreferrer">VERIFY SOURCE ↗</a> : <em>NO SOURCE LINK</em>}</span></div>;
}
