"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { LineChart } from "@/src/components/charts/LineChart";
import { findMarketQuote, type MarketQuote } from "@/src/data/markets";
import { pick, useI18n } from "@/src/i18n";

export function MarketDetail({ symbol }: { symbol: string }) {
  const { locale } = useI18n(); const quote = findMarketQuote(symbol);
  if (!quote) return <div className="not-found section-shell"><span className="eyebrow">404 · MARKETS</span><h1>{pick(locale, { en: "Instrument not found.", es: "Instrumento no encontrado." })}</h1><a className="button button-primary" href="/markets">Markets</a></div>;
  const action = quote.assetClass === "FX" ? pick(locale, { en: "PRICE FX OPTION", es: "VALORAR OPCIÓN FX" }) : quote.assetClass === "COMM" ? pick(locale, { en: "OPEN BLACK-76", es: "ABRIR BLACK-76" }) : pick(locale, { en: "PRICE OPTION", es: "VALORAR OPCIÓN" });
  const pricer = `/lab?lab=vanilla&mode=${quote.pricerMode ?? "equity"}&symbol=${quote.symbol}&spot=${quote.price}`;
  return <div className="market-detail-page"><header className="market-detail-hero section-shell"><div><div className="breadcrumb"><a href="/markets">MARKETS</a><span>/</span><b>{quote.displaySymbol}</b></div><span className="eyebrow">{quote.assetClass} · {quote.name}</span><h1>{quote.displaySymbol}</h1><div className="detail-price"><strong>{formatPrice(quote)}</strong><em className={quote.changePercent >= 0 ? "positive" : "negative"}>{quote.changePercent >= 0 ? "+" : ""}{quote.changePercent.toFixed(2)}%</em></div></div><DataPassport quote={quote} /></header><section className="market-detail-grid section-shell"><article className="chart-card"><div className="chart-title"><div><span>{pick(locale, { en: "HISTORICAL PATH", es: "SERIE HISTÓRICA" })}</span><strong>{pick(locale, { en: "Frozen illustrative series", es: "Serie ilustrativa congelada" })}</strong></div><div className="range-picker">1D 5D 1M 3M 1Y</div></div><LineChart x={quote.history.map((_, index) => index)} series={[{ name: quote.displaySymbol, values: quote.history }]} xLabel="Observation" yLabel="Level" height={310} /></article><aside className="market-stats"><Stat label="OPEN" value={quote.open} /><Stat label="HIGH" value={quote.high} /><Stat label="LOW" value={quote.low} /><Stat label="PREV CLOSE" value={quote.previousClose} /><a className="button button-primary" href={pricer}>{action}<span>→</span></a>{quote.learnSlug && <a className="button button-secondary" href={quote.learnSlug}>{pick(locale, { en: "LEARN THE MODEL", es: "APRENDER EL MODELO" })}<span>→</span></a>}</aside></section></div>;
}

function formatPrice(quote: MarketQuote) { return quote.currency === "%" ? `${quote.price.toFixed(3)}%` : quote.price < 10 ? quote.price.toFixed(4) : quote.price.toFixed(2); }
function formatTimestamp(timestamp: string, locale: "en" | "es") { return new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short", timeZone: "UTC", hour12: false }).format(new Date(timestamp)) + " UTC"; }
function Stat({ label, value }: { label: string; value: number }) { return <div><span>{label}</span><strong>{value < 10 ? value.toFixed(4) : value.toFixed(2)}</strong></div>; }
function DataPassport({ quote }: { quote: MarketQuote }) { const { locale } = useI18n(); return <aside className="data-passport"><span>{pick(locale, { en: "DATA PASSPORT", es: "PASAPORTE DE DATOS" })}</span><dl><dt>{pick(locale, { en: "STATUS", es: "ESTADO" })}</dt><dd>{quote.status.replaceAll("_", " ")}</dd><dt>{pick(locale, { en: "SOURCE", es: "FUENTE" })}</dt><dd>{quote.source}</dd><dt>{pick(locale, { en: "MARKET TIME", es: "HORA DE MERCADO" })}</dt><dd>{formatTimestamp(quote.marketTimestamp, locale)}</dd><dt>{pick(locale, { en: "RECEIVED", es: "RECIBIDO" })}</dt><dd>{formatTimestamp(quote.receivedTimestamp, locale)}</dd></dl><small>{quote.status === "DEMO" ? pick(locale, { en: "Frozen educational scenario. Not a tradable quote.", es: "Escenario educativo congelado. No es una cotización negociable." }) : pick(locale, { en: "Public reference observation, not a streaming quote.", es: "Observación pública de referencia, no una cotización en streaming." })}</small></aside>; }
