"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useMemo, useState } from "react";
import { LineChart } from "@/src/components/charts/LineChart";
import { findInstrument } from "@/src/market-data/instrumentMaster";
import type { MarketDataMode, MarketQuote } from "@/src/market-data/domain";
import { formatMarketPrice, formatSessionMove, formatTickMove } from "@/src/market-data/normalization";
import { useMarketQuote, useMarketSnapshot, useProviderHealth } from "@/src/market-data/client/hooks";
import { marketIntelligenceMetrics } from "@/src/data/marketMetrics";
import { pick, useI18n } from "@/src/i18n";

export function MarketDetail({ symbol }: { symbol: string }) {
  const { locale } = useI18n(); const instrument = findInstrument(symbol); const [mode, setMode] = useState<MarketDataMode>("LIVE_STREAM"); const [asOf, setAsOf] = useState(new Date().toISOString().slice(0, 10)); const ids = useMemo(() => instrument ? [instrument.id] : [], [instrument]); const state = useMarketSnapshot(ids, mode, "AUTO", mode === "HISTORICAL" ? asOf : undefined); const quote = useMarketQuote(instrument?.id ?? "missing"); const health = useProviderHealth();
  if (!instrument) return <div className="not-found section-shell"><span className="eyebrow">404 · MARKETS</span><h1>{pick(locale, { en: "Instrument not found.", es: "Instrumento no encontrado." })}</h1><a className="button button-primary" href="/markets">Markets</a></div>;
  const action = instrument.assetClass === "FX" ? pick(locale, { en: "PRICE FX OPTION", es: "VALORAR OPCIÓN FX" }) : instrument.assetClass === "COMMODITY" ? pick(locale, { en: "OPEN BLACK-76", es: "ABRIR BLACK-76" }) : pick(locale, { en: "PRICE OPTION", es: "VALORAR OPCIÓN" });
  const price = quote?.price; const pricer = !quote || price === null || price === undefined ? "/lab?lab=vanilla" : `/lab?lab=vanilla&mode=${instrument.pricerMode ?? "equity"}&instrumentId=${instrument.id}&symbol=${encodeURIComponent(instrument.symbol.replaceAll("/", ""))}&spot=${price}&source=${encodeURIComponent(quote.source)}&status=${quote.status}&asOf=${encodeURIComponent(quote.asOf)}&dataMode=${quote.dataMode}`; const metrics = marketIntelligenceMetrics(quote?.history ?? []);
  return <div className="market-detail-page"><header className="market-detail-hero section-shell"><div><div className="breadcrumb"><a href="/markets">MARKETS</a><span>/</span><b>{instrument.symbol}</b></div><span className="eyebrow">{instrument.assetClass} · {instrument.instrumentType.replaceAll("_", " ")}</span><h1>{instrument.symbol}</h1><div className="detail-price"><strong>{quote ? formatMarketPrice(quote, instrument) : "—"}</strong><em className={(quote?.sessionChange ?? 0) >= 0 ? "positive" : "negative"}>{quote ? formatSessionMove(quote, instrument) : "LOADING"}</em><i>{quote?.tickDirection === "UP" ? "↑" : quote?.tickDirection === "DOWN" ? "↓" : "·"}</i></div><p>{instrument.name} · {instrument.exchange ?? "OTC / reference"}</p></div>{quote ? <DataPassport quote={quote} health={health.state} /> : <aside className="data-passport"><span>DATA PASSPORT</span><p>{state.error || "Normalizing quote…"}</p></aside>}</header>
    <section className="detail-mode-bar section-shell"><div><span>MARKET STATE</span>{(["LIVE_STREAM", "LIVE_SNAPSHOT", "END_OF_DAY", "HISTORICAL"] as MarketDataMode[]).map((item) => <button key={item} className={mode === item ? "active" : ""} onClick={() => setMode(item)}>{item === "LIVE_STREAM" ? "LIVE" : item === "LIVE_SNAPSHOT" ? "SNAPSHOT" : item === "END_OF_DAY" ? "CLOSE" : "HISTORICAL"}</button>)}</div>{mode === "HISTORICAL" && <label><span>AS OF</span><input type="date" value={asOf} onChange={(event) => setAsOf(event.target.value)} /></label>}<strong>{quote?.resolution ?? "resolution pending"}</strong></section>
    <section className="market-detail-grid section-shell"><article className="chart-card"><div className="chart-title"><div><span>{mode === "LIVE_STREAM" ? "LIVE + RECENT PATH" : "NORMALIZED HISTORY"}</span><strong>{quote?.resolution ?? "Waiting for a supported source"}</strong></div><div className="range-picker">1D 5D 1M 3M 6M 1Y</div></div>{quote?.history.length ? <LineChart x={quote.history.map((_, index) => index)} series={[{ name: instrument.symbol, values: quote.history }]} xLabel="Observation" yLabel="Level" height={310} /> : <div className="chart-unavailable">No legitimate history is available for this provider and mode.</div>}<footer className="chart-lineage">AS OF {quote?.asOf ?? "—"} · {quote?.source ?? "—"}{quote?.notice && <span>{quote.notice}</span>}</footer></article><aside className="market-stats"><Stat label="LAST" value={quote ? formatMarketPrice(quote, instrument) : "—"} /><Stat label="PREVIOUS TICK" value={quote?.previousPrice === null || quote?.previousPrice === undefined ? "—" : quote.previousPrice.toFixed(instrument.displayPrecision)} /><Stat label="TICK MOVE" value={quote ? formatTickMove(quote, instrument) : "—"} /><Stat label="SESSION / 24H" value={quote ? formatSessionMove(quote, instrument) : "—"} /><Stat label="BID" value={field(quote?.bid, instrument.displayPrecision)} /><Stat label="ASK" value={field(quote?.ask, instrument.displayPrecision)} /><Stat label="SPREAD" value={quote?.spreadInPips !== null && quote?.spreadInPips !== undefined ? `${quote.spreadInPips.toFixed(2)} pips` : field(quote?.spread, instrument.displayPrecision)} /><Stat label="OPEN" value={field(quote?.open, instrument.displayPrecision)} /><Stat label="HIGH" value={field(quote?.high, instrument.displayPrecision)} /><Stat label="LOW" value={field(quote?.low, instrument.displayPrecision)} /><Stat label="5D RETURN" value={`${signed(metrics.return5D)}%`} /><Stat label="Z-SCORE" value={metrics.zScore20D?.toFixed(2) ?? "n/a"} /></aside></section>
    <section className="detail-actions section-shell"><a className="button button-primary" href={pricer} aria-disabled={price === null || price === undefined}>{action}<span>→</span></a><a className="button button-secondary" href="/analytics">OPEN ANALYTICS<span>→</span></a>{instrument.learnSlug && <a className="button button-secondary" href={instrument.learnSlug}>LEARN INSTRUMENT<span>→</span></a>}<a className="button button-secondary" href={`/ask?topic=${encodeURIComponent(instrument.name)}`}>ASK AI<span>→</span></a></section>
  </div>;
}

const signed = (value: number) => `${value >= 0 ? "+" : ""}${value.toFixed(2)}`;
const field = (value: number | null | undefined, precision: number) => value === null || value === undefined ? "—" : value.toFixed(precision);
function Stat({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function DataPassport({ quote, health }: { quote: MarketQuote; health: string }) { const { locale } = useI18n(); return <aside className="data-passport"><span>{pick(locale, { en: "DATA PASSPORT", es: "PASAPORTE DE DATOS" })}</span><dl><dt>STATE</dt><dd>{quote.dataMode.replaceAll("_", " ")}</dd><dt>STATUS</dt><dd>{quote.status} · {quote.freshness}</dd><dt>SOURCE</dt><dd>{quote.source}</dd><dt>MARKET TIME</dt><dd>{quote.marketTimestamp ? new Date(quote.marketTimestamp).toISOString() : "unavailable"}</dd><dt>RECEIVED</dt><dd>{new Date(quote.receivedTimestamp).toISOString()}</dd><dt>LATENCY</dt><dd>{quote.latencyMs === null ? "not supplied" : `${quote.latencyMs} ms`}</dd><dt>TRANSPORT</dt><dd>{health}</dd></dl>{quote.sourceUrl && <a className="source-button" href={quote.sourceUrl} target={quote.sourceUrl.startsWith("http") ? "_blank" : undefined} rel="noreferrer">VERIFY SOURCE INPUT ↗</a>}<small>{quote.notice ?? "Normalized by the shared market-data layer."}</small></aside>; }
