"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useEffect, useState } from "react";
import type { PredictionBook, PredictionCoverage, PredictionEvent, PredictionLivePatch, PredictionMarket } from "@/src/polymarket/domain";
import { pick, useI18n } from "@/src/i18n";

type Payload = { source: string; status: string; receivedAt: string; events: PredictionEvent[]; markets: PredictionMarket[]; error?: string; persistence?: { persistent: boolean; rows: number }; coverage?: PredictionCoverage | null };
type Sort = "volume" | "activity" | "movers" | "liquidity" | "probability";
const compact = (value: number) => new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 1 }).format(value);
const percent = (value: number | null, digits = 1) => value === null ? "—" : `${(value * 100).toFixed(digits)}%`;

export function PredictionNav({ active }: { active: "dashboard" | "explorer" | "study" | "health" }) {
  return <nav className="prediction-nav" aria-label="Prediction intelligence"><a className={active === "dashboard" ? "active" : ""} href="/markets/predictions">Dashboard</a><a className={active === "explorer" ? "active" : ""} href="/intelligence/data">Data Explorer</a><a className={active === "study" ? "active" : ""} href="/intelligence/event-study">Event Study</a><a className={active === "health" ? "active" : ""} href="/dev/data">Pipeline Health</a></nav>;
}

export function PredictionsDashboard({ compactView = false }: { compactView?: boolean }) {
  const { locale } = useI18n(); const [payload, setPayload] = useState<Payload | null>(null); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [category, setCategory] = useState("ALL"); const [sort, setSort] = useState<Sort>("activity"); const [live, setLive] = useState<Record<string, { probability: number; at: number; direction: "UP" | "DOWN" | "UNCHANGED" }>>({}); const [streamStatus, setStreamStatus] = useState("CONNECTING");
  useEffect(() => { const controller = new AbortController(); fetch("/api/predictions?limit=50", { signal: controller.signal }).then(async (response) => { const data = await response.json() as Payload; if (!response.ok) throw new Error(data.error || "Unavailable"); setPayload(data); }).catch((reason: Error & { name?: string }) => { if (reason.name !== "AbortError") setError(reason.message); }); return () => controller.abort(); }, []);
  useEffect(() => {
    if (!payload || compactView) return; const subscriptions = payload.markets.filter((market) => market.acceptingOrders).slice(0, 24).flatMap((market) => market.outcomes[market.primaryOutcomeIndex] ? [{ marketId: market.id, tokenId: market.outcomes[market.primaryOutcomeIndex].tokenId }] : []); if (!subscriptions.length) return;
    const stream = new EventSource(`/api/predictions/live?tokens=${subscriptions.map((item) => item.tokenId).join(",")}&markets=${subscriptions.map((item) => item.marketId).join(",")}`);
    let polling: ReturnType<typeof setInterval> | null = null; let fallback: ReturnType<typeof setTimeout> | null = null; let stopped = false;
    const applyQuote = (marketId: string, probability: number, observedAt: number) => setLive((current) => { const previous = current[marketId]?.probability ?? payload.markets.find((market) => market.id === marketId)?.probability ?? probability; return { ...current, [marketId]: { probability, at: observedAt, direction: probability > previous ? "UP" : probability < previous ? "DOWN" : "UNCHANGED" } }; });
    const poll = () => { void fetch(`/api/predictions/books?tokens=${subscriptions.map((item) => item.tokenId).join(",")}&markets=${subscriptions.map((item) => item.marketId).join(",")}`).then((response) => response.json() as Promise<{ books?: PredictionBook[] }>).then((result) => { for (const book of result.books ?? []) if (book.mid !== null) applyQuote(book.marketId, book.mid, book.observedAt); }).catch(() => setStreamStatus("RECONNECTING")); };
    const startPolling = () => { if (polling || stopped) return; stream.close(); setStreamStatus("LIVE · POLLED"); poll(); polling = setInterval(poll, 3_000); };
    stream.addEventListener("patch", (event) => { const patch = JSON.parse((event as MessageEvent<string>).data) as PredictionLivePatch; if (patch.type === "status") setStreamStatus(patch.status); if (patch.type === "quote") { if (fallback) { clearTimeout(fallback); fallback = null; } const next = patch.mid ?? patch.last; if (next !== null) applyQuote(patch.marketId, next, patch.observedAt); } });
    stream.onerror = startPolling; fallback = setTimeout(startPolling, 4_000); return () => { stopped = true; stream.close(); if (polling) clearInterval(polling); if (fallback) clearTimeout(fallback); };
  }, [payload, compactView]);
  if (error) return <div className="prediction-state"><span>POLYMARKET · UNAVAILABLE</span><p>{pick(locale, { en: "Public prediction data could not be loaded. No probabilities were fabricated.", es: "No se pudieron cargar los datos públicos. No se han inventado probabilidades." })}</p><small>{error}</small></div>;
  if (!payload) return <div className="prediction-state"><span>POLYMARKET · READ ONLY</span><p>{pick(locale, { en: "Discovering events and normalizing outcome tokens…", es: "Descubriendo eventos y normalizando tokens…" })}</p></div>;
  const categories = ["ALL", ...new Set(payload.events.map((event) => event.category).filter(Boolean))].slice(0, 10);
  const filtered = payload.events.filter((event) => { const term = query.trim().toLowerCase(); return (category === "ALL" || event.category === category) && (!term || `${event.title} ${event.description} ${event.markets.map((market) => market.question).join(" ")}`.toLowerCase().includes(term)); }).sort((left, right) => sortValue(right, sort) - sortValue(left, sort));
  const movers = [...payload.markets].filter((market) => market.change1d !== null).sort((left, right) => Math.abs(right.change1d ?? 0) - Math.abs(left.change1d ?? 0)).slice(0, 5);
  if (compactView) return <section className="predictions predictions-compact"><div className="module-head"><div><span className="eyebrow">PUBLIC PREDICTIONS · READ ONLY</span><h2>{pick(locale, { en: "Live probability board", es: "Panel de probabilidades" })}</h2></div><a href="/markets/predictions">{pick(locale, { en: "Open workstation", es: "Abrir estación" })} →</a></div><div className="prediction-grid">{filtered.slice(0, 4).map((event) => <EventCard event={event} live={live} locale={locale} key={event.id} />)}</div></section>;
  return <div className="prediction-workstation">
    <PredictionNav active="dashboard" />
    <header className="page-hero compact-hero section-shell predictions-hero"><div><span className="eyebrow">POLYMARKET INTELLIGENCE · PUBLIC READ ONLY</span><h1>{pick(locale, { en: <>EVENT RISK,<br /><em>IN MARKET STATE.</em></>, es: <>RIESGO DE EVENTO,<br /><em>EN ESTADO DE MERCADO.</em></> })}</h1><p>{pick(locale, { en: "Discovery, live L2 books, trades, open interest and persisted probability history. No wallet, order entry or investment recommendation.", es: "Descubrimiento, libro L2, operaciones, interés abierto e historial persistido. Sin cartera, órdenes ni recomendaciones." })}</p></div><DataState payload={payload} streamStatus={streamStatus} /></header>
    <section className="prediction-kpis section-shell"><Kpi label="EVENTS" value={String(payload.events.length)} note={`${payload.markets.length} markets`} /><Kpi label="OUTCOME TOKENS" value={String(payload.markets.reduce((sum, market) => sum + market.outcomes.length, 0))} note="distinct stream assets" /><Kpi label="24H VOLUME" value={`$${compact(payload.markets.reduce((sum, market) => sum + market.volume24h, 0))}`} note="discovered set" /><Kpi label="PIPELINE" value={payload.coverage?.persistent ? "DURABLE" : "LIVE ONLY"} note={payload.coverage?.persistent ? `${payload.coverage.bars} history rows` : "D1 unavailable locally"} /></section>
    <section className="prediction-screener section-shell"><div className="prediction-controls"><label><span>SEARCH EVENTS</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Fed, election, Bitcoin…" /></label><label><span>CATEGORY</span><select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map((item) => <option value={item} key={item}>{item}</option>)}</select></label><label><span>RANK BY</span><select value={sort} onChange={(event) => setSort(event.target.value as Sort)}><option value="activity">24H activity</option><option value="movers">Largest move</option><option value="volume">All-time volume</option><option value="liquidity">Liquidity</option><option value="probability">Probability</option></select></label></div><div className="mover-strip"><span>TOP MOVERS · 24H</span>{movers.map((market) => <a href={`/markets/predictions/${market.eventId}?market=${market.id}`} key={market.id}><b className={(market.change1d ?? 0) >= 0 ? "positive" : "negative"}>{(market.change1d ?? 0) >= 0 ? "+" : ""}{((market.change1d ?? 0) * 100).toFixed(1)}pp</b><small>{market.question}</small></a>)}</div></section>
    <section className="prediction-results section-shell"><header><div><span className="eyebrow">EVENT SCREENER</span><h2>{filtered.length} live events</h2></div><small>INITIAL SNAPSHOT + INCREMENTAL LIVE BOOK UPDATES</small></header><div className="prediction-grid">{filtered.map((event) => <EventCard event={event} live={live} locale={locale} key={event.id} />)}</div></section>
    <aside className="probability-note section-shell"><span>SEMANTICS · NOT OBJECTIVE PROBABILITY</span><p>{pick(locale, { en: "A 63% outcome token is the current market-implied trading coordinate. Liquidity, spread, fees, risk preference, participant beliefs and resolution rules matter. Midpoints are analytical, not necessarily executable.", es: "Un token al 63% es la coordenada implícita actual. Importan liquidez, spread, comisiones, preferencias, creencias y reglas de resolución. El punto medio no es necesariamente ejecutable." })}</p><a href="/learn/foundations/prediction-market-probabilities">{pick(locale, { en: "Learn the microstructure", es: "Aprender microestructura" })} →</a></aside>
  </div>;
}

function EventCard({ event, live, locale }: { event: PredictionEvent; live: Record<string, { probability: number; at: number; direction: "UP" | "DOWN" | "UNCHANGED" }>; locale: "en" | "es" }) {
  const activeMarkets = event.markets.filter((market) => market.active && !market.closed); const primary = [...activeMarkets].sort((left, right) => right.volume24h - left.volume24h)[0] ?? event.markets[0]; if (!primary) return null; const tick = live[primary.id]; const probability = tick?.probability ?? primary.probability; const href = `/markets/predictions/${event.slug}?market=${primary.id}`;
  return <article className="prediction-card"><a className="prediction-card-main" href={href}><header><span>{event.category || "EVENT"} · {event.marketCount} MARKET{event.marketCount === 1 ? "" : "S"}</span><b className={tick ? `tick-${tick.direction.toLowerCase()}` : ""}>{percent(probability)}{tick?.direction === "UP" ? " ↑" : tick?.direction === "DOWN" ? " ↓" : ""}</b></header><h3>{event.title}</h3><p>{primary.question}</p><dl><div><dt>24H VOL</dt><dd>${compact(primary.volume24h)}</dd></div><div><dt>LIQUIDITY</dt><dd>${compact(primary.liquidity)}</dd></div><div><dt>SPREAD</dt><dd>{primary.spread === null ? "—" : `${(primary.spread * 100).toFixed(1)}pp`}</dd></div></dl><footer><span>{new Date(tick?.at ?? primary.updatedAt).toLocaleString(locale, { dateStyle: "medium", timeStyle: "short" })}</span><b>{tick ? "LIVE PATCH" : "API SNAPSHOT"}</b></footer></a><div className="prediction-card-links"><a href={href}>OPEN EVENT →</a><a href={event.sourceUrl} target="_blank" rel="noreferrer">VERIFY ↗</a></div></article>;
}

function sortValue(event: PredictionEvent, sort: Sort): number { const markets = event.markets; if (sort === "activity") return markets.reduce((sum, market) => sum + market.volume24h, 0); if (sort === "movers") return Math.max(...markets.map((market) => Math.abs(market.change1d ?? 0)), 0); if (sort === "liquidity") return event.liquidity; if (sort === "probability") return Math.max(...markets.map((market) => market.probability ?? 0), 0); return event.volume; }
function Kpi({ label, value, note }: { label: string; value: string; note: string }) { return <article><span>{label}</span><b>{value}</b><small>{note}</small></article>; }
function DataState({ payload, streamStatus }: { payload: Payload; streamStatus: string }) { return <aside className="data-passport"><span>DATA PASSPORT</span><dl><dt>DISCOVERY</dt><dd>GAMMA · LIVE</dd><dt>STREAM</dt><dd>{streamStatus}</dd><dt>PERSISTENCE</dt><dd>{payload.coverage?.persistent ? "D1 · ACTIVE" : "LIVE FALLBACK"}</dd><dt>RECEIVED</dt><dd>{new Date(payload.receivedAt).toISOString()}</dd></dl><a className="source-button" href="https://docs.polymarket.com/market-data/overview" target="_blank" rel="noreferrer">OFFICIAL API MAP ↗</a><small>Observed public data. Trading intentionally excluded.</small></aside>; }
