"use client";
import { useEffect, useMemo, useState } from "react";
import { LineChart } from "@/src/components/charts/LineChart";
import type { MarketQuote } from "@/src/market-data/domain";
import type { PredictionEvent, PredictionHistoryPoint } from "@/src/polymarket/domain";
import { curatedLinksForEvent } from "@/src/polymarket/crossAsset";
import { PredictionNav } from "./PredictionsDashboard";

export function PredictionEventStudy() {
  const [events, setEvents] = useState<PredictionEvent[]>([]); const [eventId, setEventId] = useState(""); const [history, setHistory] = useState<PredictionHistoryPoint[]>([]); const [quote, setQuote] = useState<MarketQuote | null>(null);
  useEffect(() => { fetch("/api/predictions/events?limit=80&order=volume24hr").then((response) => response.json() as Promise<{ events?: PredictionEvent[] }>).then((payload) => { const next = (payload.events ?? []).filter((event) => curatedLinksForEvent(event.title, event.description).length); setEvents(next); setEventId((current) => current || next[0]?.id || ""); }).catch(() => undefined); }, []);
  const event = events.find((item) => item.id === eventId) ?? null; const market = event?.markets.filter((item) => item.active && !item.closed).sort((left, right) => right.volume24h - left.volume24h)[0] ?? null; const outcome = market?.outcomes[market.primaryOutcomeIndex] ?? null; const links = useMemo(() => event ? curatedLinksForEvent(event.title, event.description) : [], [event]); const [instrumentId, setInstrumentId] = useState(""); const selectedLink = links.find((link) => link.instrument.id === instrumentId) ?? links[0] ?? null;
  useEffect(() => { if (!outcome || !selectedLink) return; const controller = new AbortController(); Promise.all([
    fetch(`/api/predictions/markets/${outcome.tokenId}/history?range=30d`, { signal: controller.signal }).then((response) => response.json() as Promise<{ points?: PredictionHistoryPoint[] }>),
    fetch(`/api/markets/snapshot?ids=${selectedLink.instrument.id}&mode=HISTORICAL`, { signal: controller.signal }).then((response) => response.json() as Promise<{ quotes?: MarketQuote[] }>),
  ]).then(([prediction, traditional]) => { setHistory(prediction.points ?? []); setQuote(traditional.quotes?.[0] ?? null); }).catch(() => { setHistory([]); setQuote(null); }); return () => controller.abort(); }, [outcome, selectedLink]);
  const normalized = quote?.history.length ? quote.history.map((value) => value / quote.history[0] * 100) : [];
  return <div className="event-study-page"><PredictionNav active="study" /><header className="page-hero compact-hero section-shell"><div><span className="eyebrow">CURATED CROSS-ASSET EVENT STUDY</span><h1>EVENT ODDS,<br /><em>MARKET CONTEXT.</em></h1><p>Compare a persisted prediction path with an explicitly related traditional-market series. Units remain separate; association is never presented as causality.</p></div></header>
    <section className="event-study-controls section-shell"><label><span>PREDICTION EVENT</span><select value={eventId} onChange={(change) => setEventId(change.target.value)}>{events.map((item) => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><label><span>CURATED UNDERLYING</span><select value={selectedLink?.instrument.id ?? ""} onChange={(change) => setInstrumentId(change.target.value)}>{links.map((link) => <option value={link.instrument.id} key={link.instrument.id}>{link.instrument.symbol} · {link.instrument.name}</option>)}</select></label></section>
    <section className="event-study-grid section-shell"><article><header><span className="eyebrow">POLYMARKET · PROBABILITY %</span><h2>{market?.question ?? "Select a linked event"}</h2></header>{history.length > 1 ? <LineChart x={history.map((point) => point.timestamp)} series={[{ name: "Implied probability", values: history.map((point) => point.probability * 100) }]} xLabel="Unix ms" yLabel="Probability %" height={280} /> : <p className="empty-state">Prediction history is loading or unavailable.</p>}</article><article><header><span className="eyebrow">TRADITIONAL MARKET · INDEXED TO 100</span><h2>{selectedLink?.instrument.symbol ?? "No curated relationship"}</h2></header>{normalized.length > 1 ? <LineChart x={normalized.map((_, index) => index)} series={[{ name: selectedLink?.instrument.symbol ?? "Market", values: normalized }]} xLabel="Observation" yLabel="Index (100)" height={280} /> : <p className="empty-state">No legally displayable traditional history is configured.</p>}</article></section>
    {selectedLink && <section className="study-rationale section-shell"><div><span>CURATION RATIONALE</span><p>{selectedLink.rationale}</p><small>Traditional series: {quote?.status ?? "UNAVAILABLE"} · {quote?.source ?? "NO PROVIDER"}. Observation-index alignment is shown when point timestamps are not supplied; no spurious time synchronisation is claimed.</small></div><a className="button button-primary" href={selectedLink.learnHref}>WHY A QUANT CARES →</a></section>}
  </div>;
}
