"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { useEffect, useMemo, useState } from "react";
import { LineChart } from "@/src/components/charts/LineChart";
import { formatTimestamp } from "@/src/components/charts/chartModel";
import type { PredictionBook, PredictionEvent, PredictionHistoryPoint, PredictionLivePatch, PredictionStats, PredictionTrade } from "@/src/polymarket/domain";
import { pick, useI18n } from "@/src/i18n";
import { PredictionNav } from "./PredictionsDashboard";

type EventPayload = { event: PredictionEvent; error?: string };
type Range = "1h" | "1d" | "7d" | "30d" | "all";
const compact = (value: number) => new Intl.NumberFormat("en", { notation: "compact", maximumFractionDigits: 2 }).format(value);
const probability = (value: number | null) => value === null ? "—" : `${(value * 100).toFixed(1)}%`;

export function PredictionEventDetail({ slug, initialMarketId }: { slug: string; initialMarketId?: string }) {
  const { locale } = useI18n(); const [event, setEvent] = useState<PredictionEvent | null>(null); const [error, setError] = useState(""); const [range, setRange] = useState<Range>("7d"); const [history, setHistory] = useState<PredictionHistoryPoint[]>([]); const [historyOrigin, setHistoryOrigin] = useState(""); const [book, setBook] = useState<PredictionBook | null>(null); const [trades, setTrades] = useState<PredictionTrade[]>([]); const [stats, setStats] = useState<PredictionStats | null>(null); const [streamStatus, setStreamStatus] = useState("CONNECTING"); const [last, setLast] = useState<number | null>(null);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/predictions/events/${encodeURIComponent(slug)}`, { signal: controller.signal }).then(async (response) => { const payload = await response.json() as EventPayload; if (!response.ok) throw new Error(payload.error || "Event unavailable"); setEvent(payload.event); }).catch((reason: Error & { name?: string }) => { if (reason.name !== "AbortError") setError(reason.message); }); return () => controller.abort(); }, [slug]);
  const market = useMemo(() => event?.markets.find((item) => item.id === initialMarketId || item.slug === initialMarketId) ?? event?.markets.find((item) => item.active && !item.closed) ?? event?.markets[0] ?? null, [event, initialMarketId]); const outcome = market?.outcomes[market.primaryOutcomeIndex] ?? null;
  useEffect(() => { if (!market || !outcome) return; const controller = new AbortController(); Promise.allSettled([
    fetch(`/api/predictions/markets/${outcome.tokenId}/history?range=${range}`, { signal: controller.signal }).then((response) => response.json() as Promise<{ points?: PredictionHistoryPoint[]; origin?: string }>).then((payload) => { setHistory(payload.points ?? []); setHistoryOrigin(payload.origin ?? "Unavailable"); }),
    fetch(`/api/predictions/markets/${outcome.tokenId}/orderbook`, { signal: controller.signal }).then((response) => response.json() as Promise<{ book?: PredictionBook }>).then((payload) => setBook(payload.book ?? null)),
    fetch(`/api/predictions/markets/${market.id}/trades?limit=50`, { signal: controller.signal }).then((response) => response.json() as Promise<{ trades?: PredictionTrade[] }>).then((payload) => setTrades(payload.trades ?? [])),
    fetch(`/api/predictions/markets/${market.id}/stats`, { signal: controller.signal }).then((response) => response.json() as Promise<{ stats?: PredictionStats }>).then((payload) => setStats(payload.stats ?? null)),
  ]); return () => controller.abort(); }, [market, outcome, range]);
  useEffect(() => {
    if (!market || !outcome || !market.acceptingOrders) return; const stream = new EventSource(`/api/predictions/live?tokens=${outcome.tokenId}&markets=${market.id}`);
    let polling: ReturnType<typeof setInterval> | null = null; let fallback: ReturnType<typeof setTimeout> | null = null; let stopped = false; let pollCount = 0;
    const applyCoordinate = (next: number, observedAt: number) => { setLast(next); setHistory((current) => { const latest = current.at(-1); if (latest && observedAt - latest.timestamp < 5_000) return [...current.slice(0, -1), { timestamp: observedAt, probability: next }]; return [...current, { timestamp: observedAt, probability: next }].slice(-5_000); }); };
    const poll = () => { pollCount += 1; void fetch(`/api/predictions/books?tokens=${outcome.tokenId}&markets=${market.id}`).then((response) => response.json() as Promise<{ books?: PredictionBook[] }>).then((result) => { const nextBook = result.books?.[0]; if (!nextBook) return; setBook(nextBook); if (nextBook.mid !== null) applyCoordinate(nextBook.mid, nextBook.observedAt); }).catch(() => setStreamStatus("RECONNECTING")); if (pollCount % 3 === 0) void fetch(`/api/predictions/markets/${market.id}/trades?limit=50`).then((response) => response.json() as Promise<{ trades?: PredictionTrade[] }>).then((result) => setTrades(result.trades ?? [])).catch(() => undefined); };
    const startPolling = () => { if (polling || stopped) return; stream.close(); setStreamStatus("LIVE · POLLED"); poll(); polling = setInterval(poll, 3_000); };
    stream.addEventListener("patch", (eventMessage) => { const patch = JSON.parse((eventMessage as MessageEvent<string>).data) as PredictionLivePatch; if (patch.type === "status") setStreamStatus(patch.status); if (patch.type === "book" && patch.book.tokenId === outcome.tokenId) setBook(patch.book); if (patch.type === "trade" && patch.trade.tokenId === outcome.tokenId) { setTrades((current) => [patch.trade, ...current.filter((trade) => trade.identity !== patch.trade.identity)].slice(0, 80)); setLast(patch.trade.price); } if (patch.type === "quote" && patch.tokenId === outcome.tokenId) { if (fallback) { clearTimeout(fallback); fallback = null; } const next = patch.mid ?? patch.last; if (next !== null) applyCoordinate(next, patch.observedAt); } }); stream.onerror = startPolling; fallback = setTimeout(startPolling, 4_000); return () => { stopped = true; stream.close(); if (polling) clearInterval(polling); if (fallback) clearTimeout(fallback); };
  }, [market, outcome]);
  if (error) return <div className="prediction-state"><span>EVENT · UNAVAILABLE</span><p>No values were fabricated.</p><small>{error}</small></div>;
  if (!event || !market || !outcome) return <div className="prediction-state"><span>POLYMARKET · EVENT DETAIL</span><p>Loading event, markets, token mappings, book and history…</p></div>;
  const shownProbability = last ?? book?.mid ?? market.probability; const totalDepth = (book?.bidDepth ?? 0) + (book?.askDepth ?? 0);
  return <div className="prediction-detail-page"><PredictionNav active="dashboard" /><header className="prediction-detail-hero section-shell"><div><span className="eyebrow">{event.category} · {event.negativeRisk ? "NEGATIVE-RISK EVENT" : "STANDARD EVENT"}</span><h1>{event.title}</h1><p>{event.description}</p><div className="detail-actions"><a className="button button-primary" href={event.sourceUrl} target="_blank" rel="noreferrer">VERIFY AT POLYMARKET ↗</a><a className="button" href="/learn/foundations/prediction-market-probabilities">WHY A QUANT CARES →</a></div></div><aside className="prediction-live-coordinate"><span>PRIMARY OUTCOME · {outcome.label.toUpperCase()}</span><b>{probability(shownProbability)}</b><small>{streamStatus} · {market.acceptingOrders ? "BOOK OPEN" : "BOOK CLOSED"}</small><dl><dt>BID</dt><dd>{probability(book?.bestBid ?? market.bid)}</dd><dt>ASK</dt><dd>{probability(book?.bestAsk ?? market.ask)}</dd><dt>MID</dt><dd>{probability(book?.mid ?? market.mid)}</dd><dt>SPREAD</dt><dd>{book?.spread === null || book?.spread === undefined ? "—" : `${(book.spread * 100).toFixed(2)}pp`}</dd></dl></aside></header>
    <nav className="event-market-rail section-shell" aria-label="Markets in this event">{event.markets.map((item) => <a className={item.id === market.id ? "active" : ""} href={`/markets/predictions/${event.slug}?market=${item.id}`} key={item.id}><span>{item.question}</span><b>{probability(item.probability)}</b><small>{item.closed ? "CLOSED" : `$${compact(item.volume24h)} 24H`}</small></a>)}</nav>
    <section className="prediction-detail-kpis section-shell"><Metric label="VOLUME" value={`$${compact(stats?.volume ?? market.volume)}`} /><Metric label="24H VOLUME" value={`$${compact(stats?.volume24h ?? market.volume24h)}`} /><Metric label="LIQUIDITY" value={`$${compact(stats?.liquidity ?? market.liquidity)}`} /><Metric label="OPEN INTEREST" value={stats?.openInterest === null || stats?.openInterest === undefined ? "N/A" : `$${compact(stats.openInterest)}`} /><Metric label="TOP HOLDERS" value={stats?.holders === null || stats?.holders === undefined ? "N/A" : String(stats.holders)} /></section>
    <section className="prediction-detail-grid section-shell"><article className="prediction-chart-panel"><header><div><span className="eyebrow">PERSISTED PROBABILITY PATH</span><h2>{outcome.label} token history</h2></div><div className="range-tabs">{(["1h", "1d", "7d", "30d", "all"] as Range[]).map((item) => <button className={range === item ? "active" : ""} type="button" onClick={() => setRange(item)} key={item}>{item.toUpperCase()}</button>)}</div></header>{history.length > 1 ? <LineChart x={history.map((point) => point.timestamp)} series={[{ name: `${outcome.label} implied`, values: history.map((point) => point.probability * 100) }]} xLabel="Time (UTC)" yLabel="Implied probability" description="Persisted market-implied probability path for the selected outcome." xFormatter={formatTimestamp} yFormatter={(value) => `${value.toFixed(2)}%`} height={300} /> : <div className="empty-state">History is backfilling from the official CLOB API.</div>}<footer><span>ORIGIN · {historyOrigin.toUpperCase()}</span><span>LIVE UPDATES APPEND AFTER LOAD</span></footer></article><OrderBookPanel book={book} totalDepth={totalDepth} /></section>
    <section className="prediction-trade-section section-shell"><header><div><span className="eyebrow">PUBLIC TRADE TAPE</span><h2>Recent matched activity</h2></div><small>DATA API SNAPSHOT + LIVE CLOB TRADES</small></header><div className="prediction-trades"><div className="trade-head"><span>TIME</span><span>SIDE</span><span>PRICE</span><span>SIZE</span><span>NOTIONAL</span></div>{trades.length ? trades.map((trade) => <div className="trade-row" key={trade.identity}><span>{new Date(trade.timestamp).toLocaleTimeString(locale)}</span><b className={trade.side === "BUY" ? "positive" : "negative"}>{trade.side}</b><span>{probability(trade.price)}</span><span>{compact(trade.size)}</span><span>${compact(trade.price * trade.size)}</span></div>) : <p className="empty-state">No public trades returned for this market.</p>}</div></section>
    <section className="prediction-rules section-shell"><div><span>RESOLUTION & SEMANTICS</span><p>{market.description || event.description}</p><small>Resolution source: {event.resolutionSource || "See the official event rules."}</small></div><aside><b>{pick(locale, { en: "Observed, not forecast", es: "Observado, no pronosticado" })}</b><p>{pick(locale, { en: "Contract prices are market-implied coordinates shaped by book depth, fees, beliefs and settlement rules. They are neither objective probability nor certainty.", es: "Los precios son coordenadas implícitas condicionadas por profundidad, comisiones, creencias y reglas. No son probabilidad objetiva ni certeza." })}</p></aside></section>
  </div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <article><span>{label}</span><b>{value}</b></article>; }
function OrderBookPanel({ book, totalDepth }: { book: PredictionBook | null; totalDepth: number }) { const bids = book?.bids.slice(0, 10) ?? []; const asks = book?.asks.slice(0, 10) ?? []; const maxSize = Math.max(...bids.map((level) => level.size), ...asks.map((level) => level.size), 1); return <article className="orderbook-panel"><header><div><span className="eyebrow">LIVE L2 ORDER BOOK</span><h2>Depth and imbalance</h2></div><b>{book?.imbalance === null || book?.imbalance === undefined ? "—" : `${(book.imbalance * 100).toFixed(1)}%`}</b></header><div className="book-columns"><div><span>BIDS · {totalDepth ? `${((book?.bidDepth ?? 0) / totalDepth * 100).toFixed(0)}%` : "—"}</span>{bids.map((level) => <div className="book-level bid" key={level.price}><i style={{ width: `${level.size / maxSize * 100}%` }} /><b>{probability(level.price)}</b><small>{compact(level.size)}</small></div>)}</div><div><span>ASKS · {totalDepth ? `${((book?.askDepth ?? 0) / totalDepth * 100).toFixed(0)}%` : "—"}</span>{asks.map((level) => <div className="book-level ask" key={level.price}><i style={{ width: `${level.size / maxSize * 100}%` }} /><b>{probability(level.price)}</b><small>{compact(level.size)}</small></div>)}</div></div>{!book && <p className="empty-state">Order book unavailable or market closed.</p>}<footer><span>BID DEPTH · {compact(book?.bidDepth ?? 0)}</span><span>ASK DEPTH · {compact(book?.askDepth ?? 0)}</span></footer></article>; }
