"use client";
import { useEffect, useState } from "react";
import type { PredictionCoverage } from "@/src/polymarket/domain";
import { PredictionNav } from "./PredictionsDashboard";

type Payload = { coverage: PredictionCoverage; quotes: Record<string, unknown>[]; error?: string; receivedAt?: string };
const tables = [
  ["prediction_events", "Event metadata and resolution context"], ["prediction_markets", "Tradable condition-level markets"], ["prediction_outcomes", "Outcome ↔ CLOB token mappings"], ["prediction_quotes", "Incremental best bid/ask/mid/spread"], ["prediction_trades", "Deduplicated public trades"], ["prediction_probability_bars", "Backfilled probability observations"], ["prediction_orderbook_snapshots", "Sampled L2 depth, not every raw book"], ["prediction_stats", "Volume, liquidity and open-interest snapshots"], ["prediction_ingestion_checkpoints", "Resumable pipeline cursors and lag"],
] as const;

export function PredictionDataExplorer() {
  const [payload, setPayload] = useState<Payload | null>(null); const [error, setError] = useState(""); const [limit, setLimit] = useState(100);
  useEffect(() => { const controller = new AbortController(); fetch(`/api/predictions/explorer?limit=${limit}`, { signal: controller.signal }).then(async (response) => { const data = await response.json() as Payload; if (!response.ok) throw new Error(data.error || "Explorer unavailable"); setPayload(data); }).catch((reason: Error & { name?: string }) => { if (reason.name !== "AbortError") setError(reason.message); }); return () => controller.abort(); }, [limit]);
  const coverage = payload?.coverage;
  return <div className="prediction-explorer-page"><PredictionNav active="explorer" /><header className="page-hero compact-hero section-shell"><div><span className="eyebrow">NORMALIZED DATA EXPLORER · READ ONLY</span><h1>DATA,<br /><em>WITH MEMORY.</em></h1><p>Inspect accumulated events, tokens, probability observations, live quotes and ingestion health. SQL is never exposed to the browser.</p></div><aside className="market-status"><i /><strong>{coverage?.persistent ? "D1 CONNECTED" : "LIVE-ONLY FALLBACK"}</strong><span>{coverage?.latestDataAt ? `LATEST ${new Date(coverage.latestDataAt).toISOString()}` : "NO PERSISTED SAMPLE YET"}</span></aside></header>
    <section className="explorer-kpis section-shell"><Coverage label="EVENTS" value={coverage?.events} /><Coverage label="MARKETS" value={coverage?.markets} /><Coverage label="OUTCOMES" value={coverage?.outcomes} /><Coverage label="QUOTES" value={coverage?.quotes} /><Coverage label="TRADES" value={coverage?.trades} /><Coverage label="HISTORY" value={coverage?.bars} /></section>
    {error && <div className="prediction-state section-shell"><span>PERSISTENCE · UNAVAILABLE</span><p>The live dashboard remains available; durable inspection requires the D1 binding and migrations.</p><small>{error}</small></div>}
    <section className="explorer-layout section-shell"><article><header><div><span className="eyebrow">LATEST NORMALIZED QUOTES</span><h2>Best-book observations</h2></div><label><span>ROWS</span><select value={limit} onChange={(event) => setLimit(Number(event.target.value))}><option>50</option><option>100</option><option>250</option><option>500</option></select></label></header><div className="explorer-table"><div className="explorer-row explorer-head"><span>TIME</span><span>MARKET</span><span>BID</span><span>ASK</span><span>MID</span><span>SPREAD</span></div>{payload?.quotes.length ? payload.quotes.map((quote, index) => <div className="explorer-row" key={`${quote.tokenId}-${quote.observedAt}-${index}`}><span>{new Date(Number(quote.observedAt)).toISOString()}</span><span>{String(quote.question || quote.marketId || "—")}</span><span>{formatProbability(quote.bid)}</span><span>{formatProbability(quote.ask)}</span><span>{formatProbability(quote.mid)}</span><span>{formatProbability(quote.spread, true)}</span></div>) : <p className="empty-state">Open a live event for several seconds to begin collecting quote observations.</p>}</div></article><aside className="schema-panel"><span className="eyebrow">SCHEMA COVERAGE</span>{tables.map(([name, description]) => <div key={name}><code>{name}</code><small>{description}</small></div>)}<a className="source-button" href="/dev/data">OPEN PIPELINE HEALTH →</a></aside></section>
    <aside className="probability-note section-shell"><span>RETENTION POLICY</span><p>Metadata is retained. Trades and probability bars are deduplicated. L2 snapshots retain top ten levels at sampled provider updates; full raw books are intentionally not stored forever. Scale-up path: PostgreSQL + Timescale hypertables and continuous aggregates when volume or external workloads justify it.</p></aside>
  </div>;
}
function Coverage({ label, value }: { label: string; value?: number }) { return <article><span>{label}</span><b>{value === undefined ? "—" : value.toLocaleString()}</b></article>; }
function formatProbability(value: unknown, points = false) { const number = Number(value); return Number.isFinite(number) ? `${(number * 100).toFixed(2)}${points ? "pp" : "%"}` : "—"; }
