import { assetPath, contentCatalog } from "@/src/content/catalog";
import { instrumentMaster } from "@/src/market-data/instrumentMaster";
import { MarketDataRouter, licensingModeFromEnv } from "@/src/market-data/router";
import { formatMarketPrice, formatSessionMove } from "@/src/market-data/normalization";
import { discoverPredictionEvents } from "@/src/polymarket/client";
import { localizeEntry } from "@/src/content/localization";
import type { Locale } from "@/src/i18n";

export interface AssistantEvidence { tool: "market_data" | "prediction_data" | "learn" | "analytics" | "navigation"; answer: string; sources: { label: string; href: string; status: string }[]; }

const normalized = (value: string) => value.toLowerCase().replaceAll("/", "").replaceAll("€", "e").replaceAll(" ", "");

export async function resolveEvidence(question: string, resolveMarketData = false, locale: Locale = "en"): Promise<AssistantEvidence> {
  const term = question.toLowerCase();
  const es = locale === "es";
  const compactTerm = normalized(term); const instrument = instrumentMaster.find((item) => compactTerm.includes(normalized(item.symbol)) || compactTerm.includes(normalized(item.slug)));
  if (instrument) {
    if (!resolveMarketData) return { tool: "market_data", answer: es ? `${instrument.symbol} está disponible mediante el enrutador normalizado de datos de mercado. Abre su pasaporte de datos para consultar valor, proveedor, estado, timestamp de mercado y semántica as-of; el asistente no infiere ningún precio.` : `${instrument.symbol} is available through the normalized market-data router. Open its data passport for the current value, provider, status, market timestamp and as-of semantics; no price is inferred by the assistant.`, sources: [{ label: es ? `Pasaporte de datos de ${instrument.symbol}` : `${instrument.symbol} data passport`, href: `/markets/${instrument.slug}`, status: "NORMALIZED MARKET STATE" }] };
    const [quote] = await new MarketDataRouter().getQuotes({ instrumentIds: [instrument.id], mode: "LIVE_SNAPSHOT", provider: "AUTO", licensingMode: licensingModeFromEnv(process.env) });
    if (quote?.price !== null && quote?.price !== undefined) return { tool: "market_data", answer: es ? `${instrument.symbol} cotiza a ${formatMarketPrice(quote, instrument)}; variación mostrada de la sesión ${formatSessionMove(quote, instrument)}. Estado ${quote.status}, fuente ${quote.source}, a fecha ${quote.asOf}. Es un valor observado o una referencia/demo etiquetada explícitamente; no es una cotización ejecutable ni una previsión del modelo.` : `${instrument.symbol} is ${formatMarketPrice(quote, instrument)}; displayed session change ${formatSessionMove(quote, instrument)}. Status ${quote.status}, source ${quote.source}, as of ${quote.asOf}. This is an observed or explicitly labelled reference/demo value, not a tradable quote or model forecast.`, sources: [{ label: es ? `Pasaporte de datos de ${instrument.symbol}` : `${instrument.symbol} data passport`, href: `/markets/${instrument.slug}`, status: `${quote.status} · ${quote.source}` }, ...(quote.sourceUrl ? [{ label: es ? "Verificar input del proveedor" : "Verify provider input", href: quote.sourceUrl, status: "EXTERNAL SOURCE" }] : [])] };
    return { tool: "market_data", answer: es ? `${instrument.symbol} no está disponible actualmente mediante un proveedor configurado cuya licencia permita mostrarlo. No se ha fabricado ningún valor.` : `${instrument.symbol} is currently unavailable from a legally displayable configured provider. No value was fabricated.`, sources: [{ label: es ? `Pasaporte de datos de ${instrument.symbol}` : `${instrument.symbol} data passport`, href: `/markets/${instrument.slug}`, status: "UNAVAILABLE" }] };
  }
  const analyticsTopic = /(option|opci[oó]n|greek|griega|delta|gamma|vega|theta|rho|implied vol|volatilidad impl[ií]cita|black.scholes|garman|black.76)/.test(term);
  const analyticsAction = /(use|run|calculate|price|usar|ejecutar|calcular|valorar)/.test(term);
  const analyticsAnswer = es ? "Una respuesta numérica requiere modelo, spot o forward, strike, vencimiento, tipos, volatilidad, tipo de opción y nocional explícitos. Abre la herramienta analítica determinista; sus resultados, supuestos y linaje de datos prevalecen sobre cualquier explicación del modelo de lenguaje." : "A numerical answer requires explicit model, spot or forward, strike, maturity, rates, volatility, option type and notional. Open the deterministic analytics tool; its output, assumptions and data lineage take authority over any language-model explanation.";
  if (analyticsAction && analyticsTopic) return { tool: "analytics", answer: analyticsAnswer, sources: [{ label: es ? "Analítica de opciones europeas" : "European option analytics", href: "/lab?lab=vanilla", status: "LOCAL QUANT ENGINE" }] };
  if (/prediction|predicci[oó]n|probability|probabilidad|polymarket|event odds/.test(term) && resolveMarketData) {
    try {
      const discovery = await discoverPredictionEvents({ limit: 100, order: "volume24hr" }); const stop = new Set(["what", "when", "where", "which", "will", "would", "could", "should", "probability", "prediction", "market", "polymarket", "current", "price", "odds", "about", "from", "with", "that", "this", "the", "and", "for"]); const words = term.replace(/[^a-z0-9 ]/g, " ").split(/\s+/).filter((word) => word.length > 2 && !stop.has(word));
      const ranked = discovery.markets.map((market) => ({ market, score: words.reduce((score, word) => score + (`${market.question} ${market.category}`.toLowerCase().includes(word) ? 1 : 0), 0) })).sort((left, right) => right.score - left.score || right.market.volume24h - left.market.volume24h); const selected = ranked[0];
      if (selected && (selected.score > 0 || words.length === 0)) { const market = selected.market; const event = discovery.events.find((item) => item.id === market.eventId); const probability = market.probability === null ? (es ? "no disponible" : "unavailable") : `${(market.probability * 100).toFixed(1)}%`; return { tool: "prediction_data", answer: es ? `${market.question}: el token principal cotiza actualmente a ${probability}. Mejor bid ${market.bid === null ? "n/d" : `${(market.bid * 100).toFixed(1)}%`}, mejor ask ${market.ask === null ? "n/d" : `${(market.ask * 100).toFixed(1)}%`}, volumen de 24 horas $${market.volume24h.toLocaleString("es", { maximumFractionDigits: 0 })}, liquidez $${market.liquidity.toLocaleString("es", { maximumFractionDigits: 0 })}. Es una coordenada implícita observada en mercado, no una probabilidad objetiva ni una previsión.` : `${market.question}: the primary outcome token is currently ${probability}. Best bid ${market.bid === null ? "n/a" : `${(market.bid * 100).toFixed(1)}%`}, best ask ${market.ask === null ? "n/a" : `${(market.ask * 100).toFixed(1)}%`}, 24-hour volume $${market.volume24h.toLocaleString("en", { maximumFractionDigits: 0 })}, liquidity $${market.liquidity.toLocaleString("en", { maximumFractionDigits: 0 })}. This is an observed market-implied coordinate, not objective probability or a forecast.`, sources: [{ label: es ? "Detalle normalizado del evento" : "Normalized event detail", href: `/markets/predictions/${event?.slug ?? market.eventId}?market=${market.id}`, status: "GAMMA + CLOB PUBLIC READ ONLY" }, { label: es ? "Verificar en Polymarket" : "Verify at Polymarket", href: market.sourceUrl, status: "EXTERNAL SOURCE" }] }; }
    } catch { /* Continue to the non-numerical, safe navigation response. */ }
  }
  const concept = contentCatalog.find((entry) => term.includes(entry.title.toLowerCase()) || term.includes(localizeEntry(entry, "es").title.toLowerCase())) ?? contentCatalog.find((entry) => entry.tags.some((tag) => term.includes(tag.toLowerCase())));
  if (concept) { const localized = localizeEntry(concept, locale); return { tool: "learn", answer: `${localized.title}: ${localized.description} ${localized.intuition} ${es ? "Uso en mercado" : "Market use"}: ${localized.marketUse}`, sources: [{ label: localized.title, href: `/learn/${assetPath(concept.assetClass)}/${concept.slug}`, status: `${es ? "REVISADO" : "REVIEWED"} ${concept.lastReviewed}` }] }; }
  if (analyticsTopic) return { tool: "analytics", answer: analyticsAnswer, sources: [{ label: es ? "Analítica de opciones europeas" : "European option analytics", href: "/lab?lab=vanilla", status: "LOCAL QUANT ENGINE" }] };
  if (/prediction|predicci[oó]n|probability|probabilidad|polymarket/.test(term)) return { tool: "navigation", answer: es ? "Las probabilidades de los mercados de predicción se cargan mediante nuestra capa normalizada y pública de solo lectura sobre las API Gamma, CLOB y Data. Son precios observados de contratos, no previsiones calibradas del mundo real. Abre el panel para consultar libro, histórico y timestamps de las fuentes." : "Prediction-market probabilities are loaded through our normalized public read-only Gamma, CLOB and Data API layer. They are observed contract prices, not calibrated real-world forecasts. Open the dashboard for live book state, history and source timestamps.", sources: [{ label: es ? "Mercados de predicción" : "Prediction markets", href: "/markets/predictions", status: "PUBLIC READ ONLY" }, { label: es ? "Explorador de datos de predicción" : "Prediction Data Explorer", href: "/intelligence/data", status: "NORMALIZED PERSISTENCE" }] };
  return { tool: "navigation", answer: es ? "Puedo fundamentar las respuestas en el corpus de Learn, los datos de mercado mostrados, los mercados de predicción o la analítica determinista. Indica un concepto o instrumento, o proporciona todos los inputs de valoración." : "I can ground answers in the Learn corpus, displayed market data, prediction markets or deterministic analytics. Name a concept or instrument, or provide complete pricing inputs.", sources: [{ label: es ? "Catálogo unificado de Learn" : "Unified Learn catalog", href: "/learn", status: "LOCAL REVIEWED CORPUS" }] };
}
