import type { AssetClass, ContentEntry, ContentType, Difficulty } from "./types";

type Seed = {
  assetClass: AssetClass;
  title: string;
  description: string;
  intuition: string;
  mathematics: string;
  marketUse: string;
  relatedTopics?: string[];
  difficulty?: Difficulty;
  type?: ContentType;
};

const slugify = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

function createEntry(seed: Seed): ContentEntry {
  const slug = slugify(seed.title);
  return {
    ...seed,
    slug,
    category: seed.assetClass === "Foundations" ? "Foundations" : seed.assetClass,
    difficulty: seed.difficulty ?? "foundation",
    type: seed.type ?? "concept",
    prerequisites: seed.assetClass === "Foundations" ? [] : ["Risk-Neutral Pricing"],
    relatedTopics: seed.relatedTopics ?? [],
    labs: seed.title.includes("Curve") || seed.title.includes("Rate") || seed.title.includes("Discount") ? ["yield-curve"] : seed.assetClass === "EQ" || seed.assetClass === "FX" ? ["black-scholes", "greeks"] : [],
    tags: [seed.assetClass, seed.type ?? "concept", seed.difficulty ?? "foundation"],
    authors: ["TheQuantBateman Research"],
    lastReviewed: "2026-08-10",
    assumptions: [
      "Educational conventions are stated explicitly and may simplify market quotation or settlement details.",
      "Rates are continuously compounded unless the section says otherwise.",
      "Inputs are deterministic in the base model.",
    ],
    deskView: `Start with the quote convention, then ask which ${seed.assetClass} risk survives the hedge. A number without its convention is merely well-dressed ambiguity.`,
  };
}

const seeds: Seed[] = [
  { assetClass: "Foundations", title: "Random Variables", description: "Map uncertain outcomes to measurable numerical values.", intuition: "A random variable is a rule that assigns a number to each possible market outcome. The randomness is in the outcome, not in the rule.", mathematics: "X: \\Omega \\to \\mathbb{R}, \\quad F_X(x)=\\mathbb{P}[X\\le x]", marketUse: "P&L distributions, payoff definitions, risk measures and simulation all start here.", relatedTopics: ["Brownian Motion", "Risk-Neutral Pricing"] },
  { assetClass: "Foundations", title: "Brownian Motion", description: "The continuous-time noise behind classical diffusion models.", intuition: "Brownian motion accumulates independent, normally distributed shocks. Paths are continuous but nowhere differentiable.", mathematics: "W_0=0, \\quad W_t-W_s \\sim \\mathcal{N}(0,t-s)", marketUse: "It drives Black-Scholes diffusions and remains a baseline building block for stochastic models.", relatedTopics: ["Random Variables", "Black-Scholes"], difficulty: "practitioner" },
  { assetClass: "Foundations", title: "Risk-Neutral Pricing", description: "Value discounted payoffs under a measure that removes risk premia.", intuition: "Change the probability lens so tradable assets grow at the funding rate after carry. Then discount the expected payoff.", mathematics: "V_t=B_t\\,\\mathbb{E}^{\\mathbb{Q}}[B_T^{-1}X_T\\mid\\mathcal{F}_t]", marketUse: "This is the common pricing spine of derivatives desks, not a claim that investors are actually risk neutral.", relatedTopics: ["Black-Scholes", "Discount Factors"], difficulty: "practitioner" },

  { assetClass: "EQ", title: "Equity Forward", description: "Lock a future equity purchase price after funding and dividends.", intuition: "Carry spot forward: financing raises the forward; dividends lower it.", mathematics: "F_{0,T}=S_0e^{(r-q)T}", marketUse: "Forward valuation, futures basis, option parity and dividend-implied analysis.", relatedTopics: ["Black-Scholes", "Implied Volatility"], type: "instrument" },
  { assetClass: "EQ", title: "Black-Scholes", description: "Closed-form European option pricing under lognormal diffusion.", intuition: "A continuously rebalanced hedge removes the diffusion shock, leaving a price pinned by no-arbitrage.", mathematics: "C=S_0e^{-qT}N(d_1)-Ke^{-rT}N(d_2)", marketUse: "Still the quoting and risk lingua franca even where richer models price exotics.", relatedTopics: ["Greeks", "Implied Volatility", "Risk-Neutral Pricing"], difficulty: "practitioner", type: "model" },
  { assetClass: "EQ", title: "Greeks", description: "Local sensitivities that translate model parameters into hedge language.", intuition: "Greeks are slopes and curvatures: how the option changes for a small controlled move.", mathematics: "\\Delta=\\partial_S V, \\quad \\Gamma=\\partial^2_{SS}V, \\quad \\nu=\\partial_\\sigma V", marketUse: "Hedge sizing, scenario interpretation and P&L attribution.", relatedTopics: ["Black-Scholes", "Implied Volatility"], difficulty: "practitioner" },
  { assetClass: "EQ", title: "Implied Volatility", description: "The volatility input that makes a model reproduce a market option price.", intuition: "Implied volatility is a quote coordinate, not a forecast delivered by the market.", mathematics: "\\sigma_{imp}: V_{BS}(\\sigma_{imp})=V_{mkt}", marketUse: "Normalises option prices across strikes, maturities and underlyings.", relatedTopics: ["Black-Scholes", "Volatility Smile"], difficulty: "practitioner" },
  { assetClass: "EQ", title: "Volatility Smile", description: "Strike-dependent implied volatility at a single expiry.", intuition: "Markets charge different volatility for different regions of the terminal distribution.", mathematics: "K \\mapsto \\sigma_{imp}(K,T)", marketUse: "Expresses skew, tail pricing and supply-demand effects.", relatedTopics: ["Implied Volatility", "Volatility Surface"], difficulty: "practitioner" },
  { assetClass: "EQ", title: "Volatility Surface", description: "Implied volatility across strike and maturity.", intuition: "Stack smiles through time and you obtain the market's option-price coordinate system.", mathematics: "(K,T) \\mapsto \\sigma_{imp}(K,T)", marketUse: "Interpolation, marking, scenario risk and exotic calibration inputs.", relatedTopics: ["Volatility Smile", "Local Volatility"], difficulty: "front-office" },

  { assetClass: "FX", title: "FX Spot", description: "The exchange rate for near-immediate delivery between two currencies.", intuition: "An FX rate is always one currency priced in another; the direction matters before any arithmetic begins.", mathematics: "S_t = \\text{units of domestic currency per unit of foreign currency}", marketUse: "Anchor for forwards, swaps, options and cross-currency exposures.", relatedTopics: ["FX Forward", "Garman-Kohlhagen"], type: "instrument" },
  { assetClass: "FX", title: "FX Forward", description: "A future exchange rate implied by two funding curves.", intuition: "Forward points compensate for the interest-rate differential, not an expected spot move.", mathematics: "F_{0,T}=S_0e^{(r_d-r_f)T}", marketUse: "Hedging, carry, basis analysis and option forwards.", relatedTopics: ["FX Spot", "FX Swap"], type: "instrument" },
  { assetClass: "FX", title: "FX Swap", description: "Exchange currencies now and reverse the exchange later.", intuition: "An FX swap moves funding across currencies while keeping most spot risk neutralised.", mathematics: "\\text{swap points}=F_{0,T}-S_0", marketUse: "Treasury funding, liquidity management and forward-curve construction.", relatedTopics: ["FX Forward", "FX Spot"], type: "instrument", difficulty: "practitioner" },
  { assetClass: "FX", title: "Garman-Kohlhagen", description: "Black-Scholes adapted to domestic and foreign interest rates.", intuition: "Treat the foreign currency like a dividend-paying asset whose yield is the foreign rate.", mathematics: "C=S_0e^{-r_fT}N(d_1)-Ke^{-r_dT}N(d_2)", marketUse: "Baseline European FX option valuation and Greeks.", relatedTopics: ["FX Delta Conventions", "FX Volatility Smile"], type: "model", difficulty: "practitioner" },
  { assetClass: "FX", title: "FX Delta Conventions", description: "Premium-adjusted, forward and spot delta quotation choices.", intuition: "The same option can carry different delta numbers under valid market conventions.", mathematics: "\\Delta_{spot}=e^{-r_fT}N(d_1), \\quad \\Delta_{fwd}=N(d_1)", marketUse: "Smile construction and strike inversion require the exact pair-specific convention.", relatedTopics: ["Garman-Kohlhagen", "Risk Reversal"], difficulty: "front-office" },
  { assetClass: "FX", title: "Risk Reversal", description: "Call-minus-put volatility at matched absolute delta.", intuition: "Risk reversal measures directional asymmetry in the smile.", mathematics: "RR_{\\Delta}=\\sigma_{call,\\Delta}-\\sigma_{put,\\Delta}", marketUse: "Quotes skew and packages directional convexity exposure.", relatedTopics: ["Butterfly", "FX Volatility Smile"], difficulty: "front-office", type: "instrument" },
  { assetClass: "FX", title: "Butterfly", description: "A convexity quote combining wing and ATM volatilities.", intuition: "Butterfly asks how expensive both wings are relative to the centre.", mathematics: "BF_{\\Delta}=\\tfrac12(\\sigma_{call,\\Delta}+\\sigma_{put,\\Delta})-\\sigma_{ATM}", marketUse: "Builds smile curvature alongside ATM and risk reversal quotes.", relatedTopics: ["Risk Reversal", "FX Volatility Smile"], difficulty: "front-office", type: "instrument" },
  { assetClass: "FX", title: "FX Volatility Smile", description: "Construct an FX smile from ATM, risk reversal and butterfly quotes.", intuition: "FX desks quote the centre, asymmetry and wing richness rather than every strike directly.", mathematics: "\\{ATM,RR_{25},BF_{25}\\} \\to \\sigma(K)", marketUse: "Vanilla marking, strike construction and exotic calibration.", relatedTopics: ["Risk Reversal", "Butterfly", "FX Delta Conventions"], difficulty: "front-office" },

  { assetClass: "IR", title: "Discount Factors", description: "Present value of one unit of currency paid at a future date.", intuition: "A discount factor is the price today of a future unit under the relevant collateral and currency rules.", mathematics: "P(0,T)=e^{-z(0,T)T}", marketUse: "Every cashflow PV and curve construction step depends on them.", relatedTopics: ["Zero Rates", "Yield Curves"] },
  { assetClass: "IR", title: "Zero Rates", description: "Single-period rates implied by discount factors.", intuition: "A zero rate compresses the discount to one maturity into an annualised number.", mathematics: "z(0,T)=-\\frac{\\ln P(0,T)}{T}", marketUse: "Curve display, scenario construction and model inputs.", relatedTopics: ["Discount Factors", "Forward Rates"] },
  { assetClass: "IR", title: "Forward Rates", description: "Rates implied today for borrowing over a future interval.", intuition: "A forward is the break-even rate between discounting directly and rolling through an intermediate date.", mathematics: "f(T_1,T_2)=\\frac{\\ln P(0,T_1)-\\ln P(0,T_2)}{T_2-T_1}", marketUse: "FRA valuation, swap cashflows and monetary-policy expectations under a chosen curve.", relatedTopics: ["Zero Rates", "FRAs"] },
  { assetClass: "IR", title: "Yield Curves", description: "Term structures linking maturity to discounting or yield.", intuition: "A curve is not one rate stretched through time; every tenor is a different market constraint.", mathematics: "T \\mapsto P(0,T), z(0,T), f(0,T)", marketUse: "Pricing, carry, rolldown, DV01 and scenario risk.", relatedTopics: ["Curve Bootstrapping", "Discount Factors"], difficulty: "practitioner" },
  { assetClass: "IR", title: "OIS", description: "Fixed-versus-compounded overnight indexed swaps.", intuition: "OIS exchanges a fixed rate for realised compounded overnight funding.", mathematics: "PV_{fixed}=PV_{compounded\\ overnight}", marketUse: "Core collateral discounting and overnight-rate exposure.", relatedTopics: ["Interest Rate Swaps", "Curve Bootstrapping"], type: "instrument", difficulty: "practitioner" },
  { assetClass: "IR", title: "FRAs", description: "Contracts fixing a future simple interest rate.", intuition: "An FRA settles the difference between a contracted rate and the fixing for a future accrual period.", mathematics: "PV=N\\delta P(0,T_2)(F-K)", marketUse: "Short-end rate hedging and forward-curve instruments.", relatedTopics: ["Forward Rates", "Interest Rate Swaps"], type: "instrument", difficulty: "practitioner" },
  { assetClass: "IR", title: "Interest Rate Swaps", description: "Exchange fixed coupons for floating-rate cashflows.", intuition: "The par swap rate makes the fixed leg equal the floating leg at inception.", mathematics: "K_{par}=\\frac{P(0,T_0)-P(0,T_n)}{\\sum_i \\delta_iP(0,T_i)}", marketUse: "Benchmark rate exposure, curve calibration and asset-liability hedging.", relatedTopics: ["OIS", "Curve Bootstrapping"], type: "instrument", difficulty: "practitioner" },
  { assetClass: "IR", title: "Curve Bootstrapping", description: "Solve discount factors sequentially from market instruments.", intuition: "Each liquid instrument pins another part of the curve once earlier cashflows are already known.", mathematics: "\\text{quotes} \\to \\{P(0,T_i)\\}_{i=1}^n", marketUse: "Produces internally consistent pricing curves from deposits, futures, OIS and swaps.", relatedTopics: ["Yield Curves", "Interest Rate Swaps"], type: "method", difficulty: "front-office" },

  { assetClass: "COMM", title: "Spot vs Futures", description: "Separate immediate physical value from exchange-traded future delivery.", intuition: "Storage, funding, convenience and delivery constraints connect spot and futures.", mathematics: "F_{0,T}=S_0e^{(r+u-y)T}", marketUse: "Basis analysis, hedging and curve interpretation.", relatedTopics: ["Forward Curves", "Convenience Yield"], type: "instrument" },
  { assetClass: "COMM", title: "Forward Curves", description: "Commodity delivery prices across maturities.", intuition: "Each point reflects inventory, seasonality, logistics and financing—not merely a price forecast.", mathematics: "T \\mapsto F(0,T)", marketUse: "Hedging programmes, storage economics and spread risk.", relatedTopics: ["Contango", "Backwardation"], difficulty: "practitioner" },
  { assetClass: "COMM", title: "Contango", description: "A forward curve whose later deliveries trade above nearby prices.", intuition: "Carry costs or abundant inventory can make deferred delivery more expensive.", mathematics: "F(0,T_2)>F(0,T_1), \\quad T_2>T_1", marketUse: "Roll yield, storage signals and calendar-spread positioning.", relatedTopics: ["Backwardation", "Convenience Yield"] },
  { assetClass: "COMM", title: "Backwardation", description: "A forward curve whose later deliveries trade below nearby prices.", intuition: "Scarcity and immediate utility can make prompt barrels or inventory unusually valuable.", mathematics: "F(0,T_2)<F(0,T_1), \\quad T_2>T_1", marketUse: "Inventory stress, positive roll and prompt-spread risk.", relatedTopics: ["Contango", "Convenience Yield"] },
  { assetClass: "COMM", title: "Convenience Yield", description: "The non-cash benefit of holding physical inventory.", intuition: "A physical unit can keep a refinery running or meet an unexpected order; that operational value behaves like a yield.", mathematics: "y=r+u-\\frac{1}{T}\\ln(F_{0,T}/S_0)", marketUse: "Explains basis behaviour and embeds scarcity in carry models.", relatedTopics: ["Spot vs Futures", "Forward Curves"], difficulty: "practitioner" },
  { assetClass: "COMM", title: "Black-76", description: "Option pricing on forwards under lognormal forward dynamics.", intuition: "Price the option on the forward and discount the expected payoff back to today.", mathematics: "C=e^{-rT}[FN(d_1)-KN(d_2)]", marketUse: "Common baseline for commodity, caplet and swaption quotation contexts.", relatedTopics: ["Asian Options", "Forward Curves"], type: "model", difficulty: "practitioner" },
  { assetClass: "COMM", title: "Asian Options", description: "Options whose payoff depends on an average price.", intuition: "Averaging dampens the impact of one extreme fixing and better matches gradual physical exposure.", mathematics: "\\max(\\frac1n\\sum_i S_{t_i}-K,0)", marketUse: "Commodity procurement, production and revenue hedging.", relatedTopics: ["Black-76", "Forward Curves"], type: "instrument", difficulty: "front-office" },

  { assetClass: "Frontier", title: "Rough Volatility", description: "Very low regularity volatility models aligned with observed short-scale behaviour.", intuition: "Volatility appears rougher than classical diffusions suggest, especially at short horizons.", mathematics: "H<\\tfrac12 \\text{ in fractional-volatility drivers}", marketUse: "Active research with growing calibration relevance; implementation and hedging remain specialised.", difficulty: "research", type: "research", relatedTopics: ["Neural SDEs", "Bayesian Calibration"] },
  { assetClass: "Frontier", title: "AAD", description: "Adjoint algorithmic differentiation for many sensitivities at near-constant reverse cost.", intuition: "Record the pricing computation, then propagate sensitivities backwards through it.", mathematics: "\\bar{x}_i=\\partial V/\\partial x_i", marketUse: "Industry-standard technique for large-scale Greeks where the implementation supports it.", difficulty: "front-office", type: "method", relatedTopics: ["Differentiable Pricing", "GPU Monte Carlo"] },
  { assetClass: "Frontier", title: "Differentiable Pricing", description: "Pricing systems designed for gradients across models and parameters.", intuition: "Treat calibration and risk as first-class derivatives of the pricing program.", mathematics: "\\nabla_\\theta V(\\theta)", marketUse: "Emerging infrastructure pattern spanning AAD, automatic differentiation and ML frameworks.", difficulty: "research", type: "research", relatedTopics: ["AAD", "Machine Learning Surrogates"] },
  { assetClass: "Frontier", title: "Machine Learning Surrogates", description: "Fast learned approximations to expensive pricing maps.", intuition: "Pay a training cost once, then approximate repeated model evaluations very quickly inside a controlled domain.", mathematics: "\\hat{V}_\\phi(x) \\approx V_{model}(x)", marketUse: "Active deployment area, but error control and extrapolation governance are essential.", difficulty: "research", type: "research", relatedTopics: ["Deep Hedging", "Differentiable Pricing"] },
  { assetClass: "Frontier", title: "Deep Hedging", description: "Learn hedging policies under frictions and non-quadratic objectives.", intuition: "Optimise the trading policy directly when transaction costs and constraints break textbook replication.", mathematics: "\\min_\\pi \\; \\rho(\\text{hedging P&L}_\\pi)", marketUse: "Active research and selective experimentation, not a universal replacement for desk risk systems.", difficulty: "research", type: "research", relatedTopics: ["Machine Learning Surrogates", "Neural SDEs"] },
  { assetClass: "Frontier", title: "Neural SDEs", description: "Stochastic differential equations with learned functional components.", intuition: "Keep continuous-time stochastic structure while learning flexible drift or diffusion maps from data.", mathematics: "dX_t=\\mu_\\theta(X_t,t)dt+\\sigma_\\theta(X_t,t)dW_t", marketUse: "Research-stage modelling with challenges in identifiability, stability and governance.", difficulty: "research", type: "research", relatedTopics: ["Rough Volatility", "Bayesian Calibration"] },
  { assetClass: "Frontier", title: "Bayesian Calibration", description: "Infer parameter distributions rather than one best-fit point.", intuition: "Calibration uncertainty is information; retain it instead of hiding it behind one optimiser output.", mathematics: "p(\\theta\\mid y)\\propto p(y\\mid\\theta)p(\\theta)", marketUse: "Research and specialist risk analysis, especially where parameter uncertainty matters.", difficulty: "research", type: "research", relatedTopics: ["Rough Volatility", "Machine Learning Surrogates"] },
  { assetClass: "Frontier", title: "GPU Monte Carlo", description: "Parallel simulation and payoff evaluation on graphics processors.", intuition: "Independent paths are naturally parallel, provided memory movement and branching are controlled.", mathematics: "V\\approx e^{-rT}N^{-1}\\sum_{i=1}^N g(X_T^{(i)})", marketUse: "Industry-standard acceleration in suitable large simulation workloads.", difficulty: "front-office", type: "method", relatedTopics: ["AAD", "Machine Learning Surrogates"] },
];

const expandedTopics: Record<Exclude<AssetClass, "Frontier">, string[]> = {
  Foundations: ["Conditional Expectation", "Martingales", "Change of Measure", "Itô Calculus", "Monte Carlo", "Variance Reduction", "Finite Differences", "PDE Methods", "Calibration Basics", "Interpolation Basics", "Numerical Stability"],
  EQ: ["Call-Put Parity", "Dividend Carry", "Historical Volatility", "Realized Volatility", "Term Structure", "Local Volatility", "Stochastic Volatility", "Heston", "SABR", "Gamma Scalping", "Variance Swaps", "Barrier Options", "Digital Options", "American Options", "Early Exercise", "Volatility Arbitrage"],
  FX: ["Forward Points", "ATM Conventions", "Premium-Adjusted Delta", "Smile Construction", "FX Digitals", "FX Barriers", "Dual-Currency Notes", "Quanto Effects", "Triangular Arbitrage", "Cross-Currency Basis"],
  IR: ["Day Count Conventions", "Compounding Conventions", "Multi-Curve Framework", "DV01", "Key-Rate Duration", "Carry and Rolldown", "Caps", "Floors", "Swaptions", "Short-Rate Models", "Hull-White", "LMM", "Convexity Adjustments", "Negative Rates"],
  COMM: ["Storage Costs", "Seasonality", "Roll Yield", "Calendar Spreads", "Commodity Swaps", "Commodity Options", "Mean Reversion", "Spread Options", "Swing Options", "Weather Derivatives", "Crack Spreads", "Spark Spreads", "Real Options"],
};

const topicDescriptions: Record<string, string> = {
  "Conditional Expectation": "Update expected values using the information currently available.", Martingales: "Processes whose conditional future value equals their current value.", "Change of Measure": "Reweight probabilities to move between pricing numeraires.", "Itô Calculus": "Differential calculus for stochastic processes with quadratic variation.", "Monte Carlo": "Estimate prices and risk by simulating many model paths.", "Variance Reduction": "Improve simulation precision without merely adding paths.", "Finite Differences": "Approximate derivatives and solve pricing PDEs on a grid.", "PDE Methods": "Translate no-arbitrage dynamics into boundary-value problems.", "Calibration Basics": "Choose parameters that reconcile a model with observed instruments.", "Interpolation Basics": "Estimate values between liquid market pillars without inventing arbitrage.", "Numerical Stability": "Keep computed outputs reliable under finite precision and difficult inputs.",
  "Call-Put Parity": "Connect European calls, puts, forwards and discounting by no-arbitrage.", "Dividend Carry": "Separate funding and distributions in equity forward value.", "Historical Volatility": "Estimate dispersion from a time series of past returns.", "Realized Volatility": "Measure variance accumulated over an observed period.", "Term Structure": "Track implied volatility across option maturities.", "Local Volatility": "Infer state-dependent instantaneous variance from a vanilla surface.", "Stochastic Volatility": "Model volatility itself as a random process.", Heston: "Model variance as a mean-reverting square-root diffusion.", SABR: "Model forward and volatility jointly for smile dynamics.", "Gamma Scalping": "Monetise convexity through repeated delta rebalancing.", "Variance Swaps": "Trade future realised variance against a fixed strike.", "Barrier Options": "Activate or extinguish payoff when an underlying crosses a level.", "Digital Options": "Pay a fixed amount when a terminal condition is met.", "American Options": "Allow exercise before expiry and introduce an optimal stopping problem.", "Early Exercise": "Compare continuation value with immediate exercise value.", "Volatility Arbitrage": "Express relative-value views across implied and realised volatility.",
  "Forward Points": "Quote the forward-minus-spot adjustment implied by two currencies.", "ATM Conventions": "Define where at-the-money sits under pair-specific FX rules.", "Premium-Adjusted Delta": "Account for option premium in the hedge-ratio convention.", "Smile Construction": "Turn market quote coordinates into a strike-volatility curve.", "FX Digitals": "Price fixed cashflows conditional on an exchange-rate event.", "FX Barriers": "Add path-dependent trigger levels to FX option payoffs.", "Dual-Currency Notes": "Combine fixed-income cashflows with embedded FX optionality.", "Quanto Effects": "Value an asset payoff translated at a fixed exchange rate.", "Triangular Arbitrage": "Enforce consistency across three quoted currency pairs.", "Cross-Currency Basis": "Measure funding dislocations not explained by covered interest parity.",
  "Day Count Conventions": "Convert calendar dates into contractual accrual fractions.", "Compounding Conventions": "Translate rates consistently across simple, periodic and continuous forms.", "Multi-Curve Framework": "Separate discounting from tenor-specific projection curves.", DV01: "Measure value change for a one-basis-point rate shift.", "Key-Rate Duration": "Allocate curve sensitivity to selected maturity nodes.", "Carry and Rolldown": "Decompose expected horizon P&L with an unchanged curve.", Caps: "Limit floating-rate payments through a strip of caplets.", Floors: "Protect minimum floating-rate receipts through floorlets.", Swaptions: "Grant the right to enter an interest-rate swap.", "Short-Rate Models": "Model the instantaneous funding rate to generate a term structure.", "Hull-White": "Use a mean-reverting Gaussian short rate fitted to today’s curve.", LMM: "Model a family of market forward rates under linked measures.", "Convexity Adjustments": "Correct linear forward intuition when payoff and discounting are nonlinear.", "Negative Rates": "Handle rate distributions and quotation when strikes can cross zero.",
  "Storage Costs": "Embed physical warehousing, insurance and financing in commodity carry.", Seasonality: "Model recurring calendar patterns in supply, demand and forward prices.", "Roll Yield": "Measure the return from moving exposure along a forward curve.", "Calendar Spreads": "Trade relative value between delivery months.", "Commodity Swaps": "Exchange floating commodity prices for fixed contractual levels.", "Commodity Options": "Attach optionality to forwards, futures or physical indices.", "Mean Reversion": "Model commodity prices returning toward an equilibrium level.", "Spread Options": "Option the difference between related prices.", "Swing Options": "Optimise repeated exercise volumes under operational constraints.", "Weather Derivatives": "Link payoffs to temperature or other weather indices.", "Crack Spreads": "Track refinery margin between crude and products.", "Spark Spreads": "Track power-generation margin between electricity and fuel.", "Real Options": "Value operational flexibility using option-pricing logic.",
};

const expandedSeeds: Seed[] = Object.entries(expandedTopics).flatMap(([assetClass, titles]) => titles.map((title) => ({
  assetClass: assetClass as Exclude<AssetClass, "Frontier">,
  title,
  description: topicDescriptions[title],
  intuition: `${title} becomes useful once its observable quote, state variables and governing convention are kept separate. Build the mental model before selecting the numerical method.`,
  mathematics: "\\operatorname{Value}=\\mathcal{M}(\\text{state},\\text{parameters},\\text{conventions})",
  marketUse: `${title} appears in pricing, scenario analysis, risk aggregation or hedge design. Production use requires explicit units, calendars, interpolation and data lineage.`,
  difficulty: title.includes("Basics") || ["Call-Put Parity", "Historical Volatility", "Forward Points", "Day Count Conventions", "Storage Costs"].includes(title) ? "foundation" : title.includes("Heston") || title.includes("SABR") || title.includes("LMM") || title.includes("Swing") ? "front-office" : "practitioner",
  type: title.includes("Options") || ["Caps", "Floors", "Swaptions", "Variance Swaps", "Dual-Currency Notes"].includes(title) ? "instrument" : title.includes("Methods") || title.includes("Monte Carlo") || title.includes("Differences") || title.includes("Reduction") ? "method" : "concept",
}))) as Seed[];

export const contentCatalog = [...seeds, ...expandedSeeds].map(createEntry);

export function assetPath(assetClass: AssetClass): string {
  return ({ Foundations: "foundations", EQ: "equity", FX: "fx", IR: "rates", COMM: "commodities", Frontier: "frontier" } as const)[assetClass];
}

export function findContent(asset: string, slug: string): ContentEntry | undefined {
  return contentCatalog.find((entry) => assetPath(entry.assetClass) === asset && entry.slug === slug);
}

export function findByTitle(title: string): ContentEntry | undefined {
  return contentCatalog.find((entry) => entry.title === title);
}
