"use client";

import { demoMarketQuotes, marketDetailPath } from "@/src/data/markets";
import { marketIntelligenceMetrics, quoteMoveLabel } from "@/src/data/marketMetrics";
import { pick, useI18n } from "@/src/i18n";

export function IntelligenceHub() {
  const { locale } = useI18n();
  return <div className="intelligence-page"><header className="page-hero compact-hero section-shell intelligence-hero"><div><span className="eyebrow">DETERMINISTIC MARKET INTELLIGENCE</span><h1>{pick(locale, { en: <>SIGNAL,<br /><em>WITH LINEAGE.</em></>, es: <>SEÑAL,<br /><em>CON PROCEDENCIA.</em></> })}</h1><p>{pick(locale, { en: "Transparent metrics computed from the displayed series. No LLM-generated prices, forecasts or trading instructions.", es: "Métricas transparentes calculadas desde las series mostradas. Sin precios ni previsiones generadas por IA." })}</p></div><aside className="market-status"><i /><strong>LOCAL ENGINE</strong><span>REFERENCE + FROZEN SCENARIOS</span></aside></header><section className="intelligence-grid section-shell">{demoMarketQuotes.map((quote) => { const metric = marketIntelligenceMetrics(quote.history); return <a href={marketDetailPath(quote.symbol)} className="intelligence-row" key={quote.symbol}><header><strong>{quote.displaySymbol}</strong><span>{quote.assetClass} · {quote.status}</span></header><div><Metric label="1D" value={`${metric.return1D >= 0 ? "+" : ""}${metric.return1D.toFixed(2)}%`} /><Metric label="5D" value={`${metric.return5D >= 0 ? "+" : ""}${metric.return5D.toFixed(2)}%`} /><Metric label="MOVE" value={quoteMoveLabel(quote.assetClass, quote.change)} /><Metric label="Z-SCORE" value={metric.zScore20D === null ? "n/a" : metric.zScore20D.toFixed(2)} /><Metric label="RANGE" value={metric.rangePosition === null ? "n/a" : `${Math.round(metric.rangePosition * 100)}%`} /></div><p><b>{pick(locale, { en: "WHY A QUANT CARES", es: "POR QUÉ IMPORTA" })}</b> {explain(quote.assetClass, locale)}</p><i>→</i></a>; })}</section><section className="method-note section-shell"><span>METHOD</span><p>{pick(locale, { en: "Returns, sample realized volatility, rolling z-score, range position and moving-average distance use only the visible local series. Short histories are labelled rather than padded or fabricated.", es: "Retornos, volatilidad realizada, z-score, posición en rango y distancia a la media usan solo la serie local visible. No se rellenan historiales cortos." })}</p></section></div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <span><small>{label}</small><b>{value}</b></span>; }
function explain(asset: string, locale: "en" | "es") { const en: Record<string, string> = { FX: "Pips and cross-currency carry connect spot to forwards and FX options.", EQ: "Spot moves alter delta, gamma concentration and implied-volatility coordinates.", IR: "Basis points transmit directly into discounting, forwards and DV01.", COMM: "Carry and curve shape can dominate the spot narrative." }; const es: Record<string, string> = { FX: "Los pips y el carry conectan spot, forwards y opciones FX.", EQ: "El spot altera delta, gamma y coordenadas de volatilidad implícita.", IR: "Los puntos básicos pasan al descuento, forwards y DV01.", COMM: "El carry y la curva pueden dominar al spot." }; return (locale === "en" ? en : es)[asset]; }
