"use client";

import { marketIntelligenceMetrics } from "@/src/data/marketMetrics";
import { defaultWatchlistIds, findInstrument } from "@/src/market-data/instrumentMaster";
import type { MarketInstrument } from "@/src/market-data/domain";
import { useMarketQuote, useMarketSnapshot } from "@/src/market-data/client/hooks";
import { formatTickMove } from "@/src/market-data/normalization";
import { pick, useI18n } from "@/src/i18n";

export function IntelligenceHub() {
  const { locale } = useI18n(); const instruments = defaultWatchlistIds.flatMap((id) => findInstrument(id) ?? []); useMarketSnapshot(defaultWatchlistIds, "LIVE_STREAM");
  return <div className="intelligence-page"><header className="page-hero compact-hero section-shell intelligence-hero"><div><span className="eyebrow">DETERMINISTIC MARKET INTELLIGENCE</span><h1>{pick(locale, { en: <>SIGNAL,<br /><em>WITH LINEAGE.</em></>, es: <>SEÑAL,<br /><em>CON PROCEDENCIA.</em></> })}</h1><p>{pick(locale, { en: "Transparent metrics computed from the displayed normalized series. No LLM-generated prices, forecasts or trading instructions.", es: "Métricas transparentes calculadas desde las series normalizadas. Sin precios ni previsiones generadas por IA." })}</p></div><aside className="market-status"><i /><strong>NORMALIZED STATE</strong><span>LIVE + REFERENCE + EXPLICIT DEMO</span></aside></header><section className="intelligence-grid section-shell">{instruments.map((instrument) => <IntelligenceRow instrument={instrument} locale={locale} key={instrument.id} />)}</section><section className="method-note section-shell"><span>METHOD</span><p>{pick(locale, { en: "Returns, sample realized volatility, rolling z-score, range position and moving-average distance use only the displayed provider series. Short histories are labelled rather than padded or fabricated.", es: "Retornos, volatilidad realizada, z-score, posición en rango y distancia a la media usan solo la serie visible del proveedor. No se rellenan historiales cortos." })}</p></section></div>;
}

function IntelligenceRow({ instrument, locale }: { instrument: MarketInstrument; locale: "en" | "es" }) { const quote = useMarketQuote(instrument.id); const metric = marketIntelligenceMetrics(quote?.history ?? []); const percentage = quote?.sessionChangePct; return <a href={`/markets/${instrument.slug}`} className="intelligence-row"><header><strong>{instrument.symbol}</strong><span>{instrument.assetClass} · {quote?.status ?? "LOADING"} · {quote?.source ?? "NORMALIZING"}</span></header><div><Metric label="SESSION" value={percentage === null || percentage === undefined ? "n/a" : `${percentage >= 0 ? "+" : ""}${percentage.toFixed(2)}%`} /><Metric label="5D" value={quote?.history.length ? `${metric.return5D >= 0 ? "+" : ""}${metric.return5D.toFixed(2)}%` : "n/a"} /><Metric label="TICK" value={quote ? formatTickMove(quote, instrument) : "n/a"} /><Metric label="Z-SCORE" value={metric.zScore20D === null ? "n/a" : metric.zScore20D.toFixed(2)} /><Metric label="RANGE" value={metric.rangePosition === null ? "n/a" : `${Math.round(metric.rangePosition * 100)}%`} /></div><p><b>{pick(locale, { en: "WHY A QUANT CARES", es: "POR QUÉ IMPORTA" })}</b> {explain(instrument.assetClass, locale)}</p><i>→</i></a>; }

function Metric({ label, value }: { label: string; value: string }) { return <span><small>{label}</small><b>{value}</b></span>; }
function explain(asset: string, locale: "en" | "es") { const en: Record<string, string> = { FX: "Pips and cross-currency carry connect spot to forwards and FX options.", EQUITY: "Spot moves alter delta, gamma concentration and implied-volatility coordinates.", INDEX: "Index level and breadth shape portfolio beta and volatility context.", RATES: "Basis points transmit directly into discounting, forwards and DV01.", COMMODITY: "Carry and curve shape can dominate the spot narrative.", CRYPTO: "Continuous trading makes tick and 24-hour semantics materially different." }; const es: Record<string, string> = { FX: "Los pips y el carry conectan spot, forwards y opciones FX.", EQUITY: "El spot altera delta, gamma y coordenadas de volatilidad implícita.", INDEX: "El nivel y amplitud del índice contextualizan beta y volatilidad.", RATES: "Los puntos básicos pasan al descuento, forwards y DV01.", COMMODITY: "El carry y la curva pueden dominar al spot.", CRYPTO: "La negociación continua cambia la semántica del tick y de las 24 horas." }; return (locale === "en" ? en : es)[asset] ?? "Source-aware observations preserve the boundary between data and model output."; }
