"use client";

import { assetPath, contentCatalog } from "@/src/content/catalog";
import { localizeEntry } from "@/src/content/localization";
import { pick, useI18n } from "@/src/i18n";

const status: Record<string, { en: string; es: string }> = { AAD: { en: "INDUSTRY STANDARD", es: "ESTÁNDAR DEL SECTOR" }, "GPU Monte Carlo": { en: "INDUSTRY STANDARD", es: "ESTÁNDAR DEL SECTOR" }, "Machine Learning Surrogates": { en: "ACTIVE DEPLOYMENT", es: "DESPLIEGUE ACTIVO" }, "Differentiable Pricing": { en: "EMERGING", es: "EMERGENTE" }, "Rough Volatility": { en: "ACTIVE RESEARCH", es: "INVESTIGACIÓN ACTIVA" }, "Deep Hedging": { en: "ACTIVE RESEARCH", es: "INVESTIGACIÓN ACTIVA" }, "Neural SDEs": { en: "ACTIVE RESEARCH", es: "INVESTIGACIÓN ACTIVA" }, "Bayesian Calibration": { en: "ACTIVE RESEARCH", es: "INVESTIGACIÓN ACTIVA" } };

export function ResearchFrontier() {
  const { locale } = useI18n(); const topics = contentCatalog.filter((entry) => entry.assetClass === "Frontier");
  return <><header className="page-hero section-shell research-hero"><span className="eyebrow">{pick(locale, { en: "QUANT FRONTIER · RESEARCH MAP", es: "FRONTERA QUANT · MAPA DE INVESTIGACIÓN" })}</span><h1>{pick(locale, { en: <>THE EDGE,<br /><em>WITHOUT THE HYPE.</em></>, es: <>LA FRONTERA,<br /><em>SIN HYPE.</em></> })}</h1><p>{pick(locale, { en: "Production technique, emerging infrastructure and active research are not interchangeable labels. We keep them visible.", es: "Técnica de producción, infraestructura emergente e investigación activa no son etiquetas intercambiables. Las mantenemos visibles." })}</p></header><section className="research-grid section-shell">{topics.map((topic, index) => { const localized = localizeEntry(topic, locale); const state = status[topic.title]?.[locale] ?? status[topic.title]?.en; return <a className="research-card" href={`/learn/${assetPath(topic.assetClass)}/${topic.slug}`} key={topic.slug}><header><span className="card-index">{String(index + 1).padStart(2, "0")}</span><b className={`research-status status-${status[topic.title].en.toLowerCase().replaceAll(" ", "-")}`}>{state}</b></header><h2>{localized.title}</h2><p>{localized.description}</p><div><span>{topic.type}</span><span>{topic.difficulty}</span><i>↗</i></div></a>; })}</section><section className="research-note section-shell"><span className="eyebrow light">{pick(locale, { en: "RESEARCH DISCIPLINE", es: "DISCIPLINA DE INVESTIGACIÓN" })}</span><h2>{pick(locale, { en: <>Fit is not evidence.<br />Speed is not governance.</>, es: <>El ajuste no es evidencia.<br />La velocidad no es gobernanza.</> })}</h2><p>{pick(locale, { en: "Experimental methods require benchmark error, stability domains, fallback models and production monitoring before they earn desk-standard status.", es: "Los métodos experimentales requieren error de benchmark, dominios de estabilidad, modelos de respaldo y monitorización antes de convertirse en estándar de mesa." })}</p></section></>;
}
