import type { AcademyLesson, AcademyReference, AcademyTrackNode } from "./types";

const reviewed = "2026-08-12";

const references: AcademyReference[] = [
  { sourceId: "grzelak-ir-xva", locator: "Curve construction, multi-curve, short-rate and HJM lectures", url: "https://github.com/LechGrzelak/FinancialEngineering_IR_xVA", note: "Research map for term-structure theory and numerical experiments; all platform explanations and code are original." },
  { sourceId: "grzelak-computational-finance", locator: "Monte Carlo, stochastic calculus and calibration lectures", url: "https://github.com/LechGrzelak/Computational-Finance-Course", note: "Mathematical and numerical cross-reference for model dynamics and diagnostics." },
  { sourceId: "quantlib-upstream", locator: "Current bootstrapping, interpolation, curve, model, cap/floor and swaption tests", url: "https://github.com/lballabio/QuantLib", note: "Implementation authority for production object boundaries and regression-test patterns." },
];

type AdvancedSeed = Omit<AcademyLesson, "domain" | "assetClass" | "lastReviewed" | "implementation" | "interactiveLabs" | "frontOffice" | "macroConnections" | "references"> & {
  quantLib: string;
  pythonLab: AcademyLesson["implementation"]["pythonLab"];
  lab: AcademyLesson["interactiveLabs"][number];
  frontOffice: AcademyLesson["frontOffice"];
  macro: AcademyLesson["macroConnections"][number];
};

const seeds: AdvancedSeed[] = [
  {
    id: "rate-curve-bootstrap", slug: "curve-bootstrapping", title: "Curve construction and bootstrapping", subtitle: "Solving a dated system of market instruments with repricing residuals at every pillar", level: "front-office", estimatedMinutes: 84,
    legacyRoutes: ["/learn/rates/yield-curves", "/learn/rates/curve-construction"], prerequisites: ["OIS", "FRAs and futures", "Interest-rate swaps", "Root finding"], learningObjectives: ["Map each market quote to its exact instrument cash flows and conventions.", "Bootstrap discount factors sequentially from deposits/OIS/futures/swaps.", "Diagnose quote repricing, pillar choice and interpolation dependence.", "Explain why a curve snapshot requires market data, conventions and construction policy together."], tags: ["bootstrapping", "yield curve", "rate helper", "pillar", "repricing"],
    intuition: { lead: "A bootstrap is a constrained inverse problem. Each liquid quote contributes an equation; the curve is accepted only when every calibration instrument reprices under the same conventions and interpolation policy.", points: ["Instrument quotes are equations, not curve nodes until cash flows are modelled.", "Sequential solution works when each new helper introduces one new degree of freedom.", "A tiny quote residual can coexist with unstable forwards, so repricing and shape diagnostics are both mandatory."] },
    marketContext: { why: "Discounting, forecasting, carry, hedging and every downstream model depend on a curve that converts heterogeneous market quotes into consistent dated prices.", instruments: ["overnight deposits and OIS", "rate futures and FRAs", "fixed-for-floating swaps", "basis swaps"], quoteConvention: "Store bid, ask, mid, timestamp, source, currency, index, tenor, settlement, day count, calendar, compounding and pillar rule with every helper." },
    mathematics: { notation: ["q_i: i-th market quote", "\\theta_i: i-th curve node", "V_i(\\theta): model PV", "\\varepsilon_i: quote repricing residual"], formulas: [
      { label: "Bootstrap equation", latex: "V_i(\\theta_1,\\ldots,\\theta_i;q_i)=0", interpretation: "The i-th par instrument determines the next unknown curve node after earlier nodes are fixed." },
      { label: "Repricing residual", latex: "\\varepsilon_i=q_i^{model}(\\theta)-q_i^{market}", interpretation: "Residuals must be reported in the market quote’s native unit and compared with tolerance or spread." },
      { label: "Curve objective for global fits", latex: "\\min_{\\theta}\\sum_i w_i\\varepsilon_i^2+\\lambda\\,\\mathcal R(\\theta)", interpretation: "A global fit can trade exact repricing for stability through weights and regularisation; that trade-off must be explicit." },
    ] },
    derivation: { title: "Sequentially solving a par swap pillar", introduction: "Assume earlier discount factors are known and isolate the final maturity discount factor from the newest par instrument.", steps: [
      { title: "Write the par equation", body: "For an annual fixed-for-floating single-curve swap, fixed PV equals 1−P(0,T_n).", latex: "K\\sum_{j=1}^{n}\\alpha_jP(0,T_j)=1-P(0,T_n)" },
      { title: "Separate known coupons", body: "All payment-date factors before T_n were solved by earlier helpers; leave the final factor as the only unknown.", latex: "K\\sum_{j<n}\\alpha_jP_j+K\\alpha_nP_n=1-P_n" },
      { title: "Solve the new node", body: "Collect P_n and divide by its positive coefficient.", latex: "P_n=\\frac{1-K\\sum_{j<n}\\alpha_jP_j}{1+K\\alpha_n}" },
      { title: "Insert and reprice", body: "Add the node to the curve, rebuild the instrument and compute its quote residual using the final interpolation.", check: "Every helper—not only the newest one—must still reprice after the curve is complete." },
      { title: "Inspect the implied forwards", body: "Compute adjacent forwards and key-rate sensitivities; reject local spikes or negative accumulations that the quote residual alone cannot reveal." },
    ], conclusion: "A production curve is a reproducible construction policy with instrument-level repricing and shape diagnostics, not an interpolated list of displayed rates." },
    pricing: { method: "Order helpers by pillar, solve each unknown in discount or log-discount space, rebuild all instruments, and expose zero, forward, discount and risk views from one curve object.", calibration: "Use bid/ask-aware tolerances, deterministic pillar dates, documented interpolation and fallback rules. Retain both input quote and solved node lineage.", limitations: ["The closed-form swap step is educational and single-curve.", "Global and sequential fits can differ under inconsistent or noisy quotes.", "Exact repricing does not guarantee stable off-grid forwards or hedge ratios."] },
    pythonLab: { title: "Sequential par-swap discount bootstrap", objective: "Solve final discount factors and verify every par equation.", code: `from __future__ import annotations\n\nimport math\n\ndef bootstrap_annual_swaps(par_rates: list[float]) -> list[float]:\n    discounts: list[float] = []\n    for rate in par_rates:\n        if not math.isfinite(rate):\n            raise ValueError("finite quote required")\n        known_annuity = sum(discounts)\n        final_discount = (1.0 - rate * known_annuity) / (1.0 + rate)\n        if final_discount <= 0:\n            raise ValueError("inconsistent quote set")\n        discounts.append(final_discount)\n    return discounts\n\nquotes = [0.0300, 0.0320, 0.0340, 0.0350, 0.0360]\ndf = bootstrap_annual_swaps(quotes)\nfor maturity, (rate, terminal) in enumerate(zip(quotes, df), start=1):\n    fixed = rate * sum(df[:maturity])\n    floating = 1.0 - terminal\n    assert abs(fixed - floating) < 1e-12\nprint([round(x, 8) for x in df])`, output: ["A positive, decreasing discount-factor vector with zero par-swap residuals."], checks: ["Every quote is finite.", "Every solved factor is positive.", "All calibration swaps reprice after the final node is added."] },
    quantLib: "Compose instrument-specific RateHelpers into PiecewiseYieldCurve with explicit traits and interpolation. Preserve helper impliedQuote/error diagnostics, pillar choices and observer lifecycle; current upstream tests are the API authority.", lab: { id: "curve-bootstrapping", title: "Curve construction workbench", description: "Shock liquid pillars and inspect linked zero, forward, discount and key-rate views with repricing diagnostics." },
    frontOffice: { quote: "If a quote cannot be traced to a helper, convention, pillar and residual, it is not a curve input—it is a loose number.", inputs: ["timestamped bid/ask quotes", "instrument conventions", "pillar policy", "interpolation/extrapolation", "tolerances and fallback"], calibration: "Bootstrap in dependency order, reprice every helper after construction and compare residuals with bid/offer and desk tolerances.", risk: ["pillar/key-rate DV01", "instrument basis", "interpolation risk", "stale-quote risk"], workflow: ["freeze market snapshot", "validate helper set", "solve nodes", "reprice all helpers", "inspect forwards and risk"], productionIssues: ["duplicate pillar", "missing short-end anchor", "mixed calendars", "curve rebuilt from partially updated quotes"] },
    macro: { title: "Market instruments into a policy and term-premium curve", thesis: "Macro expectations arrive through different liquid instruments by tenor; the bootstrap converts their quotes into one dated pricing representation.", nodes: [{ label: "Macro repricing", effect: "moves deposits, futures and swaps" }, { label: "Helper equations", effect: "translate quotes into cash-flow constraints" }, { label: "Curve nodes", effect: "solve dated discount prices" }, { label: "Portfolio risk", effect: "maps exposure back to liquid hedges" }] },
    pitfalls: ["Treating quoted swap rates as continuous zero rates.", "Checking only node monotonicity and not helper repricing.", "Changing interpolation without rerunning risk and validation.", "Using asynchronous quote timestamps as one coherent market snapshot."], relatedLessonIds: ["rate-swaps", "rate-interpolation", "rate-multicurve"],
  },
  {
    id: "rate-interpolation", slug: "curve-interpolation", title: "Curve interpolation, extrapolation and arbitrage", subtitle: "Choosing the state to interpolate by controlling off-grid discount and forward behaviour", level: "advanced", estimatedMinutes: 72,
    legacyRoutes: ["/learn/rates/interpolation"], prerequisites: ["Curve bootstrapping", "Forward rates", "Numerical interpolation"], learningObjectives: ["Compare linear-zero, log-linear-discount and monotone interpolation.", "Derive the forward curve implied by an interpolation rule.", "Detect negative discount factors, impossible accumulations and local forward spikes.", "Explain why interpolation is a risk-model choice between liquid pillars."], tags: ["interpolation", "extrapolation", "forward stability", "arbitrage"],
    intuition: { lead: "The market constrains a sparse set of instruments, but valuation asks for every date. Interpolation specifies the untraded economy between pillars and therefore changes cash-flow PV, carry and hedge allocation.", points: ["Interpolate a mathematically controlled state, not whichever quote is easiest to display.", "Log-linear discounting preserves positive discount factors and gives piecewise-constant continuous forwards.", "Smooth curves can still be economically unstable if their derivatives oscillate."] },
    marketContext: { why: "Off-grid coupons, broken-date trades, forward starts and risk buckets all depend on interpolation and extrapolation beyond liquid tenors.", instruments: ["broken-date swaps", "forward-start swaps", "bonds", "long-dated exotics"], quoteConvention: "Record interpolation variable, order, boundary conditions, extrapolation policy and the liquid horizon with every curve build." },
    mathematics: { notation: ["\\ell(T)=\\ln P(0,T): log discount", "f(0,T)=-\\ell'(T): instantaneous forward", "T_i: liquid pillars", "w(T): interpolation weight"], formulas: [
      { label: "Log-linear discount", latex: "\\ell(T)=(1-w)\\ell(T_i)+w\\ell(T_{i+1})", interpretation: "Linear interpolation in log discount guarantees a positive discount factor after exponentiation." },
      { label: "Segment forward", latex: "f_i=-\\frac{\\ell(T_{i+1})-\\ell(T_i)}{T_{i+1}-T_i}", interpretation: "Log-linear discounting implies one constant continuous forward on each segment." },
      { label: "Reconstruction identity", latex: "P(0,T)=\\exp\\left(-\\int_0^T f(0,u)\\,du\\right)", interpretation: "Any interpolated forward representation must integrate back to the discount curve." },
    ] },
    derivation: { title: "From log-discount interpolation to a segment forward", introduction: "Differentiate the state actually interpolated, then inspect the economic quantity used by forward-start products.", steps: [
      { title: "Choose log discount as state", body: "Write ℓ_i=ln P_i at each positive discount pillar." },
      { title: "Interpolate linearly", body: "Between T_i and T_{i+1}, ℓ has a constant slope.", latex: "\\ell(T)=\\ell_i+\\frac{T-T_i}{T_{i+1}-T_i}(\\ell_{i+1}-\\ell_i)" },
      { title: "Differentiate", body: "The negative derivative of ℓ is the instantaneous forward and is constant on the segment.", latex: "f_i=-(\\ell_{i+1}-\\ell_i)/(T_{i+1}-T_i)" },
      { title: "Reintegrate", body: "Integrating the segment forwards reproduces every input pillar exactly.", check: "Interpolated discounts at T_i must equal input discounts to machine tolerance." },
      { title: "Stress the boundaries", body: "Inspect discontinuities in forwards at nodes and compare extrapolated PV/risk outside the last liquid tenor." },
    ], conclusion: "Interpolation selects off-grid forwards and risk allocation; it belongs in model governance, not chart styling." },
    pricing: { method: "Interpolate one controlled state, expose derived zero/forward/discount views, and run node-reconstruction plus off-grid perturbation tests.", calibration: "Choose the rule by product needs, hedge stability and historical robustness—not in-sample curve smoothness alone.", limitations: ["Piecewise-constant forwards jump at pillars.", "Higher-order splines can overshoot or create oscillating forwards.", "Any extrapolation beyond the liquid horizon is a model assumption."] },
    pythonLab: { title: "Log-linear discount interpolation", objective: "Preserve node discounts and verify a constant segment forward.", code: `from __future__ import annotations\n\nimport math\n\ndef log_linear(t: float, t0: float, p0: float, t1: float, p1: float) -> float:\n    if not (0 < t0 < t1 and t0 <= t <= t1 and p0 > 0 and p1 > 0):\n        raise ValueError("invalid interpolation domain")\n    w = (t - t0) / (t1 - t0)\n    return math.exp(math.log(p0) + w * (math.log(p1) - math.log(p0)))\n\np1, p3 = math.exp(-0.02), math.exp(-0.03 * 3.0)\np2 = log_linear(2.0, 1.0, p1, 3.0, p3)\nassert abs(math.log(p1 / p2) - math.log(p2 / p3)) < 1e-12\nassert log_linear(1.0, 1.0, p1, 3.0, p3) == p1\nprint(f"P2={p2:.9f}")`, output: ["An interior discount factor with equal one-year continuous forwards on both halves."], checks: ["Input discounts remain positive.", "Pillar values are reconstructed.", "Segment-forward identity holds."] },
    quantLib: "Select curve traits and interpolation deliberately—Discount/LogLinear, Zero/Linear or Forward variants imply different off-grid dynamics. Lock the policy in regression tests with discounts, forwards and instrument NPVs.", lab: { id: "curve-interpolation", title: "Interpolation stress laboratory", description: "Compare linear-zero, log-linear-discount and monotone shapes; expose their forward and off-grid PV consequences." },
    frontOffice: { quote: "The interpolation rule is where a sparse market becomes a dense risk model.", inputs: ["curve pillars", "interpolated state", "boundary conditions", "liquid horizon", "product cash-flow dates"], calibration: "Reprice pillars identically, then choose among candidates using forward stability, hedge stability and out-of-sample broken-date behaviour.", risk: ["off-grid DV01", "node allocation", "forward discontinuity", "extrapolation"], workflow: ["fit same pillars", "derive forwards", "stress nodes", "compare broken dates", "approve one governed rule"], productionIssues: ["spline overshoot", "hidden extrapolation", "negative discount output", "risk jumps after library upgrade"] },
    macro: { title: "Interpolation and the shape of priced expectations", thesis: "Markets quote a few tenors; interpolation controls how a macro move is distributed between them and therefore how slope or butterfly risk appears.", nodes: [{ label: "Macro move", effect: "reprices liquid pillars" }, { label: "Interpolation", effect: "fills unquoted dates" }, { label: "Forward shape", effect: "allocates local expectations" }, { label: "Hedge map", effect: "assigns risk to instruments" }] },
    pitfalls: ["Choosing interpolation for visual smoothness only.", "Inspecting zero rates without instantaneous forwards.", "Assuming exact pillar fit means identical off-grid PV.", "Extrapolating silently beyond market liquidity."], relatedLessonIds: ["rate-curve-bootstrap", "rate-multicurve", "rate-curve-risk"],
  },
  {
    id: "rate-multicurve", slug: "multi-curve-framework", title: "Multi-curve valuation and basis", subtitle: "Separating collateral discounting from index-specific forward projection", level: "front-office", estimatedMinutes: 78,
    legacyRoutes: ["/learn/rates/multi-curve", "/learn/rates/basis-swaps"], prerequisites: ["OIS discounting", "Interest-rate swaps", "Curve bootstrapping"], learningObjectives: ["Explain why discount and projection curves have different roles.", "Price floating coupons with an index curve and collateral discount curve.", "Derive a basis-spread par condition.", "Identify cross-curve sensitivities and bootstrap dependency order."], tags: ["multi-curve", "basis", "discounting", "projection curve"],
    intuition: { lead: "Post-crisis rates valuation separates the curve that discounts collateralised cash flows from curves that project index-specific fixings. Basis quotes reconcile cash-flow streams carrying different tenor, liquidity and credit characteristics.", points: ["One cash flow can depend on one curve for projection and another for discounting.", "Each index tenor needs its own forward representation when basis is material.", "A multi-curve build is a dependency graph; rebuilding order and joint sensitivities matter."] },
    marketContext: { why: "Multi-curve valuation is required for swaps, basis swaps, caps/floors and swaptions whose index projection differs from collateral discounting.", instruments: ["OIS", "term-index swaps", "tenor basis swaps", "cross-currency basis swaps"], quoteConvention: "State discount collateral, projected index and tenor, basis-leg sign, spread placement, reset frequency and all schedules." },
    mathematics: { notation: ["P_d(0,T): discount-curve factor", "F_p(0;T_{i-1},T_i): projection-curve forward", "s: quoted basis spread", "A_d: discounted spread annuity"], formulas: [
      { label: "Projected floating leg", latex: "PV_{flt}^{p,d}=N\\sum_i\\delta_iP_d(0,T_i)F_p(0;T_{i-1},T_i)", interpretation: "Projection supplies expected coupon rates; collateral discounting supplies present-value weights." },
      { label: "Basis par condition", latex: "PV_A+sA_A=PV_B", interpretation: "The quoted spread equalises two index-specific floating legs after common collateral discounting." },
      { label: "Basis spread", latex: "s=\\frac{PV_B-PV_A}{A_A}", interpretation: "Spread is the residual value difference divided by the discounted accrual annuity of the spread-paying leg." },
    ] },
    derivation: { title: "Solving a tenor-basis spread", introduction: "Price each projected floating stream separately, then solve for the spread that restores zero PV.", steps: [
      { title: "Build collateral discounting", body: "Construct P_d from collateral-consistent OIS instruments." },
      { title: "Project each index", body: "Use the A- and B-tenor forwarding curves to produce period-specific forwards on their exact schedules." },
      { title: "Discount both streams", body: "Apply the same collateral discount curve to every payment while retaining distinct projections.", latex: "PV_A=N\\sum_i\\delta_i^AP_d(T_i^A)F_A^i" },
      { title: "Solve for the basis", body: "Add s to the designated leg and set net PV to zero.", latex: "s=(PV_B-PV_A)/[N\\sum_i\\delta_i^AP_d(T_i^A)]" },
      { title: "Differentiate jointly", body: "Bump discount, A-projection and B-projection quotes independently and together to identify cross-curve dependencies.", check: "The calibrated basis swap must reprice to zero under the stated spread sign." },
    ], conclusion: "Multi-curve valuation makes curve role explicit: discounting prices collateralised cash flows; index curves project contractual fixings." },
    pricing: { method: "Construct the OIS discount curve first, then projection curves in a documented dependency order using swaps and basis instruments; price with separate typed handles.", calibration: "Reprice OIS, outright swaps and basis swaps after every dependent curve build. Report residuals and cross-curve Jacobians.", limitations: ["The framework does not eliminate bank credit, funding or CSA optionality.", "Legacy index fallback and cessation require contract-specific treatment.", "Joint curve calibration can be ill-conditioned in illiquid tenors."] },
    pythonLab: { title: "Two-curve floating-leg valuation", objective: "Show how a projection spread changes PV under fixed OIS discounting.", code: `from __future__ import annotations\n\nimport math\n\ntimes = [1., 2., 3., 4., 5.]\ndiscounts = [math.exp(-0.032*t) for t in times]\nois_forwards = [0.033, 0.034, 0.035, 0.036, 0.037]\nterm_forwards = [f + 0.004 for f in ois_forwards]\naccruals = [1.0] * len(times)\n\ndef leg(forwards: list[float]) -> float:\n    return sum(a*p*f for a, p, f in zip(accruals, discounts, forwards))\n\nannuity = sum(a*p for a, p in zip(accruals, discounts))\nbasis = (leg(term_forwards) - leg(ois_forwards)) / annuity\nassert abs(basis - 0.004) < 1e-12\nprint(f"par basis={basis:.2%}")`, output: ["A 40bp par basis when every projected term forward is 40bp above OIS."], checks: ["Both legs share discounting.", "Each leg retains its projection curve.", "Basis sign matches the spread-paying leg."] },
    quantLib: "Use separate RelinkableHandle<YieldTermStructure> objects for discounting and each index. Bootstrap dependencies deterministically and avoid accidental handle aliasing between OvernightIndex and IborIndex projections.", lab: { id: "multi-curve", title: "Multi-curve basis laboratory", description: "Move OIS, term projection and basis independently; inspect swap PV and risk by curve role." },
    frontOffice: { quote: "‘The curve moved’ is incomplete until you say discount curve, projection curve and tenor basis.", inputs: ["OIS curve", "index-specific swaps", "basis quotes", "CSA currency", "curve dependency graph"], calibration: "Build discounting before projection, then solve basis-linked curves and reprice the full dependency set after each update.", risk: ["discount DV01", "projection DV01", "tenor basis", "cross-curve Jacobian"], workflow: ["freeze all quote sets", "build OIS", "build projection curves", "reprice basis", "aggregate risk by role"], productionIssues: ["curve-handle aliasing", "circular dependency", "wrong basis sign", "staggered quote timestamps"] },
    macro: { title: "Liquidity and credit transmission through basis", thesis: "Funding stress, index credit sensitivity and liquidity demand can widen the spread between overnight discounting and term-index projection.", nodes: [{ label: "Funding/liquidity shock", effect: "changes term-index premium" }, { label: "Basis quotes", effect: "separate projection curves" }, { label: "Multi-curve PV", effect: "revalues floating streams" }, { label: "Cross-curve hedge", effect: "allocates OIS and basis risk" }] },
    pitfalls: ["Projecting term coupons from the OIS curve.", "Discounting collateralised cash flows on an index curve.", "Reporting one net DV01 for dependent curves.", "Building projection curves before their discount dependency is frozen."], relatedLessonIds: ["rate-ois", "rate-curve-bootstrap", "rate-curve-risk"],
  },
  {
    id: "rate-curve-risk", slug: "curve-risk", title: "Curve risk, carry and roll-down", subtitle: "Moving from one parallel DV01 to bucketed scenarios, hedge instruments and time passage", level: "front-office", estimatedMinutes: 76,
    legacyRoutes: ["/learn/rates/dv01", "/learn/rates/key-rate-duration"], prerequisites: ["Interest-rate swaps", "Curve bootstrapping", "Multi-curve valuation"], learningObjectives: ["Define PV01/DV01 with sign, bump size and curve role.", "Construct key-rate and quote-space sensitivities.", "Separate carry, roll-down and market-move P&L.", "Design level, slope and butterfly scenarios without double counting."], tags: ["DV01", "key rate", "carry", "roll-down", "P&L attribution"],
    intuition: { lead: "A portfolio does not own ‘duration’ in the abstract. It owns sensitivity to specific curve inputs, dates and curve roles; as time passes, cash flows roll through that geometry even if market quotes do not move.", points: ["DV01 must state whether rates are bumped up or down and whether it is PV change or signed derivative.", "Key-rate risk depends on bump shape and curve rebuild policy.", "Carry and roll-down are scenario P&L under a frozen-market assumption, not guaranteed return."] },
    marketContext: { why: "Trading limits, hedge sizing, P&L explanation and macro scenario design require exposures that map back to liquid curve instruments.", instruments: ["swaps and futures", "government bonds", "basis swaps", "options on rates"], quoteConvention: "Report currency, valuation date, curve role, quote set, bump direction/size, rebuild mode and units. One basis point is 0.0001 in decimal rates." },
    mathematics: { notation: ["V(q): portfolio PV from market quotes", "DV01_i: i-th quote sensitivity", "h=10^{-4}: one-bp bump", "\\Delta t: carry horizon"], formulas: [
      { label: "Signed quote DV01", latex: "DV01_i=V(q_i+h)-V(q_i)", interpretation: "This convention reports PV change for a +1bp quote bump; many desks use the negative or symmetric derivative, so sign must be stated." },
      { label: "First-order scenario P&L", latex: "\\Delta V\\approx\\sum_i\\frac{\\partial V}{\\partial q_i}\\Delta q_i", interpretation: "Quote-space gradients map a prescribed level, slope or butterfly move into approximate P&L." },
      { label: "Carry/roll decomposition", latex: "\\Delta V_{frozen}=\\Theta_{carry}\\Delta t+\\Delta V_{roll}+\\Delta V_{cash}", interpretation: "Under a frozen curve, accrual, curve roll and realised cash flows are separated for attribution." },
    ] },
    derivation: { title: "From curve-node shocks to liquid hedge ratios", introduction: "Differentiate the entire calibration-and-pricing pipeline with respect to market quotes, not only internal zero nodes.", steps: [
      { title: "Freeze the market state", body: "Store quote snapshot, curve policy, trade state and base PV." },
      { title: "Bump one liquid quote", body: "Move q_i by h, rebuild every dependent curve and reprice the portfolio." },
      { title: "Record the signed PV change", body: "Retain V(q_i+h)−V(q), the bump size and the affected curve role." },
      { title: "Assemble scenario vectors", body: "Combine quote DV01s with level, slope or butterfly shock vectors while keeping units consistent.", latex: "\\Delta V_{lin}=J_q\\Delta q" },
      { title: "Validate nonlinearity", body: "Compare up/down symmetric bumps and full revaluation under larger scenarios.", check: "The sum of bucketed first-order contributions should reconcile with a parallel small-bump PV change within curvature tolerance." },
    ], conclusion: "Curve risk is a Jacobian from liquid market quotes to portfolio value, augmented by nonlinear scenarios and time-passage attribution." },
    pricing: { method: "Bump liquid calibration quotes, rebuild all dependent curves and return signed quote-space risk plus internal node diagnostics and full-revaluation scenarios.", calibration: "Use stable bump sizes, symmetric checks and a frozen dependency graph. Version curve construction alongside risk results.", limitations: ["Finite differences mix model nonlinearity with rebuild effects.", "Key-rate results depend on interpolation and bump localisation.", "Frozen-curve carry omits future market moves, funding and execution costs."] },
    pythonLab: { title: "Parallel and key-rate DV01", objective: "Compute signed +1bp PV changes and reconcile the bucket sum with a parallel bump.", code: `from __future__ import annotations\n\nimport math\n\ntimes = [1., 2., 5., 10., 20.]\ncashflows = [2., 2., 2., 2., 102.]\nrates = [0.03, 0.032, 0.035, 0.038, 0.04]\nh = 1e-4\n\ndef pv(curve: list[float]) -> float:\n    return sum(c*math.exp(-r*t) for c, r, t in zip(cashflows, curve, times))\n\nbase = pv(rates)\nbuckets = []\nfor i in range(len(rates)):\n    bumped = rates.copy(); bumped[i] += h\n    buckets.append(pv(bumped) - base)\nparallel = pv([r+h for r in rates]) - base\nassert abs(sum(buckets) - parallel) < 0.01\nassert all(x < 0 for x in buckets)\nprint(f"parallel +1bp={parallel:.6f}")`, output: ["Negative +1bp PV change and bucket sum close to parallel full revaluation."], checks: ["Bump is exactly 0.0001.", "Sign convention is +1bp PV change.", "Bucket sum reconciles within a stated curvature tolerance."] },
    quantLib: "Relink or rebuild quote handles one at a time and force dependent term structures to update before repricing. Preserve base/bumped snapshots; validate quote-space risk against analytical cash-flow sensitivities where available.", lab: { id: "curve-risk", title: "Key-rate and scenario laboratory", description: "Apply parallel, steepener, flattener and butterfly shocks; inspect bucketed DV01, carry and roll-down." },
    frontOffice: { quote: "A DV01 without curve role, bump sign and rebuild policy cannot be hedged or reconciled.", inputs: ["portfolio cash flows", "market quote set", "curve dependency graph", "bump policy", "carry horizon"], calibration: "Risk must use the same accepted curve build as valuation; symmetric and parallel-reconciliation tests are release gates.", risk: ["level/slope/butterfly", "key-rate concentration", "carry/roll", "basis and convexity"], workflow: ["freeze base PV", "bump/rebuild", "aggregate buckets", "run full scenarios", "attribute carry and market move"], productionIssues: ["mixed DV01 signs", "partial dependency rebuild", "bump too small/large", "risk reported in internal nodes only"] },
    macro: { title: "Macro scenarios as curve-factor shocks", thesis: "Policy, inflation, growth and supply shocks rarely move every tenor equally; level, slope and butterfly factors connect narratives to portfolio P&L.", nodes: [{ label: "Macro thesis", effect: "defines tenor-specific shock" }, { label: "Curve factors", effect: "encode level/slope/butterfly" }, { label: "Quote sensitivities", effect: "map shock into PV" }, { label: "Hedge decision", effect: "targets residual factor risk" }] },
    pitfalls: ["Calling PV change for +1bp ‘DV01’ without sign definition.", "Summing risks across currencies without FX and units.", "Computing node risk without rebuilding calibrated curves.", "Treating carry as a forecast-free profit."], relatedLessonIds: ["rate-interpolation", "rate-hull-white", "rate-hjm"],
  },
  {
    id: "rate-hull-white", slug: "hull-white", title: "Hull–White one-factor model", subtitle: "Fitting today’s term structure while modelling mean-reverting Gaussian short-rate dynamics", level: "advanced", estimatedMinutes: 88,
    legacyRoutes: ["/learn/volatility/hull-white", "/learn/rates/short-rate-models"], prerequisites: ["Stochastic differential equations", "No-arbitrage term structures", "Rate options"], learningObjectives: ["Relate Ho–Lee, Vasicek and Hull–White short-rate dynamics.", "Derive the conditional Gaussian distribution of the mean-reverting factor.", "Explain how the time-dependent drift fits the initial curve.", "Price or calibrate caps/swaptions while diagnosing negative-rate and one-factor limitations."], tags: ["Hull-White", "short rate", "mean reversion", "swaption", "Jamshidian"],
    intuition: { lead: "Hull–White adds a deterministic time-dependent drift to an Ornstein–Uhlenbeck short-rate process. That shift fits today’s discount curve exactly, while mean reversion and volatility govern future rate distributions.", points: ["Curve fit and dynamic calibration are separate tasks.", "Gaussian rates permit analytic bond formulas and negative outcomes.", "One factor moves the entire curve through a single source of randomness, limiting decorrelation across tenors."] },
    marketContext: { why: "Hull–White remains a transparent benchmark for callable structures, Bermudan exercise, exposure simulation and rate-option calibration.", instruments: ["caps and floors", "European swaptions", "callable bonds", "Bermudan swaptions"], quoteConvention: "Rate-option calibration must state normal/lognormal/shifted volatility convention, forward, annuity, expiry, tenor, strike, settlement and collateral curves." },
    mathematics: { notation: ["r_t: short rate", "a: mean-reversion speed", "\\sigma: short-rate volatility", "\\theta(t): curve-fitting drift"], formulas: [
      { label: "Hull–White dynamics", latex: "dr_t=[\\theta(t)-a r_t]dt+\\sigma dW_t", interpretation: "A time-inhomogeneous Gaussian short rate mean reverts at speed a with volatility σ." },
      { label: "Conditional variance", latex: "\\operatorname{Var}_t(r_T)=\\frac{\\sigma^2}{2a}\\left(1-e^{-2a(T-t)}\\right)", interpretation: "Mean reversion bounds long-horizon short-rate variance when a>0." },
      { label: "Affine bond price", latex: "P(t,T)=A(t,T)e^{-B(t,T)r_t},\\quad B(t,T)=\\frac{1-e^{-a(T-t)}}{a}", interpretation: "Zero-coupon bond prices are exponential-affine in the short rate." },
    ] },
    derivation: { title: "Solving the mean-reverting Gaussian factor", introduction: "Apply an integrating factor to the linear short-rate SDE and separate deterministic drift from stochastic innovation.", steps: [
      { title: "Multiply by the integrating factor", body: "Apply e^{at} so the mean-reversion term becomes an exact differential.", latex: "d(e^{at}r_t)=e^{at}\\theta(t)dt+\\sigma e^{at}dW_t" },
      { title: "Integrate from t to T", body: "Solve for r_T as decayed current state plus deterministic drift integral and a Gaussian stochastic integral.", latex: "r_T=e^{-a\\tau}r_t+\\int_t^T e^{-a(T-u)}\\theta(u)du+\\sigma\\int_t^T e^{-a(T-u)}dW_u" },
      { title: "Compute the variance", body: "Itô isometry converts the stochastic-integral variance into an ordinary integral.", latex: "\\sigma^2\\int_t^T e^{-2a(T-u)}du=\\sigma^2(1-e^{-2a\\tau})/(2a)" },
      { title: "Fit the initial term structure", body: "Choose θ(t), or an equivalent deterministic shift φ(t), so model P(0,T) equals the observed discount curve at every maturity." },
      { title: "Calibrate option dynamics", body: "Fit a and σ—or piecewise volatility—to a governed cap/swaption basket after the curve fit.", check: "Model zero-coupon prices at t=0 must reconstruct the input discount curve independently of option parameters." },
    ], conclusion: "Hull–White separates exact initial-curve fit from a parsimonious one-factor Gaussian dynamics used for optionality and scenarios." },
    pricing: { method: "Fit the deterministic shift to the discount curve, calibrate dynamic parameters to a stated option-volatility convention and use analytic, tree or Monte Carlo engines appropriate to exercise style.", calibration: "Calibrate with bid/ask-aware weights, multiple starts and stability diagnostics. Compare caps and swaption tenors not used in the fit.", limitations: ["Gaussian short rates permit arbitrarily negative values.", "One factor cannot reproduce independent curve twists.", "Parameters can be weakly identified and regime dependent."] },
    pythonLab: { title: "Exact Hull–White factor transition", objective: "Simulate the mean-zero Ornstein–Uhlenbeck factor with the exact Gaussian variance.", code: `from __future__ import annotations\n\nimport math\nimport numpy as np\n\ndef hw_transition(x: np.ndarray, a: float, sigma: float, dt: float, z: np.ndarray) -> np.ndarray:\n    if a <= 0 or sigma < 0 or dt <= 0 or x.shape != z.shape:\n        raise ValueError("invalid Hull-White transition")\n    decay = math.exp(-a * dt)\n    variance = sigma*sigma * (1.0 - math.exp(-2.0*a*dt)) / (2.0*a)\n    return decay*x + math.sqrt(variance)*z\n\nrng = np.random.default_rng(7)\nz = rng.standard_normal(200_000)\nx = hw_transition(np.zeros_like(z), 0.08, 0.01, 1.0, z)\ntheory = 0.01**2 * (1-math.exp(-0.16)) / 0.16\nassert abs(np.var(x) - theory) / theory < 0.015\nprint(f"sample variance={np.var(x):.8f} | theory={theory:.8f}")`, output: ["Sample variance within 1.5% of the exact transition variance."], checks: ["Mean reversion and time step are positive.", "Deterministic random seed is fixed.", "Monte Carlo moment matches the analytical reference."] },
    quantLib: "Construct HullWhite from the accepted yield-curve handle, then use model-consistent engines and CalibrationHelpers for caps/swaptions. Recheck calibration after relinking the curve and inspect helper errors individually.", lab: { id: "hull-white", title: "Hull–White dynamics laboratory", description: "Move mean reversion, volatility and policy shock; inspect short-rate distribution, bond response and curve-factor decay." },
    frontOffice: { quote: "Hull–White fits today’s curve by construction; calibration quality is about tomorrow’s distribution and option basket.", inputs: ["discount curve", "swaption/cap volatility basket", "volatility convention", "mean reversion", "model/engine discretisation"], calibration: "Fit curve deterministically, then calibrate dynamics with residual, parameter-bound and out-of-sample diagnostics.", risk: ["mean-reversion risk", "volatility buckets", "one-factor basis", "exercise/model risk"], workflow: ["freeze curve/vol snapshot", "fit deterministic shift", "calibrate a/σ", "validate helpers", "run scenarios and hedges"], productionIssues: ["normal/lognormal mismatch", "curve relink without recalibration", "parameter boundary", "tree time-grid misalignment"] },
    macro: { title: "Mean reversion and policy regimes", thesis: "Policy shocks move the short end immediately; the mean-reversion parameter determines how quickly model scenarios pull that disturbance back toward the fitted term structure.", nodes: [{ label: "Policy shock", effect: "moves current short-rate state" }, { label: "Mean reversion", effect: "controls persistence" }, { label: "Bond/option values", effect: "respond through affine dynamics" }, { label: "Callable risk", effect: "changes exercise and convexity" }] },
    pitfalls: ["Calling exact initial-curve fit a successful option calibration.", "Comparing normal and lognormal swaption vols directly.", "Ignoring negative-rate tails of a Gaussian model.", "Using one factor for curve-basis risk it cannot span."], relatedLessonIds: ["rate-curve-risk", "rate-hjm"],
  },
  {
    id: "rate-hjm", slug: "hjm-and-market-models", title: "HJM and market-model dynamics", subtitle: "Modelling the whole forward curve under a no-arbitrage drift restriction", level: "front-office", estimatedMinutes: 92,
    legacyRoutes: ["/learn/rates/hjm", "/learn/rates/libor-market-model"], prerequisites: ["Stochastic calculus", "Forward rates", "Change of numeraire", "Hull–White"], learningObjectives: ["State HJM forward-rate dynamics and derive the no-arbitrage drift restriction.", "Explain how volatility choice determines drift under the risk-neutral measure.", "Relate HJM, Gaussian short-rate models and forward market models.", "Design curve simulations that preserve initial term structure and report discretisation diagnostics."], tags: ["HJM", "forward curve", "no-arbitrage drift", "market model", "measure"],
    intuition: { lead: "Heath–Jarrow–Morton models the entire instantaneous forward curve directly. Once forward-rate volatility is specified, no-arbitrage determines the risk-neutral drift—preventing each maturity from being evolved independently.", points: ["The state is an infinite-dimensional curve, approximated by factors and a maturity grid.", "Volatility is the model input; drift is a no-arbitrage consequence under the chosen measure.", "Market models discretise tradable forwards and often change numeraires to simplify their dynamics."] },
    marketContext: { why: "HJM provides the organising theory for arbitrage-free curve evolution, while market models connect that theory to caps, swaptions and forward-rate simulation.", instruments: ["caps and floors", "European and Bermudan swaptions", "CMS products", "callable and path-dependent rates structures"], quoteConvention: "State forward definition, curve set, volatility coordinate, correlation/factor structure, probability measure, numeraire and rate-option quote convention." },
    mathematics: { notation: ["f(t,T): instantaneous forward", "\\sigma(t,T): forward volatility vector", "\\alpha(t,T): HJM drift", "P(t,T): zero-coupon bond price"], formulas: [
      { label: "HJM forward dynamics", latex: "df(t,T)=\\alpha(t,T)dt+\\sigma(t,T)\\cdot dW_t", interpretation: "Every maturity evolves with linked Brownian factors and a measure-dependent drift." },
      { label: "Risk-neutral HJM drift", latex: "\\alpha(t,T)=\\sigma(t,T)\\cdot\\int_t^T\\sigma(t,u)du", interpretation: "No-arbitrage fixes the drift once volatility is specified under the money-market numeraire." },
      { label: "Bond reconstruction", latex: "P(t,T)=\\exp\\left[-\\int_t^T f(t,u)du\\right]", interpretation: "The simulated forward curve must integrate to positive bond prices." },
    ] },
    derivation: { title: "Deriving the HJM drift from discounted bond martingales", introduction: "Start from the bond price implied by the forward curve, apply Itô calculus and require discounted tradable bond prices to have zero drift.", steps: [
      { title: "Represent the bond", body: "Write the log bond price as minus the integral of forwards from current time to maturity.", latex: "\\ln P(t,T)=-\\int_t^T f(t,u)du" },
      { title: "Differentiate the moving-boundary integral", body: "The time derivative contributes the short rate f(t,t), while forward drifts and volatilities integrate over maturity." },
      { title: "Apply Itô to the exponential", body: "Quadratic variation contributes half the squared integrated volatility to bond drift." },
      { title: "Discount by the money-market account", body: "Under Q, P(t,T)/B_t must be a martingale, so its drift after subtracting r_t is zero." },
      { title: "Solve the restriction", body: "Differentiate the resulting integrated relation in T to obtain α(t,T)=σ(t,T)·∫_t^Tσ(t,u)du.", check: "A zero volatility field must produce zero HJM drift and a deterministic roll of the initial curve." },
    ], conclusion: "HJM converts a chosen forward-volatility structure into an arbitrage-free drift; factorisation and discretisation make the curve model computational." },
    pricing: { method: "Choose a factor volatility/correlation representation, enforce the measure-consistent drift, discretise time and maturity, reconstruct bond prices and validate cap/swaption prices or scenario moments.", calibration: "Fit factor volatilities and correlations to a governed option basket, use dimension reduction where justified and test stability across grids and measures.", limitations: ["Naive maturity discretisation is high dimensional.", "Negative forwards remain possible in Gaussian specifications.", "Market-model lognormality, displacement and correlation are strong dynamic assumptions."] },
    pythonLab: { title: "Discrete one-factor HJM drift", objective: "Compute the no-arbitrage drift from a maturity-dependent volatility field.", code: `from __future__ import annotations\n\nimport numpy as np\n\ndef hjm_drift(maturity: np.ndarray, sigma: np.ndarray) -> np.ndarray:\n    if maturity.ndim != 1 or maturity.shape != sigma.shape or np.any(np.diff(maturity) <= 0):\n        raise ValueError("aligned increasing maturity grid required")\n    integral = np.zeros_like(sigma)\n    integral[1:] = np.cumsum(0.5 * (sigma[1:] + sigma[:-1]) * np.diff(maturity))\n    return sigma * integral\n\nT = np.linspace(0.0, 10.0, 101)\nsigma = 0.012 * np.exp(-0.15 * T)\nalpha = hjm_drift(T, sigma)\nassert alpha[0] == 0.0\nassert np.all(alpha >= 0.0)\nassert np.max(alpha) < 0.001\nprint(f"max HJM drift={np.max(alpha):.8f}")`, output: ["A non-negative one-factor HJM drift generated from the specified volatility field."], checks: ["Maturity grid is strictly increasing.", "Integral starts at current time with zero area.", "Zero volatility would imply zero drift."] },
    quantLib: "Use current upstream models and engines as implementation references for short-rate or market-model specialisations. Preserve numeraire, measure, tenor grid and correlation inputs explicitly; validate against bond and caplet invariants.", lab: { id: "hjm", title: "Forward-curve dynamics laboratory", description: "Change volatility decay, factors and policy shock; watch the initial curve evolve with its no-arbitrage drift." },
    frontOffice: { quote: "In HJM you choose volatility; the pricing measure chooses the drift. If both are freely fitted, arbitrage has entered the model.", inputs: ["initial multi-curve state", "forward-volatility factors", "correlation matrix", "measure/numeraire", "time and maturity grids"], calibration: "Fit to a defined liquid option basket, preserve positive-semidefinite correlation and validate prices plus scenario moments across discretisations.", risk: ["factor vega", "correlation", "discretisation", "measure/model basis"], workflow: ["freeze curves/options", "choose factors", "enforce drift", "calibrate and validate", "simulate exposures and hedge tests"], productionIssues: ["wrong measure drift", "non-PSD correlation", "grid-dependent calibration", "forward/bond reconstruction mismatch"] },
    macro: { title: "Whole-curve scenarios under macro shocks", thesis: "Macro shocks alter level, slope and volatility across maturities; an HJM factor model evolves those linked forward segments without violating bond-price no-arbitrage.", nodes: [{ label: "Macro factor shock", effect: "moves curve state and volatility" }, { label: "HJM factors", effect: "propagate across maturities" }, { label: "No-arbitrage drift", effect: "keeps bond dynamics consistent" }, { label: "Optionality / exposure", effect: "revalues path-dependent cash flows" }] },
    pitfalls: ["Simulating each forward maturity independently.", "Choosing both drift and volatility under Q without enforcing HJM.", "Ignoring numeraire when comparing model dynamics.", "Calibrating one grid and pricing on another without convergence tests."], relatedLessonIds: ["rate-hull-white", "rate-curve-risk", "vol-sabr"],
  },
];

export const additionalRatesLessons: AcademyLesson[] = seeds.map(({ quantLib, pythonLab, lab, frontOffice, macro, ...lesson }) => ({
  ...lesson,
  domain: "rates",
  assetClass: "IR",
  lastReviewed: reviewed,
  implementation: {
    architecture: ["Keep market conventions and quote lineage at the boundary.", "Solve curves and dynamics in framework-free deterministic kernels.", "Return residuals, state and sensitivities with every value.", "Test analytical limits, reconstruction identities and failure domains."],
    quantLib,
    pythonLab,
  },
  interactiveLabs: [lab],
  frontOffice,
  macroConnections: [macro],
  references,
}));

export const ratesAdvancedTrackNodes: AcademyTrackNode[] = [
  { id: "bootstrap", title: "Curve bootstrapping", stage: "Flagship construction workbench", level: "front-office", href: "/learn/rates/curve-bootstrapping", academyLessonId: "rate-curve-bootstrap" },
  { id: "interpolation", title: "Interpolation and arbitrage", stage: "Off-grid shape", level: "advanced", href: "/learn/rates/curve-interpolation", academyLessonId: "rate-interpolation" },
  { id: "multicurve", title: "Multi-curve and basis", stage: "Discount/projection separation", level: "front-office", href: "/learn/rates/multi-curve-framework", academyLessonId: "rate-multicurve" },
  { id: "risk", title: "Curve risk and roll", stage: "DV01, carry and scenarios", level: "front-office", href: "/learn/rates/curve-risk", academyLessonId: "rate-curve-risk" },
  { id: "hull-white", title: "Hull–White", stage: "Mean-reverting short rate", level: "advanced", href: "/learn/rates/hull-white", academyLessonId: "rate-hull-white" },
  { id: "hjm", title: "HJM and market models", stage: "Arbitrage-free curve dynamics", level: "front-office", href: "/learn/rates/hjm-and-market-models", academyLessonId: "rate-hjm" },
];
