import type { AcademyFormula, AcademyFormulaDepth, AcademyLesson, AcademyReference } from "./types";

const reviewed = "2026-08-12";

const references: AcademyReference[] = [
  { sourceId: "grzelak-computational-finance", locator: "Volatility, Monte Carlo and stochastic-volatility lectures", url: "https://github.com/LechGrzelak/Computational-Finance-Course", note: "Research map for the mathematical progression and numerical experiments; prose, examples and code are original." },
  { sourceId: "quantlib-upstream", locator: "Current volatility structures, processes, calibration helpers and tests", url: "https://github.com/lballabio/QuantLib", note: "Implementation reference for production abstractions and validation patterns." },
];

type LessonSeed = {
  id: string;
  slug: string;
  title: string;
  subtitle: string;
  level: AcademyLesson["level"];
  minutes: number;
  legacyRoutes: string[];
  prerequisites: string[];
  objectives: string[];
  tags: string[];
  lead: string;
  points: string[];
  why: string;
  instruments: string[];
  quote: string;
  notation: string[];
  formulas: Array<Omit<AcademyFormula, "depth" | "analyticsHref">>;
  derivationTitle: string;
  derivationIntro: string;
  steps: AcademyLesson["derivation"]["steps"];
  conclusion: string;
  method: string;
  calibration: string;
  limitations: string[];
  python: { title: string; objective: string; code: string; output: string[]; checks: string[] };
  lab: AcademyLesson["interactiveLabs"][number];
  deskQuote: string;
  inputs: string[];
  risk: string[];
  workflow: string[];
  productionIssues: string[];
  macro: AcademyLesson["macroConnections"][number];
  pitfalls: string[];
  related: string[];
};

type FormulaContract = {
  formulaDepths: AcademyFormulaDepth[];
  formulaAnalyticsHrefs?: Array<string | undefined>;
  derivationFormulaIndex: number;
  derivationDepth: 2 | 3;
};

const formulaContracts: Record<string, FormulaContract> = {
  "vol-realized": { formulaDepths: [2, 2, 1], derivationFormulaIndex: 0, derivationDepth: 2 },
  "vol-realized-implied": { formulaDepths: [3, 1], formulaAnalyticsHrefs: ["/analytics/volatility", "/analytics/volatility"], derivationFormulaIndex: 0, derivationDepth: 3 },
  "vol-smile": { formulaDepths: [1, 3, 1], formulaAnalyticsHrefs: ["/analytics/volatility", "/analytics/volatility", "/analytics/volatility"], derivationFormulaIndex: 1, derivationDepth: 3 },
  "vol-term": { formulaDepths: [1, 2, 1], formulaAnalyticsHrefs: ["/analytics/volatility", "/analytics/volatility", "/analytics/volatility"], derivationFormulaIndex: 1, derivationDepth: 2 },
  "vol-local": { formulaDepths: [3, 3, 1], formulaAnalyticsHrefs: ["/analytics/volatility", "/analytics/volatility", "/analytics/volatility"], derivationFormulaIndex: 1, derivationDepth: 3 },
  "vol-stochastic": { formulaDepths: [3, 1, 2], formulaAnalyticsHrefs: ["/analytics/volatility", "/analytics/volatility", "/analytics/volatility"], derivationFormulaIndex: 2, derivationDepth: 2 },
  "vol-sabr": { formulaDepths: [3, 1, 3], formulaAnalyticsHrefs: ["/analytics/volatility", "/analytics/volatility", "/analytics/volatility"], derivationFormulaIndex: 2, derivationDepth: 3 },
  "vol-calibration": { formulaDepths: [3, 3, 2], formulaAnalyticsHrefs: ["/analytics/volatility", "/analytics/volatility", "/analytics/volatility"], derivationFormulaIndex: 1, derivationDepth: 3 },
  "vol-higher-risk": { formulaDepths: [1, 2, 2], formulaAnalyticsHrefs: ["/lab?lab=greeks", "/lab?lab=greeks", "/lab?lab=greeks"], derivationFormulaIndex: 1, derivationDepth: 2 },
};

const seeds: LessonSeed[] = [
  {
    id: "vol-realized", slug: "realized-volatility", title: "Realized volatility", subtitle: "Measuring path dispersion without confusing an estimator for an observable truth", level: "foundation", minutes: 52,
    legacyRoutes: ["/learn/equity/realized-volatility", "/learn/equity/historical-volatility"], prerequisites: ["Log returns", "Sample variance", "Time scaling"],
    objectives: ["Compute close-to-close and range-based realized-volatility estimators with explicit units.", "Derive annualization from return variance rather than memorizing a square-root rule.", "Diagnose window, sampling, jump and microstructure effects.", "Interpret a rolling estimate as a backward-looking state variable, not a forecast."],
    tags: ["realized volatility", "estimators", "annualization", "rolling window", "EWMA"],
    lead: "Realized volatility is an estimate extracted from a finite price path. The sampling clock, return definition, window and treatment of jumps are part of the number—not implementation details.",
    points: ["Prices are observed; volatility is estimated from returns.", "Variance aggregates across independent increments; volatility inherits square-root time scaling only under stated assumptions.", "Range estimators use intraday extremes efficiently but impose stronger path assumptions."],
    why: "Risk limits, variance-swap marks, volatility targeting and model validation all need an ex-post measure of dispersion that can be reproduced from a fixed dataset.",
    instruments: ["cash equities and indices", "futures", "variance swaps", "volatility-controlled portfolios"], quote: "This lesson reports annualized decimal volatility from log returns and an ACT/365-like clock. A displayed 20% means 0.20 in calculations.",
    notation: ["r_t = ln(S_t/S_{t-1}): log return", "n: observations in the window", "A: observations per year", "λ: EWMA decay"],
    formulas: [
      { label: "Close-to-close estimator", latex: "\\widehat{\\sigma}_{cc}=\\sqrt{A\\,\\frac{1}{n-1}\\sum_{t=1}^{n}(r_t-\\bar r)^2}", interpretation: "Annualized sample standard deviation of equally spaced log returns." },
      { label: "Parkinson range estimator", latex: "\\widehat{\\sigma}_{P}^{2}=\\frac{A}{4n\\ln 2}\\sum_{t=1}^{n}\\left[\\ln(H_t/L_t)\\right]^2", interpretation: "Uses the intraday high-low range and is efficient under a continuous driftless diffusion, but misses overnight jumps." },
      { label: "EWMA variance", latex: "\\widehat{\\sigma}_{t}^{2}=\\lambda\\widehat{\\sigma}_{t-1}^{2}+(1-\\lambda)r_t^2", interpretation: "A recursive state with geometrically decaying memory; the decay factor determines responsiveness." },
    ],
    derivationTitle: "From quadratic return variation to an annualized quote", derivationIntro: "The square-root rule follows from a variance model; it is not a universal unit conversion.",
    steps: [
      { title: "Define the return clock", body: "Choose close-to-close log returns at a fixed sampling interval and preserve timezone, corporate-action and missing-observation rules.", latex: "r_t=\\ln S_t-\\ln S_{t-1}" },
      { title: "Estimate one-period variance", body: "Center the sample when estimating unconditional variance. For a zero-mean high-frequency model, realized variance often uses the uncentered sum.", latex: "s_r^2=\\frac{1}{n-1}\\sum(r_t-\\bar r)^2" },
      { title: "Derive time aggregation", body: "If equal-period returns are uncorrelated with common variance, the variance of their sum is the sum of variances.", latex: "\\operatorname{Var}(\\sum_{i=1}^{A}r_i)=A\\operatorname{Var}(r)" },
      { title: "Convert variance to volatility", body: "Taking the positive square root produces annualized volatility.", latex: "\\sigma_{ann}=\\sqrt{A}\\,s_r", check: "Autocorrelation, stochastic sampling and jumps change the assumptions behind this scaling." },
      { title: "Choose an estimator for the data", body: "OHLC estimators can reduce sampling noise, while EWMA deliberately weights recent shocks more heavily. Compare estimators rather than silently switching definitions." },
    ], conclusion: "A realized-volatility number is auditable only when its return clock, estimator, window, annualization and data cleaning are attached.",
    method: "Compute several estimators over the same clean path, report their definitions, and examine sensitivity to sampling and window length.", calibration: "There is no option calibration. Select λ or window length through a documented forecasting or risk objective and validate out of sample.", limitations: ["Backward-looking and regime dependent.", "Sensitive to jumps, market closure and microstructure noise.", "Square-root scaling can fail under autocorrelation or non-stationarity."],
    python: { title: "Auditable realized-volatility estimators", objective: "Compute close-to-close, Parkinson and EWMA estimates from a deterministic price path.", code: `from __future__ import annotations\n\nimport numpy as np\n\ndef realized_vol(close: np.ndarray, periods: int = 252) -> float:\n    if close.ndim != 1 or close.size < 3 or np.any(close <= 0):\n        raise ValueError("close must contain at least three positive prices")\n    returns = np.diff(np.log(close))\n    return float(np.std(returns, ddof=1) * np.sqrt(periods))\n\ndef parkinson(high: np.ndarray, low: np.ndarray, periods: int = 252) -> float:\n    if high.shape != low.shape or np.any(high < low) or np.any(low <= 0):\n        raise ValueError("invalid high-low path")\n    variance = np.mean(np.log(high / low) ** 2) / (4.0 * np.log(2.0))\n    return float(np.sqrt(periods * variance))\n\nclose = np.array([100.0, 101.2, 99.8, 102.1, 101.4, 103.0])\nhigh = close[1:] * 1.008\nlow = close[1:] * 0.992\nsigma_cc = realized_vol(close)\nsigma_p = parkinson(high, low)\nassert np.isfinite([sigma_cc, sigma_p]).all()\nassert sigma_cc > 0.0 and sigma_p > 0.0\nprint(f"CC {sigma_cc:.2%} | Parkinson {sigma_p:.2%}")`, output: ["Deterministic annualized close-to-close and Parkinson estimates."], checks: ["Positive prices and ordered ranges are validated.", "Sample standard deviation uses ddof=1.", "Annualization is explicit." ] },
    lab: { id: "realized-volatility", title: "Estimator and regime lab", description: "Change estimator, window and scenario; inspect the path, rolling estimate and annualization together." }, deskQuote: "The window is a position: it determines which regime you are carrying into the number.",
    inputs: ["adjusted OHLC path", "sampling clock", "window", "annualization basis", "jump and missing-data policy"], risk: ["estimator risk", "regime lag", "jump sensitivity", "sampling bias"], workflow: ["freeze path", "clean events", "compute estimators", "compare windows", "flag breaks"], productionIssues: ["unadjusted splits", "mixed timezones", "overnight gaps omitted", "percent/decimal mismatch"],
    macro: { title: "Realized volatility as a regime recorder", thesis: "Macro shocks enter the observed path through jumps, clustered returns and changing correlations; the window controls how long that regime remains visible.", nodes: [{ label: "Policy or growth shock", effect: "moves prices and correlations" }, { label: "Return path", effect: "records jumps and clustering" }, { label: "Estimator", effect: "weights and annualizes the path" }, { label: "Risk state", effect: "feeds limits and forecasts" }] },
    pitfalls: ["Calling the estimate observable volatility.", "Annualizing without stating the return interval.", "Comparing OHLC and close-only estimators as if assumptions were identical.", "Treating a rolling window as forward-looking."], related: ["vol-realized-implied", "vol-implied"],
  },
  {
    id: "vol-realized-implied", slug: "realized-vs-implied", title: "Realized versus implied volatility", subtitle: "Separating a backward-looking path estimate from a forward option-price coordinate", level: "foundation", minutes: 46,
    legacyRoutes: ["/learn/equity/realized-vs-implied-volatility"], prerequisites: ["Realized volatility", "Option premium", "Risk-neutral expectation"],
    objectives: ["Distinguish physical-path estimation from risk-neutral option pricing.", "Define the variance risk premium with sign and horizon conventions.", "Explain why implied volatility need not equal expected realized volatility.", "Build a horizon-matched comparison without look-ahead bias."], tags: ["variance risk premium", "implied volatility", "realized volatility", "risk-neutral measure"],
    lead: "Realized and implied volatility answer different questions. One summarizes a path under the physical measure; the other translates an option price under a model and embeds risk premia, convexity and supply-demand effects.", points: ["Match horizon before comparing the two numbers.", "The spread is not a pure forecast error.", "Variance is the cleaner additive object for risk-premium analysis."],
    why: "The realized-implied relationship drives volatility carry, variance-swap analysis, option relative value and model backtesting.", instruments: ["listed options", "variance swaps", "VIX-style indices", "delta-hedged option strategies"], quote: "Compare annualized total variance over the same future window. State whether VRP means implied minus expected realized or the reverse.",
    notation: ["IV_t(T): option-implied volatility", "RV_{t,t+T}: subsequent realized volatility", "w=σ²T: total variance", "P and Q: physical and risk-neutral measures"],
    formulas: [
      { label: "Variance risk premium convention", latex: "\\operatorname{VRP}_t(T)=\\mathbb E_t^{\\mathbb Q}[RV_{t,t+T}^{2}]-\\mathbb E_t^{\\mathbb P}[RV_{t,t+T}^{2}]", interpretation: "A positive number under this convention compensates sellers of variance risk." },
      { label: "Ex-post variance spread", latex: "\\widehat{VRP}_{t,T}=IV_t^2(T)-RV_{t,t+T}^2", interpretation: "A realized outcome useful for backtests, not the ex-ante expected premium itself." },
    ], derivationTitle: "From option value to a variance premium", derivationIntro: "The two measures differ because pricing weights states by marginal utility and hedging demand, not historical frequency alone.",
    steps: [
      { title: "Fix a future window", body: "Pair today’s implied quote with realized variance accumulated over exactly the option’s remaining horizon.", latex: "[t,t+T]" },
      { title: "Express both sides in variance", body: "Total variance is time-additive under idealized partitioning and avoids comparing square roots prematurely.", latex: "w_t(T)=IV_t^2(T)T" },
      { title: "Separate probability measures", body: "Physical expectation describes future outcomes; risk-neutral expectation prices hedgeable cash flows after discounting.", latex: "\\mathbb E^{\\mathbb P}[RV^2]\\ne\\mathbb E^{\\mathbb Q}[RV^2]" },
      { title: "Define the premium", body: "Subtract the physical expected variance from its risk-neutral counterpart and keep the sign convention attached.", latex: "VRP=E^{Q}[RV^2]-E^{P}[RV^2]" },
      { title: "Backtest without leakage", body: "Use only information available at the option timestamp, preserve bid/offer and roll the realized window forward." },
    ], conclusion: "Implied-minus-realized is a priced risk spread plus forecast error and implementation effects—not a free return statistic.", method: "Construct constant-maturity implied variance and pair it with non-overlapping or carefully adjusted subsequent realized windows.", calibration: "Estimate the physical expectation with a documented forecast; infer risk-neutral variance from option prices or a model-consistent index.", limitations: ["Overlapping windows induce serial dependence.", "Implied volatility is strike dependent.", "Transaction costs and tail losses dominate simple carry stories."],
    python: { title: "Horizon-matched variance spread", objective: "Compute ex-post variance spreads without mixing volatility and variance units.", code: `from __future__ import annotations\n\nimport numpy as np\n\ndef variance_spread(implied_vol: np.ndarray, realized_vol: np.ndarray) -> np.ndarray:\n    if implied_vol.shape != realized_vol.shape or np.any(implied_vol < 0) or np.any(realized_vol < 0):\n        raise ValueError("volatility arrays must align and be non-negative")\n    return implied_vol**2 - realized_vol**2\n\niv = np.array([0.20, 0.24, 0.31])\nrv = np.array([0.17, 0.28, 0.25])\nspread = variance_spread(iv, rv)\nassert np.allclose(spread, np.array([0.0111, -0.0208, 0.0336]))\nprint(np.round(spread * 10_000, 1))`, output: ["[111.0, -208.0, 336.0] variance-basis points."], checks: ["Arrays share horizons.", "Inputs are decimal volatilities.", "Subtraction occurs in variance units."] },
    lab: { id: "variance-risk-premium", title: "Volatility carry laboratory", description: "Shock implied level and subsequent regimes; compare variance spread, carry and tail outcomes." }, deskQuote: "Short volatility earns a premium until the distribution collects it back.", inputs: ["constant-maturity IV", "realized estimator", "bid/offer", "roll convention", "transaction costs"], risk: ["gap risk", "short convexity", "skew carry", "roll-down"], workflow: ["align horizons", "normalize variance", "estimate carry", "stress tails", "attribute outcome"], productionIssues: ["look-ahead leakage", "overlapping samples", "mid-only returns", "unmatched maturities"],
    macro: { title: "Insurance demand and the variance premium", thesis: "Risk aversion and demand for crash protection can keep risk-neutral tail variance above the physical expectation.", nodes: [{ label: "Macro uncertainty", effect: "raises protection demand" }, { label: "Option premium", effect: "embeds state prices" }, { label: "Implied variance", effect: "moves above physical expectation" }, { label: "Volatility carry", effect: "compensates tail exposure" }] }, pitfalls: ["Calling IV the market’s unbiased forecast.", "Subtracting volatilities instead of comparing variance.", "Ignoring skew and maturity.", "Backtesting with overlapping observations without robust inference."], related: ["vol-realized", "vol-implied", "vol-surface"],
  },
  {
    id: "vol-smile", slug: "smile-and-skew", title: "Volatility smile and skew", subtitle: "Reading strike-dependent option prices as distributional shape", level: "intermediate", minutes: 55,
    legacyRoutes: ["/learn/equity/volatility-smile"], prerequisites: ["Implied volatility", "Forward moneyness", "Digital options"], objectives: ["Transform strikes into forward log-moneyness.", "Relate skew and curvature to risk-neutral distribution shape.", "Distinguish sticky-strike and sticky-delta dynamics.", "Check strike slices for monotonicity and convexity."], tags: ["smile", "skew", "risk-neutral density", "moneyness", "wing"],
    lead: "A smile is the strike slice of a surface at one expiry. Its slope and curvature summarize relative option premiums, but only option-price derivatives—not a visual curve—determine arbitrage consistency.", points: ["Equity index skew is often downside-heavy rather than symmetric.", "Forward log-moneyness removes much of the carry distortion.", "A static fit and a rule for how the smile moves are different model claims."], why: "Smile shape drives relative-value trades, barrier exposure, delta conventions and every model calibrated beyond ATM.", instruments: ["puts and calls by strike", "risk reversals", "butterflies", "digitals and barriers"], quote: "Use k=ln(K/F_T) unless a market-native delta convention is required. State premium inclusion, forward and option type.", notation: ["k=ln(K/F_T): forward log-moneyness", "w(k,T)=σ²T: total variance", "∂K C: digital information", "∂KK C: density information"],
    formulas: [
      { label: "Smile slope", latex: "\\operatorname{Skew}(T)=\\left.\\partial_k\\sigma_{imp}(k,T)\\right|_{k=0}", interpretation: "Local ATM slope in log-forward-moneyness coordinates." },
      { label: "Breeden–Litzenberger density", latex: "f_{S_T}^{Q}(K)=D(0,T)^{-1}\\partial_{KK}C(K,T)", interpretation: "Convex call prices imply a non-negative terminal density." },
      { label: "Wing convexity", latex: "\\partial_{KK}C(K,T)\\ge 0", interpretation: "The fundamental butterfly-arbitrage requirement lives in price space." },
    ], derivationTitle: "From strike prices to a terminal density", derivationIntro: "Differentiate a continuum of call payoffs with respect to strike.", steps: [
      { title: "Write the call as an integral", body: "A discounted call is the integral of terminal payoff against the risk-neutral density.", latex: "C(K)=D\\int_K^\\infty(s-K)f(s)ds" },
      { title: "Differentiate once", body: "The first strike derivative is minus the discounted tail probability.", latex: "\\partial_K C=-D\\,Q(S_T>K)" },
      { title: "Differentiate twice", body: "The second derivative recovers discounted density.", latex: "\\partial_{KK}C=Df(K)" },
      { title: "Translate prices to implied vol", body: "Inverting each premium through Black–Scholes produces the displayed smile; arbitrage checks must still be performed on reconstructed prices." },
      { title: "Specify smile dynamics", body: "Sticky-strike, sticky-delta, local-vol and stochastic-vol rules imply different P&L when spot moves.", check: "Never infer dynamics from one static slice." },
    ], conclusion: "The smile is a quote coordinate for relative option prices; convex prices and explicit dynamics determine whether it is usable.", method: "Clean one expiry, convert to forward moneyness, fit total variance or prices with shape constraints, and validate reconstructed premiums.", calibration: "Weight liquid nodes by spread or vega, constrain wings, and separate interpolation from extrapolation.", limitations: ["Sparse wings are weakly identified.", "Implied-vol smoothness does not guarantee price convexity.", "A single expiry says nothing about calendar arbitrage."],
    python: { title: "Finite-difference density check", objective: "Recover a non-negative density proxy from a convex call-price slice.", code: `from __future__ import annotations\n\nimport numpy as np\n\ndef density_proxy(strikes: np.ndarray, calls: np.ndarray, discount: float) -> np.ndarray:\n    if strikes.ndim != 1 or calls.shape != strikes.shape or not np.allclose(np.diff(strikes), np.diff(strikes)[0]):\n        raise ValueError("use an aligned uniform strike grid")\n    h = strikes[1] - strikes[0]\n    density = (calls[:-2] - 2.0 * calls[1:-1] + calls[2:]) / (h * h * discount)\n    return density\n\nk = np.arange(80.0, 125.0, 5.0)\nc = np.array([22.0, 18.0, 14.5, 11.5, 9.0, 7.0, 5.5, 4.5, 3.8])\nf = density_proxy(k, c, 0.98)\nassert np.isfinite(f).all() and np.all(f >= -1e-12)\nprint(np.round(f, 5))`, output: ["A non-negative interior density proxy for the teaching slice."], checks: ["Strike spacing is uniform.", "Convexity is checked in price space.", "Discounting is explicit."] },
    lab: { id: "smile-skew", title: "Smile geometry lab", description: "Move spot, skew and curvature; inspect the smile, risk-neutral density proxy and arbitrage flags." }, deskQuote: "A wing quote is cheap until the extrapolator makes it expensive.", inputs: ["forward", "strike premiums", "discount factors", "spread weights", "wing rules"], risk: ["skew delta", "wing vega", "digital risk", "smile dynamics"], workflow: ["normalize strikes", "invert premiums", "fit slice", "reprice", "check convexity"], productionIssues: ["stale forward", "mixed call/put sides", "unconstrained splines", "unstable wing extrapolation"], macro: { title: "Downside skew and crash insurance", thesis: "Leverage, jump risk and demand for protection concentrate risk-neutral mass in the downside tail.", nodes: [{ label: "Risk-off demand", effect: "raises put premiums" }, { label: "Downside skew", effect: "steepens left wing" }, { label: "Density", effect: "reprices tail states" }, { label: "Hedge", effect: "creates spot-vol cross risk" }] }, pitfalls: ["Treating a smooth line as arbitrage-free.", "Comparing raw strikes across expiries.", "Using mid quotes in illiquid wings without uncertainty bands.", "Assuming sticky strike by default."], related: ["vol-implied", "vol-term", "vol-surface"],
  },
  {
    id: "vol-term", slug: "term-structure", title: "Volatility term structure", subtitle: "Locating uncertainty, events and mean reversion along the expiry axis", level: "intermediate", minutes: 48,
    legacyRoutes: ["/learn/equity/term-structure"], prerequisites: ["Implied volatility", "Total variance", "Forward variance"], objectives: ["Convert implied volatility into total variance.", "Derive forward variance between two maturities.", "Recognize event bumps and term inversion.", "Test a term slice for calendar consistency."], tags: ["term structure", "forward variance", "calendar arbitrage", "event volatility"],
    lead: "A term structure shows where the option market locates uncertainty in time. Volatility levels are not additive; total variance is the object that carries across adjacent horizons.", points: ["A flat volatility curve still implies increasing total variance.", "Scheduled events create localized variance increments.", "Negative forward variance signals inconsistent inputs or interpolation."], why: "Term structure controls calendar spreads, event trades, variance forwards and the maturity dimension of every surface.", instruments: ["calendar spreads", "variance swaps", "forward-start options", "earnings and event options"], quote: "This lesson uses annualized implied volatility and total variance w(T)=σ²(T)T. Expiries use a consistent ACT/365-like year fraction.", notation: ["w(T)=σ²(T)T: total variance", "ξ(T1,T2): forward variance", "T1<T2: maturity interval", "ΔT=T2-T1"],
    formulas: [
      { label: "Total variance", latex: "w(T)=\\sigma_{imp}^2(T)T", interpretation: "Variance accumulated to maturity in the chosen strike or delta slice." },
      { label: "Forward variance", latex: "\\xi(T_1,T_2)=\\frac{w(T_2)-w(T_1)}{T_2-T_1}", interpretation: "Average variance priced for the forward interval." },
      { label: "Calendar condition", latex: "w(k,T_2)\\ge w(k,T_1)\\quad\\text{for }T_2>T_1", interpretation: "A practical fixed-coordinate condition used to detect negative forward variance." },
    ], derivationTitle: "Extracting a forward variance interval", derivationIntro: "Assume integrated variance adds over non-overlapping time intervals.", steps: [
      { title: "Express each maturity in total variance", body: "Convert annualized volatility quotes before taking differences.", latex: "w_i=\\sigma_i^2T_i" },
      { title: "Partition integrated variance", body: "Cumulative variance to T2 equals cumulative variance to T1 plus the forward interval.", latex: "w(T_2)=w(T_1)+\\xi(T_1,T_2)(T_2-T_1)" },
      { title: "Solve for the forward rate", body: "Rearrange the partition identity.", latex: "\\xi=\\frac{w_2-w_1}{T_2-T_1}" },
      { title: "Require non-negative increments", body: "A negative forward interval is economically and numerically suspect for a diffusion-style variance representation.", latex: "w_2-w_1\\ge0" },
      { title: "Interpret event bumps", body: "A discrete event variance can be added to baseline integrated variance, causing short maturities spanning the event to look elevated." },
    ], conclusion: "Term structure becomes coherent when represented as cumulative and forward variance, with the maturity clock and coordinate held fixed.", method: "Fit monotone total variance through liquid expiries, preserve event knots, and extract forward intervals for interpretation.", calibration: "Use spreads and liquidity weights; do not smooth away scheduled events or force a parametric curve that creates negative increments.", limitations: ["Fixed-strike and fixed-delta slices differ as forward moves.", "Sparse long maturities require extrapolation.", "Event variance is not directly observable."],
    python: { title: "Forward variance extraction", objective: "Convert a volatility term structure into non-negative forward intervals.", code: `from __future__ import annotations\n\nimport numpy as np\n\ndef forward_variances(times: np.ndarray, vols: np.ndarray) -> np.ndarray:\n    if times.shape != vols.shape or np.any(np.diff(times) <= 0) or np.any(vols < 0):\n        raise ValueError("times must increase and vols must be non-negative")\n    total = vols**2 * times\n    forwards = np.diff(total) / np.diff(times)\n    if np.any(forwards < -1e-12):\n        raise ValueError("negative forward variance")\n    return forwards\n\nt = np.array([30, 90, 180, 365]) / 365.0\nvol = np.array([0.28, 0.24, 0.225, 0.22])\nfwd = forward_variances(t, vol)\nassert np.isfinite(fwd).all() and np.all(fwd >= 0.0)\nprint(np.round(np.sqrt(fwd), 4))`, output: ["Forward interval volatilities derived from total variance."], checks: ["Maturities strictly increase.", "Inputs are decimal vols.", "Forward variance cannot be materially negative."] },
    lab: { id: "term-structure", title: "Forward-variance lab", description: "Add an event bump or invert the front end; inspect total and forward variance by interval." }, deskQuote: "The front expiry is not high; it contains a different piece of time.", inputs: ["expiry timestamps", "forward coordinate", "ATM/slice vols", "event calendar", "spread weights"], risk: ["calendar vega", "event variance", "roll-down", "forward-vol exposure"], workflow: ["normalize expiries", "convert total variance", "fit monotone curve", "extract forwards", "stress events"], productionIssues: ["day-count mismatch", "event timestamp error", "negative forwards", "over-smoothed knots"], macro: { title: "Events redistribute variance through time", thesis: "Policy decisions, elections and earnings concentrate uncertainty in intervals rather than lifting every maturity equally.", nodes: [{ label: "Scheduled catalyst", effect: "localizes uncertainty" }, { label: "Total variance", effect: "adds an event increment" }, { label: "Term curve", effect: "forms a bump or inversion" }, { label: "Calendar trade", effect: "isolates the interval" }] }, pitfalls: ["Subtracting volatilities to obtain forward volatility.", "Comparing expiries with inconsistent clocks.", "Smoothing through known events.", "Calling an inverted volatility curve arbitrage by itself without inspecting total variance."], related: ["vol-smile", "vol-surface", "vol-realized-implied"],
  },
  {
    id: "vol-local", slug: "local-volatility", title: "Local volatility", subtitle: "An arbitrage-consistent diffusion fitted to today’s vanilla surface", level: "advanced", minutes: 68,
    legacyRoutes: ["/learn/equity/local-volatility"], prerequisites: ["Volatility surface", "Fokker–Planck equation", "Finite differences"], objectives: ["Derive Dupire local variance from the forward equation.", "Explain why call-price derivatives demand smoothing.", "Contrast exact static fit with forward smile dynamics.", "Design stable interpolation and boundary checks."], tags: ["local volatility", "Dupire", "PDE", "density", "surface derivatives"],
    lead: "Local volatility replaces one constant σ with a deterministic function σloc(S,t). Given a smooth arbitrage-consistent vanilla surface, Dupire identifies a diffusion that matches all European marginal distributions in ideal theory.", points: ["Exact vanilla fit is a static statement.", "Differentiation amplifies quote noise.", "Forward smile dynamics can be less realistic than the initial fit."], why: "Local volatility is a baseline for barrier and path-dependent pricing and a building block for local-stochastic volatility models.", instruments: ["barriers", "digitals", "autocallables", "local-stochastic-volatility hybrids"], quote: "Surface inputs must share forward, discount, dividend, expiry and strike conventions. Local variance is annualized decimal variance.", notation: ["σloc(S,t): local volatility", "C(K,T): call surface", "D(0,T): discount factor", "∂KKC: density term"],
    formulas: [
      { label: "Local-vol diffusion", latex: "dS_t=(r-q)S_tdt+\\sigma_{loc}(S_t,t)S_tdW_t", interpretation: "Volatility is deterministic conditional on current spot and time." },
      { label: "Dupire formula", latex: "\\sigma_{loc}^2(K,T)=\\frac{\\partial_TC+(r-q)K\\partial_KC+qC}{\\tfrac12K^2\\partial_{KK}C}", interpretation: "The call surface determines local variance where derivatives and density are well behaved." },
      { label: "Density requirement", latex: "\\partial_{KK}C(K,T)>0", interpretation: "A small or negative denominator makes inversion unstable or invalid." },
    ], derivationTitle: "Inverting the forward equation", derivationIntro: "Match the Fokker–Planck evolution of the local-vol diffusion to strike derivatives of call prices.", steps: [
      { title: "Start with the diffusion", body: "Specify risk-neutral drift and a state-time diffusion coefficient.", latex: "dS=(r-q)Sdt+\\sigma_{loc}(S,t)SdW" },
      { title: "Write density evolution", body: "The forward Kolmogorov equation evolves terminal density under the diffusion." },
      { title: "Connect density to calls", body: "Use Breeden–Litzenberger to replace terminal density by the second strike derivative of call prices.", latex: "\\partial_{KK}C=Df(K,T)" },
      { title: "Differentiate through maturity", body: "Differentiate the discounted payoff expectation in T and substitute the density evolution." },
      { title: "Isolate local variance", body: "Rearrange the forward PDE to obtain Dupire’s numerator over the convexity denominator.", check: "Smooth prices or total variance before differentiating; raw finite differences are unstable." },
    ], conclusion: "Dupire converts a full static surface into one diffusion, but the inversion is only as reliable as surface cleaning, smoothing and boundary treatment.", method: "Build an arbitrage-controlled call-price surface, compute stable derivatives, floor diagnostics rather than values, and solve PDEs with consistent boundaries.", calibration: "The model is implied from the vanilla surface rather than optimized to it; smoothing hyperparameters are the effective calibration choices.", limitations: ["Noise amplification in derivatives.", "Unrealistic forward smile dynamics can mis-hedge exotics.", "Boundary extrapolation materially changes local vol."],
    python: { title: "Dupire denominator diagnostic", objective: "Detect unstable density denominators before computing local variance.", code: `from __future__ import annotations\n\nimport numpy as np\n\ndef convexity(strikes: np.ndarray, calls: np.ndarray) -> np.ndarray:\n    if strikes.shape != calls.shape or strikes.size < 5:\n        raise ValueError("aligned grid with at least five nodes required")\n    h = np.diff(strikes)\n    if not np.allclose(h, h[0]):\n        raise ValueError("teaching implementation requires uniform strikes")\n    return (calls[:-2] - 2.0 * calls[1:-1] + calls[2:]) / h[0]**2\n\nk = np.arange(80.0, 125.0, 5.0)\nc = np.array([22.0, 18.0, 14.5, 11.5, 9.0, 7.0, 5.5, 4.5, 3.8])\ndensity_term = convexity(k, c)\nassert np.isfinite(density_term).all()\nassert np.all(density_term > 0.0)\nprint(float(density_term.min()))`, output: ["Positive minimum strike convexity for the teaching slice."], checks: ["Convexity is positive.", "Grid assumptions are validated.", "No denominator flooring hides an arbitrage failure."] },
    lab: { id: "local-volatility", title: "Dupire stability lab", description: "Change smoothing and grid spacing; inspect call convexity, local variance and failure regions." }, deskQuote: "The calibration is exact because the interpolation made the difficult decisions first.", inputs: ["clean call surface", "curves and forwards", "smoothing rule", "grid", "boundaries"], risk: ["local-vol vega", "barrier sensitivity", "surface derivative risk", "grid risk"], workflow: ["clean prices", "enforce shape", "differentiate", "diagnose denominator", "solve PDE"], productionIssues: ["negative density", "noisy time derivative", "wing explosion", "boundary artifacts"], macro: { title: "Spot moves through a state-dependent surface", thesis: "A local-vol model maps today’s skew into spot-dependent future diffusion, linking selloffs to higher instantaneous volatility without an independent variance shock.", nodes: [{ label: "Current skew", effect: "defines state dependence" }, { label: "Spot selloff", effect: "moves into higher local vol" }, { label: "Path distribution", effect: "changes barrier probabilities" }, { label: "Exotic hedge", effect: "inherits local dynamics" }] }, pitfalls: ["Differentiating raw implied vols.", "Calling exact vanilla fit a validation of dynamics.", "Flooring negative local variance silently.", "Ignoring extrapolation in path-dependent pricing."], related: ["vol-surface", "vol-stochastic", "vol-heston"],
  },
  {
    id: "vol-stochastic", slug: "stochastic-volatility", title: "Stochastic volatility", subtitle: "Adding an explicit random variance state and the dynamics a static surface cannot supply", level: "advanced", minutes: 64,
    legacyRoutes: ["/learn/equity/stochastic-volatility"], prerequisites: ["Itô calculus", "Volatility surface", "Monte Carlo schemes"], objectives: ["Separate spot and variance state dynamics.", "Explain leverage correlation and vol-of-vol.", "Derive the first moments of mean-reverting variance.", "Identify simulation and calibration risks."], tags: ["stochastic volatility", "variance process", "leverage", "vol of vol", "mean reversion"],
    lead: "Stochastic-volatility models make variance a random state. Correlation between spot and variance innovations creates skew dynamics; mean reversion and vol-of-vol shape the term structure and distribution of future variance.", points: ["Variance becomes a hedge factor rather than a deterministic surface lookup.", "Negative spot-variance correlation produces leverage-style downside skew.", "The discretization scheme is part of the implemented model."], why: "Stochastic volatility improves forward smile dynamics and prices payoffs exposed to variance path and convexity.", instruments: ["forward-start options", "cliquets", "barriers", "variance and volatility derivatives"], quote: "Parameters are model states or risk-neutral dynamics, not directly observed market quotes. State whether calibration is in premium or implied-vol space.", notation: ["v_t: instantaneous variance", "κ: mean-reversion speed", "θ: long-run variance", "η: vol of variance", "ρ: spot-variance correlation"],
    formulas: [
      { label: "Generic variance dynamics", latex: "dv_t=\\kappa(\\theta-v_t)dt+\\eta g(v_t)dW_t^v", interpretation: "Mean reversion plus state-dependent variance diffusion." },
      { label: "Leverage channel", latex: "d\\langle W^S,W^v\\rangle_t=\\rho\\,dt", interpretation: "Correlation transmits spot shocks into the variance state." },
      { label: "Conditional mean", latex: "\\mathbb E_t[v_{t+\\tau}]=\\theta+(v_t-\\theta)e^{-\\kappa\\tau}", interpretation: "Variance shocks decay toward the long-run level at speed κ." },
    ], derivationTitle: "The mean-reverting variance state", derivationIntro: "Take conditional expectation of the variance SDE; the martingale diffusion term vanishes.", steps: [
      { title: "Start from the SDE", body: "Use a drift pulling variance toward θ and a zero-mean diffusion innovation." },
      { title: "Take conditional expectation", body: "The Itô integral has zero conditional expectation under integrability conditions.", latex: "dm(\\tau)=\\kappa(\\theta-m(\\tau))d\\tau" },
      { title: "Solve the linear ODE", body: "Apply an integrating factor or recognize exponential decay.", latex: "m(\\tau)=\\theta+(v_t-\\theta)e^{-\\kappa\\tau}" },
      { title: "Interpret term dynamics", body: "Large κ localizes variance shocks in short maturities; θ anchors the long end." },
      { title: "Restore distributional risk", body: "The mean omits η, ρ and higher moments; pricing requires the full joint process and a risk-neutral parameterization." },
    ], conclusion: "Mean reversion explains level decay, while vol-of-vol and correlation determine smile curvature and leverage dynamics.", method: "Choose a variance process compatible with the payoff and numerical engine; validate moments, positivity behavior and limiting cases.", calibration: "Fit liquid surface nodes with constrained multi-start optimization, then evaluate parameter stability and exotic hedge behavior.", limitations: ["Parameters can be weakly identified.", "Risk-neutral and physical dynamics differ.", "Naive discretization biases variance and can cross zero."],
    python: { title: "Mean-reverting variance paths", objective: "Simulate a positive teaching process and verify the conditional mean direction.", code: `from __future__ import annotations\n\nimport numpy as np\n\ndef variance_paths(paths: int = 10_000, steps: int = 252, seed: int = 4) -> np.ndarray:\n    rng = np.random.default_rng(seed)\n    v = np.full(paths, 0.09)\n    dt, kappa, theta, eta = 1 / steps, 2.0, 0.04, 0.35\n    for _ in range(steps):\n        vp = np.maximum(v, 0.0)\n        v += kappa * (theta - vp) * dt + eta * np.sqrt(vp * dt) * rng.standard_normal(paths)\n    return np.maximum(v, 0.0)\n\nv = variance_paths()\nassert np.isfinite(v).all() and np.all(v >= 0.0)\nassert abs(float(v.mean()) - 0.04) < 0.03\nprint(round(float(v.mean()), 5))`, output: ["A deterministic terminal mean near the long-run variance."], checks: ["Seed is fixed.", "Diffusion uses non-negative variance.", "Mean-reversion direction is tested."] },
    lab: { id: "stochastic-volatility", title: "Variance-state lab", description: "Shock κ, θ, vol-of-vol and correlation; animate variance paths and surface response." }, deskQuote: "A parameter is hedgeable only through the instruments that move it.", inputs: ["surface snapshot", "variance proxy", "parameter bounds", "engine", "weights"], risk: ["variance delta", "vol-of-vol", "correlation", "parameter drift"], workflow: ["select process", "calibrate", "validate moments", "simulate", "stress hedges"], productionIssues: ["negative variance scheme", "optimizer traps", "unstable Greeks", "measure confusion"], macro: { title: "Volatility as a persistent state", thesis: "Risk shocks lift a variance state that decays rather than disappearing at the next close, producing clustering and term-structure effects.", nodes: [{ label: "Risk shock", effect: "raises variance state" }, { label: "Vol-of-vol", effect: "controls state dispersion" }, { label: "Mean reversion", effect: "sets persistence" }, { label: "Surface dynamics", effect: "moves level and skew" }] }, pitfalls: ["Reading risk-neutral parameters as physical forecasts.", "Ignoring the variance discretization scheme.", "Equating a good static fit with stable hedges.", "Calibrating without multiple starts."], related: ["vol-local", "vol-heston", "vol-sabr"],
  },
  {
    id: "vol-sabr", slug: "sabr", title: "SABR", subtitle: "Forward smile dynamics through backbone, correlation and vol-of-vol", level: "front-office", minutes: 72,
    legacyRoutes: ["/learn/equity/sabr"], prerequisites: ["Stochastic volatility", "Black–76", "Asymptotic expansions"], objectives: ["Interpret α, β, ρ and ν economically.", "Read the Hagan approximation in forward-moneyness coordinates.", "Diagnose normal versus lognormal conventions.", "Calibrate with stable parameter transformations."], tags: ["SABR", "rates volatility", "Hagan", "backbone", "vol of vol"],
    lead: "SABR couples a forward with a stochastic volatility factor. β controls the backbone, ρ the skew channel and ν the smile curvature; the widely quoted formula is an asymptotic approximation, not the SDE itself.", points: ["β is commonly fixed because all four parameters are not equally identifiable.", "Shifted lognormal or normal variants are required near negative rates.", "The approximation loses accuracy in extreme wings and long horizons."], why: "SABR remains a central quoting and interpolation model for caps, floors and swaptions and is useful for studying forward-smile dynamics.", instruments: ["caps and floors", "swaptions", "commodity options", "FX variants"], quote: "State normal, lognormal or shifted-lognormal volatility, forward, shift, delta/strike coordinate and annuity conventions.", notation: ["F_t: forward", "α_t: stochastic scale", "β: backbone elasticity", "ν: vol of vol", "ρ: correlation"],
    formulas: [
      { label: "SABR dynamics", latex: "dF_t=\\alpha_tF_t^\\beta dW_t^1,\\qquad d\\alpha_t=\\nu\\alpha_tdW_t^2", interpretation: "A stochastic scale drives a CEV-style forward diffusion." },
      { label: "Correlation", latex: "d\\langle W^1,W^2\\rangle_t=\\rho\\,dt", interpretation: "Correlation contributes the leading skew effect." },
      { label: "ATM leading order", latex: "\\sigma_{ATM}\\approx\\frac{\\alpha}{F^{1-\\beta}}\\left[1+T\\left(\\frac{(1-\\beta)^2\\alpha^2}{24F^{2-2\\beta}}+\\frac{\\rho\\beta\\nu\\alpha}{4F^{1-\\beta}}+\\frac{(2-3\\rho^2)\\nu^2}{24}\\right)\\right]", interpretation: "ATM volatility mixes scale, backbone, correlation and vol-of-vol corrections." },
    ], derivationTitle: "Reading the SABR asymptotic structure", derivationIntro: "The complete expansion is lengthy; the useful derivation is to identify leading scale and first correction channels.", steps: [
      { title: "Freeze stochastic scale", body: "At leading order, α/F^(1-β) supplies the local ATM volatility." },
      { title: "Introduce log-moneyness", body: "The expansion uses z proportional to ν/α times a backbone-adjusted forward-strike distance." },
      { title: "Correct the strike geometry", body: "The z/x(z) ratio introduces asymmetric smile response through ρ." },
      { title: "Add maturity corrections", body: "Backbone curvature, correlation and vol-of-vol contribute O(T) terms." },
      { title: "Control the limit at ATM", body: "Use the analytical z→0 limit rather than direct division to avoid cancellation.", check: "Test ATM continuity, ν→0 and F→K limits." },
    ], conclusion: "SABR is powerful because parameters map to smile features, but robust use requires convention control, asymptotic guards and calibration governance.", method: "Fix or regularize β, transform constrained parameters, price under the correct volatility convention and use stable ATM limits.", calibration: "Fit α, ρ and ν to liquid smile quotes with bounded transforms and maturity-to-maturity regularization.", limitations: ["Asymptotic error in wings and long maturities.", "Parameters can be non-unique.", "Lognormal form fails at non-positive forwards without a shift."],
    python: { title: "SABR parameter-domain guard", objective: "Validate a calibration state and compute the leading ATM scale.", code: `from __future__ import annotations\n\nimport math\n\ndef sabr_atm_leading(forward: float, alpha: float, beta: float, rho: float, nu: float) -> float:\n    if forward <= 0 or alpha <= 0 or nu < 0 or not 0 <= beta <= 1 or not -1 < rho < 1:\n        raise ValueError("invalid SABR parameter domain")\n    result = alpha / forward ** (1.0 - beta)\n    if not math.isfinite(result) or result <= 0:\n        raise ArithmeticError("invalid ATM volatility")\n    return result\n\nsigma = sabr_atm_leading(0.035, 0.03, 0.5, -0.25, 0.4)\nassert abs(sigma - 0.1603567451) < 1e-9\nprint(f"{sigma:.4%}")`, output: ["16.0357% leading-order ATM volatility."], checks: ["Forward and α are positive.", "β and ρ respect domains.", "Known analytical leading value is asserted."] },
    lab: { id: "sabr", title: "SABR smile lab", description: "Move α, β, ρ and ν; inspect backbone, smile and parameter sensitivities." }, deskQuote: "If β moves every day, the optimizer may be explaining the coordinate system.", inputs: ["forward and annuity", "smile quotes", "vol convention", "shift", "β policy"], risk: ["alpha level", "rho skew", "nu curvature", "backbone delta"], workflow: ["normalize convention", "fix β/shift", "calibrate", "check limits", "compare stability"], productionIssues: ["wrong normal/lognormal quote", "ATM cancellation", "unbounded rho", "parameter jumps"], macro: { title: "Rate regime and the SABR backbone", thesis: "The forward level and volatility convention change how an identical basis-point shock appears in percentage-volatility space.", nodes: [{ label: "Rate regime", effect: "moves forward and sign constraints" }, { label: "Backbone β", effect: "maps level to volatility" }, { label: "Smile parameters", effect: "fit skew and curvature" }, { label: "Desk quote", effect: "depends on convention" }] }, pitfalls: ["Using lognormal SABR at non-positive forwards.", "Calibrating every parameter without identifiability checks.", "Ignoring the ATM limit.", "Presenting asymptotic output as exact model price."], related: ["vol-stochastic", "vol-calibration", "vol-higher-risk"],
  },
  {
    id: "vol-calibration", slug: "calibration", title: "Volatility-model calibration", subtitle: "Turning quotes into parameters without mistaking fit for identification", level: "front-office", minutes: 70,
    legacyRoutes: [], prerequisites: ["Implied volatility surface", "Optimization", "Numerical sensitivities"], objectives: ["Formulate premium- and volatility-space objectives.", "Choose weights consistent with liquidity and units.", "Diagnose identifiability and parameter instability.", "Build reproducible calibration governance."], tags: ["calibration", "optimization", "residuals", "regularization", "model risk"],
    lead: "Calibration chooses model parameters that reproduce selected market quotes under an objective function. A low scalar error can hide systematic residuals, unidentifiable parameters and unstable hedges.", points: ["The objective defines what good fit means.", "Weights encode liquidity, units and desk priorities.", "Stability through time is evidence alongside cross-sectional fit."], why: "Every surface model and stochastic process requires a repeatable path from cleaned quotes to parameters, diagnostics and fallback decisions.", instruments: ["vanilla calibration baskets", "caps/floors", "swaptions", "exotic proxy instruments"], quote: "State calibration instruments, timestamp, bid/offer, objective units, weights, parameter transforms and solver tolerances.", notation: ["θ: parameter vector", "q_i: market quote", "m_i(θ): model quote", "W: weight matrix", "λR(θ): regularizer"],
    formulas: [
      { label: "Weighted least squares", latex: "\\widehat\\theta=\\arg\\min_\\theta\\sum_i w_i\\left(m_i(\\theta)-q_i\\right)^2+\\lambda R(\\theta)", interpretation: "Fit and regularization are explicit modelling choices." },
      { label: "Gauss–Newton step", latex: "(J^TWJ+\\lambda I)\\Delta\\theta=-J^TWr", interpretation: "The Jacobian reveals local parameter sensitivity and conditioning." },
      { label: "Conditioning", latex: "\\kappa(J^TWJ)=\\frac{\\lambda_{max}}{\\lambda_{min}}", interpretation: "A large condition number signals weak local identification." },
    ], derivationTitle: "From quote residuals to a parameter update", derivationIntro: "Linearize model quotes around the current parameter vector.", steps: [
      { title: "Define residuals", body: "Choose premium, implied-volatility or normalized residuals and preserve their units.", latex: "r_i(\\theta)=m_i(\\theta)-q_i" },
      { title: "Linearize the model", body: "Approximate residuals for a small parameter update using the Jacobian.", latex: "r(\\theta+\\Delta)\\approx r(\\theta)+J\\Delta" },
      { title: "Form the quadratic objective", body: "Insert the linearization into weighted least squares and add damping or regularization." },
      { title: "Set the gradient to zero", body: "The normal equations produce a local Gauss–Newton step.", latex: "(J^TWJ+\\lambda I)\\Delta=-J^TWr" },
      { title: "Accept only validated steps", body: "Reprice, enforce domains, inspect residual shape and compare parameters with previous snapshots.", check: "Convergence means the optimizer stopped—not that the model is identified." },
    ], conclusion: "A calibration result is a parameter vector plus residuals, conditioning, constraints, lineage and a decision on whether it is safe to use.", method: "Use bounded parameter transforms, deterministic multi-starts, analytical or validated sensitivities, and a documented fallback.", calibration: "This lesson calibrates calibration itself: choose objective, weights, basket, regularization and stopping rules before fitting the production model.", limitations: ["Non-convex objectives have local minima.", "Sparse quotes weakly identify parameters.", "Different units and weights produce different optima."],
    python: { title: "Linear calibration diagnostic", objective: "Solve a weighted linearized fit and inspect conditioning.", code: `from __future__ import annotations\n\nimport numpy as np\n\ndef gauss_newton_step(jacobian: np.ndarray, residual: np.ndarray, damping: float = 1e-6) -> tuple[np.ndarray, float]:\n    if jacobian.shape[0] != residual.size or damping < 0:\n        raise ValueError("invalid calibration dimensions")\n    normal = jacobian.T @ jacobian + damping * np.eye(jacobian.shape[1])\n    step = np.linalg.solve(normal, -(jacobian.T @ residual))\n    return step, float(np.linalg.cond(normal))\n\nj = np.array([[1.0, 0.1], [1.0, 0.4], [1.0, 0.9]])\nr = np.array([0.01, -0.005, 0.002])\nstep, condition = gauss_newton_step(j, r)\nassert np.isfinite(step).all() and np.isfinite(condition)\nassert np.linalg.norm(j @ step + r) < np.linalg.norm(r)\nprint(np.round(step, 6), round(condition, 2))`, output: ["A residual-reducing step and finite condition number."], checks: ["Dimensions are validated.", "Damping is non-negative.", "The linearized residual decreases."] },
    lab: { id: "calibration", title: "Calibration residual lab", description: "Change weights, noise and initial parameters; watch optimizer path, residual heatmap and conditioning." }, deskQuote: "A perfect fit with unstable parameters is an expensive interpolation scheme.", inputs: ["timestamped quotes", "bid/offer", "basket", "weights", "constraints"], risk: ["parameter jump", "basis residual", "solver risk", "model selection"], workflow: ["freeze snapshot", "clean basket", "multi-start fit", "inspect residuals", "approve/fallback"], productionIssues: ["unit mismatch", "silent constraint binding", "nondeterministic start", "missing diagnostics"], macro: { title: "Regime shifts expose parameter identification", thesis: "When the surface changes shape, parameters that were redundant in calm markets can move abruptly or hit bounds.", nodes: [{ label: "Regime shift", effect: "changes quote geometry" }, { label: "Calibration basket", effect: "exposes sensitivities" }, { label: "Parameters", effect: "move or become unstable" }, { label: "Model governance", effect: "accepts, regularizes or falls back" }] }, pitfalls: ["Reporting only RMSE.", "Mixing premium and vol residuals without normalization.", "Using one starting point.", "Ignoring day-over-day parameter stability."], related: ["vol-surface", "vol-heston", "vol-sabr", "vol-higher-risk"],
  },
  {
    id: "vol-higher-risk", slug: "vega-vanna-volga", title: "Vega, vanna and volga", subtitle: "The local geometry of volatility P&L beyond first order", level: "front-office", minutes: 58,
    legacyRoutes: [], prerequisites: ["Black–Scholes Greeks", "Taylor expansion", "Volatility surface"], objectives: ["Use platform units for vega, vanna and volga.", "Derive a second-order spot-volatility P&L expansion.", "Connect surface moves to cross-Greek exposure.", "Identify finite-difference and aggregation failures."], tags: ["vega", "vanna", "volga", "P&L explain", "cross gamma"],
    lead: "Vega describes a parallel local volatility move. Vanna and volga explain how delta changes with volatility and how vega curves with volatility—terms that become material during combined spot and surface shocks.", points: ["Greek units must match the scenario units.", "Vanna is a cross derivative, so sign conventions depend on definitions.", "Surface risk is bucketed; one scalar vega hides strike and maturity structure."], why: "Volatility books are explained and hedged through bucketed first- and second-order sensitivities before full repricing closes the residual.", instruments: ["vanilla option books", "risk reversals", "barriers", "volatility swaps"], quote: "Platform convention: vega per one volatility point, theta per calendar day and rho per 100bp. State the exact vanna definition used.", notation: ["ν=∂V/∂σ: raw vega", "Vanna=∂²V/(∂S∂σ)", "Volga=∂²V/∂σ²", "Δσ_pts: volatility-point move"],
    formulas: [
      { label: "Vega point unit", latex: "\\nu_{1pt}=0.01\\,\\frac{\\partial V}{\\partial\\sigma}", interpretation: "P&L for a one percentage-point volatility move." },
      { label: "Second-order spot-vol expansion", latex: "\\Delta V\\approx\\Delta\\,\\Delta S+\\nu\\,\\Delta\\sigma+\\tfrac12\\Gamma(\\Delta S)^2+\\operatorname{Vanna}\\,\\Delta S\\Delta\\sigma+\\tfrac12\\operatorname{Volga}(\\Delta\\sigma)^2", interpretation: "Cross and curvature terms matter when spot and volatility move together." },
      { label: "Black–Scholes volga", latex: "\\operatorname{Volga}=\\nu\\frac{d_1d_2}{\\sigma}", interpretation: "The sign and magnitude vary by moneyness and maturity." },
    ], derivationTitle: "A two-factor Taylor P&L explain", derivationIntro: "Expand option value in spot and volatility around the current state while holding stated conventions fixed.", steps: [
      { title: "Choose state variables", body: "Treat V=V(S,σ,t,...) locally; for a surface, σ means a stated bucket or deformation." },
      { title: "Write first-order terms", body: "Delta and raw vega multiply changes in spot and decimal volatility.", latex: "dV\\approx V_SdS+V_\\sigma d\\sigma" },
      { title: "Add pure curvature", body: "Gamma and volga capture second-order effects in each factor." },
      { title: "Add the mixed derivative", body: "Symmetry of smooth mixed partials combines the two half cross terms into vanna times dS dσ.", latex: "V_{S\\sigma}dSd\\sigma" },
      { title: "Convert units before attribution", body: "If vega is per point, multiply by Δσ in points; if raw, multiply by decimal Δσ.", check: "A 5-point move is 0.05 in raw-vega units and 5 in point-vega units." },
    ], conclusion: "Higher-order Greeks are local approximations whose usefulness depends on clear units, surface buckets and comparison with full repricing.", method: "Compute analytical Greeks where possible; otherwise use symmetric bumps sized above numerical noise and below nonlinear regime changes.", calibration: "Greeks are evaluated on a calibrated surface/model snapshot. Recalibrated Greeks and frozen-parameter Greeks answer different questions.", limitations: ["Local expansion fails for large discontinuous moves.", "Bucket interpolation changes aggregated risk.", "Cross-Greek definitions vary across systems."],
    python: { title: "Spot-volatility P&L expansion", objective: "Apply a second-order explain with explicit decimal-volatility units.", code: `from __future__ import annotations\n\ndef pnl(delta: float, gamma: float, raw_vega: float, vanna: float, volga: float, ds: float, dvol: float) -> float:\n    values = [delta, gamma, raw_vega, vanna, volga, ds, dvol]\n    if not all(map(lambda x: abs(x) < float("inf"), values)):\n        raise ValueError("inputs must be finite")\n    return delta*ds + 0.5*gamma*ds**2 + raw_vega*dvol + vanna*ds*dvol + 0.5*volga*dvol**2\n\nexplained = pnl(0.55, 0.018, 38.0, -0.22, 12.0, -4.0, 0.05)\nassert abs(explained - (-0.078)) < 1e-12\nprint(round(explained, 6))`, output: ["-0.078000 model-currency units."], checks: ["All inputs are finite.", "Volatility change is decimal.", "Reference P&L is asserted analytically."] },
    lab: { id: "higher-order-risk", title: "Volatility P&L explain lab", description: "Shock spot and surface level; compare first order, cross/curvature terms and full repricing." }, deskQuote: "The unexplained P&L often has a Greek; it may not have the Greek you reported.", inputs: ["position state", "surface buckets", "spot/forward", "bump sizes", "recalibration policy"], risk: ["bucketed vega", "vanna", "volga", "surface gamma"], workflow: ["freeze state", "compute Greeks", "observe moves", "explain P&L", "full reprice"], productionIssues: ["point/raw vega mix", "asymmetric bumps", "unstable recalibration", "double-counted buckets"], macro: { title: "Spot-vol correlation drives cross-Greek P&L", thesis: "Risk-off regimes combine falling spot and rising downside volatility, making vanna and skew exposure central to the book response.", nodes: [{ label: "Risk-off shock", effect: "spot falls" }, { label: "Surface", effect: "level and skew rise" }, { label: "Vanna/volga", effect: "add nonlinear P&L" }, { label: "Hedge residual", effect: "requires full repricing" }] }, pitfalls: ["Mixing raw and point vega.", "Reporting one scalar vega for a structured surface book.", "Using oversized finite-difference bumps.", "Treating Taylor explain as exact pricing."], related: ["vol-calibration", "vol-sabr", "vol-heston"],
  },
];

export const additionalVolatilityLessons: AcademyLesson[] = seeds.map((seed) => {
  const formulaContract = formulaContracts[seed.id];
  return {
  id: seed.id,
  slug: seed.slug,
  title: seed.title,
  subtitle: seed.subtitle,
  domain: "volatility",
  assetClass: "EQ",
  level: seed.level,
  prerequisites: seed.prerequisites,
  learningObjectives: seed.objectives,
  tags: seed.tags,
  estimatedMinutes: seed.minutes,
  lastReviewed: reviewed,
  legacyRoutes: seed.legacyRoutes,
  intuition: { lead: seed.lead, points: seed.points },
  marketContext: { why: seed.why, instruments: seed.instruments, quoteConvention: seed.quote },
  mathematics: { notation: seed.notation, formulas: seed.formulas.map((formula, index) => ({ ...formula, depth: formulaContract.formulaDepths[index], analyticsHref: formulaContract.formulaAnalyticsHrefs?.[index] })) },
  derivation: { formulaIndex: formulaContract.derivationFormulaIndex, depth: formulaContract.derivationDepth, title: seed.derivationTitle, introduction: seed.derivationIntro, steps: seed.steps, conclusion: seed.conclusion },
  pricing: { method: seed.method, calibration: seed.calibration, limitations: seed.limitations },
  implementation: {
    architecture: ["Validate domains and units at the boundary.", "Keep the numerical kernel framework-free and deterministic.", "Return diagnostics with values.", "Test analytical limits and failure states."],
    quantLib: "Current QuantLib separates market structures, processes, instruments, engines and calibration helpers. Use those abstractions only after the lesson’s conventions, domains and numerical checks are explicit.",
    pythonLab: seed.python,
  },
  interactiveLabs: [seed.lab],
  frontOffice: { quote: seed.deskQuote, inputs: seed.inputs, calibration: seed.calibration, risk: seed.risk, workflow: seed.workflow, productionIssues: seed.productionIssues },
  macroConnections: [seed.macro],
  pitfalls: seed.pitfalls,
  references,
  relatedLessonIds: seed.related,
  };
});
