import { localizedText as t, type AnalyticsScenario } from "../types";

export const coreScenarios: readonly AnalyticsScenario[] = [
  {
    id: "vanilla-equity-carry",
    labId: "vanilla",
    name: t("Equity carry and moneyness", "Carry de equity y moneyness"),
    description: t("Separate spot, carry and strike before reading the option premium.", "Separa spot, carry y strike antes de interpretar la prima de la opción."),
    learningObjective: t("Understand how rates and dividends move the forward while discounting acts on the payoff value.", "Entender cómo tipos y dividendos mueven el forward mientras el descuento actúa sobre el valor del payoff."),
    initialInputs: { mode: "equity", spot: 100, strike: 100, time: 1, rate: 0.04, dividend: 0.015, volatility: 0.22, optionType: "call" },
    expectedObservation: t("The forward sits above spot because r > q; the call contains both intrinsic convention and time value.", "El forward queda por encima del spot porque r > q; la call contiene tanto la convención de intrínseco como valor temporal."),
    suggestedInteractions: [t("Raise the dividend yield while holding every other input fixed.", "Sube la rentabilidad por dividendo manteniendo fijos los demás inputs."), t("Move spot through strike and watch delta as well as price.", "Mueve el spot a través del strike y observa delta además del precio.")],
    explanation: t("Under Black–Scholes, F(0,T)=S₀e^{(r−q)T}. A higher dividend yield lowers the forward and, all else equal, lowers a call value.", "En Black–Scholes, F(0,T)=S₀e^{(r−q)T}. Un mayor dividendo reduce el forward y, ceteris paribus, el valor de una call."),
    modelBoundary: t("Constant volatility and continuous carry do not reproduce discrete dividends or a changing volatility surface.", "La volatilidad constante y el carry continuo no reproducen dividendos discretos ni una superficie de volatilidad cambiante."),
    difficulty: "foundation",
    academyHref: "/learn/derivatives/black-scholes-replication-pricing",
  },
  {
    id: "vanilla-fx-carry",
    labId: "vanilla",
    name: t("FX domestic versus foreign rate", "FX: tipo doméstico frente a extranjero"),
    description: t("Price the same option after making both currency carries explicit.", "Valora la misma opción haciendo explícitos los carry de ambas divisas."),
    learningObjective: t("Distinguish domestic discounting from the foreign rate that acts like a dividend yield on spot FX.", "Distinguir el descuento doméstico del tipo extranjero, que actúa como dividendo sobre el spot FX."),
    initialInputs: { mode: "fx", spot: 1.08, strike: 1.1, time: 1, domesticRate: 0.04, foreignRate: 0.025, volatility: 0.12, optionType: "call" },
    expectedObservation: t("The forward is above spot because the domestic rate exceeds the foreign rate.", "El forward queda por encima del spot porque el tipo doméstico supera al extranjero."),
    suggestedInteractions: [t("Swap the domestic and foreign rates.", "Intercambia los tipos doméstico y extranjero."), t("Check call–put parity in the displayed currency convention.", "Comprueba la paridad call–put en la convención de divisa mostrada.")],
    explanation: t("Garman–Kohlhagen uses F=S₀e^{(r_d−r_f)T}; r_f is carry on the foreign asset, while r_d discounts domestic cash flows.", "Garman–Kohlhagen usa F=S₀e^{(r_d−r_f)T}; r_f es el carry del activo extranjero y r_d descuenta los flujos domésticos."),
    modelBoundary: t("The result assumes deterministic rates, one volatility input and a reconciled premium/settlement convention.", "El resultado supone tipos deterministas, una única volatilidad y convenciones de prima y liquidación reconciliadas."),
    difficulty: "practitioner",
    academyHref: "/learn/foundations/numeraires-forward-measures",
  },
  {
    id: "vanilla-black76-forward",
    labId: "vanilla",
    name: t("Black-76 forward option", "Opción sobre forward Black-76"),
    description: t("Use an observable forward as the state variable instead of reconstructing it from spot carry.", "Usa un forward observable como variable de estado en lugar de reconstruirlo desde el carry del spot."),
    learningObjective: t("Separate the forward distribution from discounting and avoid mixing spot and forward conventions.", "Separar la distribución del forward del descuento y evitar mezclar convenciones spot y forward."),
    initialInputs: { mode: "forward", forward: 100, strike: 105, time: 1, rate: 0.04, volatility: 0.25, optionType: "call" },
    expectedObservation: t("Changing the discount rate scales present value while the supplied forward remains the modeled underlying.", "Cambiar el tipo de descuento escala el valor presente mientras el forward suministrado sigue siendo el subyacente modelizado."),
    suggestedInteractions: [t("Change the rate without changing the forward.", "Cambia el tipo sin cambiar el forward."), t("Move the forward through strike and inspect delta in forward units.", "Mueve el forward a través del strike e inspecciona delta en unidades de forward.")],
    explanation: t("Black-76 prices the discounted expectation of the terminal forward payoff; the forward is an input, not S₀ grown again by carry.", "Black-76 valora la esperanza descontada del payoff sobre el forward terminal; el forward es un input, no un S₀ al que se vuelve a aplicar carry."),
    modelBoundary: t("A lognormal forward with constant volatility cannot represent negative forwards or smile dynamics.", "Un forward lognormal con volatilidad constante no representa forwards negativos ni dinámica de smile."),
    difficulty: "practitioner",
    academyHref: "/learn/foundations/numeraires-forward-measures",
  },
  {
    id: "black-scholes-atm-expiry",
    labId: "black-scholes",
    name: t("ATM near expiry", "ATM cerca del vencimiento"),
    description: t("Concentrate the exercise boundary to expose gamma and theta together.", "Concentra la frontera de ejercicio para mostrar gamma y theta conjuntamente."),
    learningObjective: t("See why short-dated ATM convexity is large and why its carry cost is inseparable from it.", "Ver por qué la convexidad ATM de corto plazo es alta y por qué su coste de carry es inseparable."),
    initialInputs: { spot: 100, strike: 100, time: 0.08, rate: 0.03, dividend: 0.01, volatility: 0.2, optionType: "call" },
    expectedObservation: t("Delta changes through a narrow spot interval, gamma rises and theta becomes more negative for the long option.", "Delta cambia en un intervalo de spot estrecho, gamma aumenta y theta se hace más negativa para la opción comprada."),
    suggestedInteractions: [t("Move spot from 95 to 105.", "Mueve el spot de 95 a 105."), t("Increase maturity to one year without changing volatility.", "Aumenta el vencimiento a un año sin cambiar la volatilidad.")],
    explanation: t("Γ=e^{−qT}φ(d₁)/(Sσ√T). Near ATM, φ(d₁) remains material while √T shrinks; theta finances that convexity.", "Γ=e^{−qT}φ(d₁)/(Sσ√T). Cerca de ATM, φ(d₁) sigue siendo material mientras √T disminuye; theta financia esa convexidad."),
    modelBoundary: t("Continuous hedging and diffusion assumptions are least credible when expiry, jumps and execution effects matter most.", "Los supuestos de cobertura continua y difusión son menos creíbles cuando vencimiento, saltos y ejecución importan más."),
    difficulty: "practitioner",
    academyHref: "/learn/risk/higher-order-greeks",
  },
  {
    id: "black-scholes-long-vega",
    labId: "black-scholes",
    name: t("Long-dated volatility exposure", "Exposición a volatilidad de largo plazo"),
    description: t("Extend maturity to separate broad volatility exposure from concentrated short-term convexity.", "Extiende el vencimiento para separar exposición amplia a volatilidad de convexidad concentrada a corto plazo."),
    learningObjective: t("Compare the √T scaling of vega with the 1/√T concentration of gamma near ATM.", "Comparar el escalado √T de vega con la concentración 1/√T de gamma cerca de ATM."),
    initialInputs: { spot: 100, strike: 100, time: 2, rate: 0.03, dividend: 0.01, volatility: 0.2, optionType: "call" },
    expectedObservation: t("Vega is larger and gamma is less concentrated than in the short-dated ATM example.", "Vega es mayor y gamma está menos concentrada que en el ejemplo ATM de corto plazo."),
    suggestedInteractions: [t("Raise volatility by one point and compare the finite price move with vega.", "Sube la volatilidad un punto y compara el movimiento finito del precio con vega."), t("Shorten maturity while keeping moneyness fixed.", "Acorta el vencimiento manteniendo fijo el moneyness.")],
    explanation: t("Black–Scholes vega is S e^{−qT}φ(d₁)√T. It is a local derivative, so a finite volatility move also contains curvature and coordinate assumptions.", "La vega Black–Scholes es S e^{−qT}φ(d₁)√T. Es una derivada local, por lo que un movimiento finito de volatilidad también contiene curvatura y supuestos de coordenadas."),
    modelBoundary: t("One parallel volatility input ignores term, skew, sticky-strike/sticky-delta and recalibration effects.", "Una única volatilidad paralela ignora plazo, skew, sticky-strike/sticky-delta y efectos de recalibración."),
    difficulty: "practitioner",
    academyHref: "/learn/risk/first-order-greeks",
  },
  {
    id: "greeks-through-strike",
    labId: "greeks",
    name: t("Move spot through strike", "Mover spot a través del strike"),
    description: t("Trace the delta transition and its gamma slope around the exercise boundary.", "Sigue la transición de delta y su pendiente gamma alrededor de la frontera de ejercicio."),
    learningObjective: t("Interpret gamma as the local rate of change of delta rather than as a standalone P&L forecast.", "Interpretar gamma como la tasa local de cambio de delta, no como una previsión aislada de P&L."),
    initialInputs: { spot: 90, strike: 100, time: 0.5, rate: 0.03, dividend: 0.01, volatility: 0.22, selectedGreek: "gamma" },
    expectedObservation: t("Gamma peaks near the forward-adjusted strike while delta transitions from low to high call exposure.", "Gamma alcanza su máximo cerca del strike ajustado por forward mientras delta transita de baja a alta exposición de call."),
    suggestedInteractions: [t("Move spot slowly from 90 to 110.", "Mueve el spot lentamente de 90 a 110."), t("Switch between delta and gamma without changing inputs.", "Alterna entre delta y gamma sin cambiar inputs.")],
    explanation: t("Gamma is ∂Δ/∂S. The smooth Black–Scholes transition approximates a terminal exercise indicator before expiry.", "Gamma es ∂Δ/∂S. La transición suave de Black–Scholes aproxima un indicador terminal de ejercicio antes del vencimiento."),
    modelBoundary: t("A local derivative describes infinitesimal moves; finite moves require repricing and can cross different surface regimes.", "Una derivada local describe movimientos infinitesimales; los movimientos finitos requieren revaloración y pueden cruzar distintos regímenes de superficie."),
    difficulty: "foundation",
    academyHref: "/learn/risk/first-order-greeks",
  },
  {
    id: "greeks-gamma-theta",
    labId: "greeks",
    name: t("Gamma–theta exchange", "Intercambio gamma–theta"),
    description: t("Shorten time while holding ATM moneyness to expose convexity carry.", "Acorta el tiempo manteniendo moneyness ATM para mostrar el carry de convexidad."),
    learningObjective: t("Connect the benefit of long gamma to the theta paid while the hedge is rebalanced discretely.", "Conectar el beneficio de gamma comprada con la theta pagada mientras la cobertura se rebalancea discretamente."),
    initialInputs: { spot: 100, strike: 100, time: 0.12, rate: 0.03, dividend: 0.01, volatility: 0.2, selectedGreek: "theta" },
    expectedObservation: t("Shorter maturity makes both gamma concentration and negative long-option theta more pronounced.", "Un vencimiento menor hace más pronunciadas tanto la concentración de gamma como la theta negativa de la opción comprada."),
    suggestedInteractions: [t("Compare 0.12 years with one year.", "Compara 0,12 años con un año."), t("Move away from ATM and observe both magnitudes decay.", "Aléjate de ATM y observa cómo disminuyen ambas magnitudes.")],
    explanation: t("In the diffusion PDE, theta, carry and gamma terms jointly reconcile the locally hedged option. They are not independent sources of value.", "En la PDE de difusión, theta, carry y los términos gamma reconcilian conjuntamente la opción cubierta localmente. No son fuentes de valor independientes."),
    modelBoundary: t("Realized hedge P&L depends on paths, jumps, costs and rehedging frequency, none of which a static Greek panel captures.", "El P&L realizado de cobertura depende de trayectorias, saltos, costes y frecuencia de rebalanceo, que un panel estático de griegas no captura."),
    difficulty: "practitioner",
    academyHref: "/learn/risk/hedging-pnl-attribution",
  },
  {
    id: "greeks-finite-vega",
    labId: "greeks",
    name: t("Local vega versus finite repricing", "Vega local frente a revaloración finita"),
    description: t("Compare a derivative at the base point with a genuine volatility shock.", "Compara una derivada en el punto base con un shock real de volatilidad."),
    learningObjective: t("Recognize that vega times a shock is a first-order approximation, not the repriced P&L authority.", "Reconocer que vega por un shock es una aproximación de primer orden, no la autoridad del P&L revalorado."),
    initialInputs: { spot: 100, strike: 105, time: 1, rate: 0.03, dividend: 0.01, volatility: 0.18, selectedGreek: "vega" },
    expectedObservation: t("A one-point move is close to vega; a larger move reveals volatility curvature and changed d₁.", "Un movimiento de un punto se aproxima a vega; uno mayor revela curvatura de volatilidad y un d₁ distinto."),
    suggestedInteractions: [t("Bump volatility by one point, then by ten points.", "Mueve la volatilidad un punto y después diez puntos."), t("Repeat at a deep ITM or OTM spot.", "Repite con spot muy ITM u OTM.")],
    explanation: t("ΔV≈νΔσ is the first Taylor term. Finite repricing incorporates the changing sensitivity along the move.", "ΔV≈νΔσ es el primer término de Taylor. La revaloración finita incorpora la sensibilidad cambiante a lo largo del movimiento."),
    modelBoundary: t("The experiment still bumps one flat volatility rather than moving and recalibrating a complete surface.", "El experimento sigue moviendo una volatilidad plana, no una superficie completa que se desplaza y recalibra."),
    difficulty: "front-office",
    academyHref: "/learn/volatility/vega-vanna-volga",
  },
  {
    id: "curve-normal-inverted",
    labId: "yield-curve",
    name: t("Normal versus inverted curve", "Curva normal frente a invertida"),
    description: t("Change the ordering of observable zero quotes and inspect discount and forward representations.", "Cambia el orden de las cotizaciones cero observables e inspecciona las representaciones de descuento y forward."),
    learningObjective: t("Distinguish an upward zero curve from the interval forwards implied by discount-factor ratios.", "Distinguir una curva cero ascendente de los forwards por intervalo implícitos en cocientes de factores de descuento."),
    initialInputs: { nodes: [{ maturity: 0.25, rate: 0.03 }, { maturity: 1, rate: 0.034 }, { maturity: 2, rate: 0.037 }, { maturity: 5, rate: 0.042 }, { maturity: 10, rate: 0.045 }] },
    expectedObservation: t("Discount factors decline with maturity while interval forwards can be steeper than displayed zero rates.", "Los factores de descuento decrecen con el vencimiento mientras los forwards por intervalo pueden ser más pronunciados que los tipos cero mostrados."),
    suggestedInteractions: [t("Lower the five- and ten-year quotes below the front end.", "Baja las cotizaciones a cinco y diez años por debajo del tramo corto."), t("Compare the zero and forward views after rebuilding.", "Compara las vistas cero y forward tras reconstruir.")],
    explanation: t("With continuous zeros P(0,T)=e^{−z(T)T}; forwards come from log discount-factor differences, so their shape is not the zero curve copied pointwise.", "Con tipos cero continuos P(0,T)=e^{−z(T)T}; los forwards proceden de diferencias logarítmicas de factores de descuento, no de copiar punto a punto la curva cero."),
    modelBoundary: t("This educational single curve omits instrument conventions, collateral discounting and multi-curve basis.", "Esta curva educativa única omite convenciones de instrumentos, descuento colateral y base multicurva."),
    difficulty: "foundation",
    academyHref: "/learn/rates/zero-and-forward-rates",
  },
  {
    id: "curve-one-bp-node",
    labId: "yield-curve",
    name: t("Localized 1bp quote bump", "Shock localizado de 1pb en cotización"),
    description: t("Bump a calibration quote, rebuild the curve and trace dependency through maturities.", "Mueve una cotización de calibración, reconstruye la curva y sigue la dependencia entre vencimientos."),
    learningObjective: t("Separate quote risk from bumping a derived zero rate on the finished curve.", "Separar el riesgo de cotización de mover un tipo cero derivado en la curva final."),
    initialInputs: { nodes: [{ maturity: 0.25, rate: 0.03 }, { maturity: 1, rate: 0.034 }, { maturity: 2, rate: 0.0371 }, { maturity: 5, rate: 0.042 }, { maturity: 10, rate: 0.045 }], bumpedMaturity: 2, bumpBasisPoints: 1 },
    expectedObservation: t("The rebuilt two-year discount factor moves and adjacent interval forwards absorb the local quote change.", "El factor de descuento a dos años reconstruido se mueve y los forwards de intervalos adyacentes absorben el cambio local de cotización."),
    suggestedInteractions: [t("Move the 2Y quote by another basis point.", "Mueve la cotización 2Y otro punto básico."), t("Repeat at 10Y and compare propagation.", "Repite en 10Y y compara la propagación.")],
    explanation: t("A bootstrap is a dependency graph: each new instrument solves a state variable using previously calibrated nodes and its own quote.", "Un bootstrap es un grafo de dependencias: cada instrumento nuevo resuelve una variable de estado usando nodos ya calibrados y su cotización."),
    modelBoundary: t("Risk depends on the actual instrument set, interpolation and recalibration rules; a node bump is not universal DV01.", "El riesgo depende de instrumentos, interpolación y reglas de recalibración; un shock de nodo no es un DV01 universal."),
    difficulty: "front-office",
    academyHref: "/learn/rates/curve-risk",
  },
  {
    id: "curve-front-end",
    labId: "yield-curve",
    name: t("Front-end repricing", "Revaloración del tramo corto"),
    description: t("Move short quotes while the long end stays fixed.", "Mueve las cotizaciones cortas manteniendo fijo el tramo largo."),
    learningObjective: t("See why a small discount-factor move can imply a large annualized short forward change.", "Ver por qué un pequeño movimiento del factor de descuento puede implicar un gran cambio anualizado del forward corto."),
    initialInputs: { nodes: [{ maturity: 0.25, rate: 0.045 }, { maturity: 1, rate: 0.041 }, { maturity: 2, rate: 0.039 }, { maturity: 5, rate: 0.04 }, { maturity: 10, rate: 0.042 }] },
    expectedObservation: t("Front-end forwards react sharply because log discount changes are divided by short time intervals.", "Los forwards cortos reaccionan con fuerza porque los cambios logarítmicos de descuento se dividen por intervalos temporales pequeños."),
    suggestedInteractions: [t("Raise only the three-month quote.", "Sube solo la cotización a tres meses."), t("Compare discount-factor and forward axis scales.", "Compara las escalas de factores de descuento y forwards.")],
    explanation: t("f(T₁,T₂)=−[ln P(0,T₂)−ln P(0,T₁)]/(T₂−T₁). Short intervals amplify the annualized forward representation.", "f(T₁,T₂)=−[ln P(0,T₂)−ln P(0,T₁)]/(T₂−T₁). Los intervalos cortos amplifican la representación forward anualizada."),
    modelBoundary: t("Annualization amplifies display sensitivity; it does not mean the present value changed by the same percentage.", "La anualización amplifica la sensibilidad mostrada; no significa que el valor presente cambie en el mismo porcentaje."),
    difficulty: "practitioner",
    academyHref: "/learn/rates/curve-bootstrapping",
  },
];

