import { localizedText as t, type AnalyticsScenario } from "../types";

export const strategyScenarios: readonly AnalyticsScenario[] = [
  {
    id: "strategy-bull-call",
    labId: "strategies",
    sourceId: "bull-call",
    name: t("Bull call spread", "Spread alcista con calls"),
    description: t("Exchange unlimited upside for lower premium and a bounded terminal range.", "Intercambia upside ilimitado por menor prima y un rango terminal acotado."),
    learningObjective: t("Derive capped gain, finite loss and exact breakeven from signed leg algebra.", "Derivar beneficio máximo, pérdida finita y breakeven exacto desde el álgebra de patas con signo."),
    initialInputs: { presetId: "bull-call", view: "profit", settlementSpot: 100 },
    expectedObservation: t("The long lower-strike call creates upside; the short higher-strike call caps it and offsets premium.", "La call comprada de strike inferior crea upside; la call vendida de strike superior lo limita y compensa prima."),
    suggestedInteractions: [t("Move the short-call strike upward.", "Sube el strike de la call vendida."), t("Compare payoff with profit after premium.", "Compara payoff con beneficio tras la prima." )],
    explanation: t("Terminal profit is the signed sum of leg payoffs minus net premium. Piecewise slopes change only at strikes.", "El beneficio terminal es la suma firmada de payoffs menos la prima neta. Las pendientes por tramos cambian solo en los strikes."),
    modelBoundary: t("Terminal payoff ignores interim volatility, early exercise, liquidity and assignment; the MTM view uses the stated model assumptions.", "El payoff terminal ignora volatilidad intermedia, ejercicio anticipado, liquidez y asignación; la vista MTM usa los supuestos indicados."),
    difficulty: "foundation",
    academyHref: "/learn/derivatives/black-scholes-replication-pricing",
  },
  {
    id: "strategy-long-straddle",
    labId: "strategies",
    sourceId: "long-straddle",
    name: t("Long straddle", "Straddle comprado"),
    description: t("Buy two-sided convexity and inspect the premium hurdle.", "Compra convexidad a ambos lados e inspecciona el umbral de prima."),
    learningObjective: t("Connect convex terminal tails with positive gamma/vega and negative theta before expiry.", "Conectar colas terminales convexas con gamma/vega positivas y theta negativa antes del vencimiento."),
    initialInputs: { presetId: "long-straddle", view: "profit", settlementSpot: 100, volatilityShock: 0.05 },
    expectedObservation: t("Large moves can overcome the two premiums; small terminal moves lose the premium paid.", "Los movimientos grandes pueden superar las dos primas; los pequeños al vencimiento pierden la prima pagada."),
    suggestedInteractions: [t("Switch from terminal profit to MTM and raise volatility.", "Cambia de beneficio terminal a MTM y sube la volatilidad."), t("Advance time without moving spot.", "Avanza el tiempo sin mover el spot." )],
    explanation: t("The terminal payoff is |S_T−K| before premium. Before expiry, the position also owns volatility sensitivity and pays calendar decay.", "El payoff terminal es |S_T−K| antes de prima. Antes del vencimiento, la posición también posee sensibilidad a volatilidad y paga decaimiento temporal."),
    modelBoundary: t("A static volatility shock does not reproduce smile repricing or the path-dependent P&L of delta hedging.", "Un shock estático de volatilidad no reproduce la revaloración del smile ni el P&L dependiente de trayectoria de la cobertura delta."),
    difficulty: "practitioner",
    academyHref: "/learn/risk/higher-order-greeks",
  },
  {
    id: "strategy-iron-condor",
    labId: "strategies",
    sourceId: "iron-condor",
    name: t("Iron condor range and tails", "Rango y colas de un iron condor"),
    description: t("Sell a bounded central range while retaining explicit wing protection.", "Vende un rango central acotado manteniendo protección explícita en las alas."),
    learningObjective: t("Read maximum profit, exact breakevens and bounded tail losses from four ordered strikes.", "Leer beneficio máximo, breakevens exactos y pérdidas acotadas en colas desde cuatro strikes ordenados."),
    initialInputs: { presetId: "iron-condor", view: "profit", settlementSpot: 100, expectedRangeLow: 90, expectedRangeHigh: 110 },
    expectedObservation: t("Profit is bounded inside the short strikes and losses are capped by the purchased wings.", "El beneficio está acotado dentro de los strikes vendidos y las pérdidas quedan limitadas por las alas compradas."),
    suggestedInteractions: [t("Move one short strike inward and compare the profitable interval.", "Mueve un strike vendido hacia dentro y compara el intervalo rentable."), t("Inspect both tail plateaus and net credit.", "Inspecciona ambas mesetas de cola y el crédito neto." )],
    explanation: t("Each option changes the piecewise terminal slope at its strike. The net credit shifts the zero-profit roots without changing the far-tail slopes.", "Cada opción cambia la pendiente terminal por tramos en su strike. El crédito neto desplaza las raíces de beneficio cero sin cambiar las pendientes de cola."),
    modelBoundary: t("Bounded terminal loss does not bound interim margin, gap execution, early assignment or liquidity costs.", "La pérdida terminal acotada no limita margen intermedio, ejecución con gap, asignación anticipada ni costes de liquidez."),
    difficulty: "front-office",
    academyHref: "/learn/risk/hedging-pnl-attribution",
  },
];

